### ISSUE TITLE
The type io.netty.util.ReferenceCounted cannot be resolved. It is indirectly referenced from required .class files	BinaryDecoder.java	/WhatsappWeb4j/src/main/java/it/auties/whatsapp/binary	line 1

### ISSUE THREAD

**Issue by brunoaduarte** [Auties00/WhatsappWeb4j#100]
![image](https://user-images.githubusercontent.com/5354345/148595769-80c305b1-6c49-43ee-8918-a921e120b1de.png)

![image](https://user-images.githubusercontent.com/5354345/148595736-25dc8860-62ea-4886-8160-469dc2f6ff29.png)

![image](https://user-images.githubusercontent.com/5354345/148596489-6ac262fc-21b1-475f-851a-324e2712defe.png)

**Comment by brunoaduarte** [comment]
![image](https://user-images.githubusercontent.com/5354345/148604711-fcd9f060-0cef-4ace-a4de-cbfcab9efe30.png)

**Comment by Auties00** [comment]
> ![image](https://user-images.githubusercontent.com/5354345/148595769-80c305b1-6c49-43ee-8918-a921e120b1de.png)
> 
> ![image](https://user-images.githubusercontent.com/5354345/148595736-25dc8860-62ea-4886-8160-469dc2f6ff29.png)
> 
> ![image](https://user-images.githubusercontent.com/5354345/148596489-6ac262fc-21b1-475f-851a-324e2712defe.png)

Use Java 17
Enable preview features 
Install maven dependencies

**Comment by Auties00** [comment]
And use intellij if you can
