### ISSUE TITLE
Old version of whatsapp message

### ISSUE THREAD

**Issue by andresip** [Auties00/WhatsappWeb4j#109]
a simple text message is sent but the message has an exclamation mark, click the exclamation mark and it tells about "the message will not auto delete. sender seems using older version of whatsapp."

send code :
var chat = api.findChatByName("My Awesome Friend").orElseThrow(); // Query a chat by name
api.sendMessage(chat, "Hello my friend :)"); // Send the text message

version: 2.2.8-SNAPSHOT
can be reproduced when auto delete message of whatsapp group is enabled

**Comment by Auties00** [comment]
> a simple text message is sent but the message has an exclamation mark, click the exclamation mark and it tells about "the message will not auto delete. sender seems using older version of whatsapp."
> 
> send code : var chat = api.findChatByName("My Awesome Friend").orElseThrow(); // Query a chat by name api.sendMessage(chat, "Hello my friend :)"); // Send the text message
> 
> version: 2.2.8-SNAPSHOT can be reproduced when auto delete message of whatsapp group is enabled

Does it happen only with an exclamation mark?

**Comment by Auties00** [comment]
> a simple text message is sent but the message has an exclamation mark, click the exclamation mark and it tells about "the message will not auto delete. sender seems using older version of whatsapp."
> 
> send code : var chat = api.findChatByName("My Awesome Friend").orElseThrow(); // Query a chat by name api.sendMessage(chat, "Hello my friend :)"); // Send the text message
> 
> version: 2.2.8-SNAPSHOT can be reproduced when auto delete message of whatsapp group is enabled

Uhm, is it because it should be wrapped in an ephemeral message and it's not perhaps? It only happens when ephemeral messages are enabled?

**Comment by andresip** [comment]
> > a simple text message is sent but the message has an exclamation mark, click the exclamation mark and it tells about "the message will not auto delete. sender seems using older version of whatsapp."
> > send code : var chat = api.findChatByName("My Awesome Friend").orElseThrow(); // Query a chat by name api.sendMessage(chat, "Hello my friend :)"); // Send the text message
> > version: 2.2.8-SNAPSHOT can be reproduced when auto delete message of whatsapp group is enabled
> 
> Uhm, is it because it should be wrapped in an ephemeral message and it's not perhaps? It only happens when ephemeral messages are enabled?

Yes.

**Comment by Auties00** [comment]
Should be fixed!
