### ISSUE TITLE
Invalid/Missing Module Definition

### ISSUE THREAD

**Issue by GedMarc** [Auties00/WhatsappWeb4j#11]
JDK 16 locks down the API to the correct no-visibility encapsulation,

A module-info must be defined for JDK 16 and up, or inconsistencies will arise when accessing protected resources without an environment variable to say illegal-access=permit in JDK_JAVA_OPTIONS or JAVA_OPTIONS 

PR coming in....

**Comment by Auties00** [comment]
Hello,
thanks for opening an issue!

At one point during development, I had included a module info, but the delombok plugin had some kind of issue with it. If you manage to make it work, I'll merge it without any doubts

**Comment by GedMarc** [comment]
Hey,

The delombok is straight forward, I did a PR with it in, but it becomes an issue with the dependency graph not being modular

Unfortunately, for building distributions now, we need JMods which require strictly typed modules all the the way up the chain - on doing this the change got too large to attempt a PR.

I'm putting one together which is a completely modular implementation ready for distribution, but there are vast dependency changes to make it compatible for distribution... And as such, imp changes. In respecting your request to keep the architecture and style the same I cancelled the PR.

I'll do the delombok for you again, but give consideration to the fact the dependencies are very out of date, and are not JDK 11 compatible, let alone JDK 16 :)

I do need the library though.

**Comment by GedMarc** [comment]
```
<!-- Compile -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin-version}</version>
                <configuration>
                    <source>${java-version}</source>
                    <target>${java-version}</target>
                    <release>${java-version}</release>
                    <fork>true</fork>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>1.4.2.Final</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok-version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <annotationProcessors>
                        <annotationProcessor>lombok.launch.AnnotationProcessorHider$AnnotationProcessor</annotationProcessor>
                    </annotationProcessors>
                    <!-- Enable lombok compilation access to com.sun, and access to mapstruct to build-->
                    <compilerArgs>
                        <arg>-J--illegal-access=permit</arg>
                    </compilerArgs>
                    <failOnError>true</failOnError>
                </configuration>
            </plugin>
```

^^^ Can remove delombok with that, my module-info will be quite different to yours on the current dep graph :) 

My compile module info - https://github.com/GedMarc/WhatsappWeb4j/blob/master/src/main/java/module-info.java
My runtime module info - https://github.com/GedMarc/WhatsappWeb4j/blob/master/src/moditect/module-info.java

**Comment by GedMarc** [comment]
# Your javadoc needs the delombok sigh XD

**Comment by Auties00** [comment]
> Your javadoc needs the delombok XD
> But I don't get any errors with module-info

Thanks for your awesome contribution!
Closing the issue as the solution was merged
