### ISSUE TITLE
The contact list is empty when I have too many contats

### ISSUE THREAD

**Issue by hmbyl** [Auties00/WhatsappWeb4j#110]
The contact list is empty when I have too many contats in whatsApp。 My listener's onContacts function didn't been called after scanning the QR code.

**Comment by Auties00** [comment]
> The contact list is empty when I have too many contats in whatsApp。 My listener's onContacts function didn't been called after scanning the QR code.

Is any exception thrown?

**Comment by hmbyl** [comment]
sorry ,there is no problem. It just took about 4 minitutes to receive all contacts , because I have more than 10000 contacts
