### ISSUE TITLE
how to send message to contact first time or start a new chat

### ISSUE THREAD

**Issue by ganeshappentus** [Auties00/WhatsappWeb4j#112]
hello @Auties00 
i'm facing issue while send message to any user for first time 
according you're documentation i need to do like that

```
var chat = api.findChatByName("My Awesome Friend").orElseThrow(); // Query a chat by name
api.sendMessage(chat, "Hello my friend :)"); // Send the text message
```
but I'm not able to find new added contact like that so how i can send first to new added WhatsApp contact

please reply

**Comment by Auties00** [comment]
> hello @Auties00 i'm facing issue while send message to any user for first time according you're documentation i need to do like that
> 
> ```
> var chat = api.findChatByName("My Awesome Friend").orElseThrow(); // Query a chat by name
> api.sendMessage(chat, "Hello my friend :)"); // Send the text message
> ```
> 
> but I'm not able to find new added contact like that so how i can send first to new added WhatsApp contact
> 
> please reply

You can create a chat object from the contact using the builder, remember to assign the jid

**Comment by ganeshappentus** [comment]
thanks @Auties00 it's works for me
