### ISSUE TITLE
Update examples in multidevice branch

### ISSUE THREAD

**Issue by brunoaduarte** [Auties00/WhatsappWeb4j#114]
```
Executing pre-compile tasks…
Loading Ant configuration...
Running Ant tasks...
Cleaning output directories…
Running 'before' tasks
Checking sources
Copying resources... [ban-bot]
Parsing java… [ban-bot]
java: An exception has occurred in the compiler (17.0.2). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
java: java.util.ServiceConfigurationError: com.sun.source.util.Plugin: Provider it.auties.whatsapp.compiler.UnsupportedPlugin not found
java: 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
java: 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
java: 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
java: 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
java: 	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
java: 	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
java: 	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:220)
java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.prepareCompiler(JavacTaskImpl.java:204)
java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:101)
java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
java: 	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:238)
java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.lambda$compileJava$2(JavaBuilder.java:518)
java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.invokeJavac(JavaBuilder.java:564)
java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:516)
java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:359)
java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:284)
java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:238)
java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1507)
java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1141)
java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1288)
java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1106)
java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:877)
java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:459)
java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:197)
java: 	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:131)
java: 	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:334)
java: 	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:162)
java: 	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:218)
java: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
java: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
java: 	at java.base/java.lang.Thread.run(Thread.java:833)
java: Compilation failed: internal java compiler error
Checking dependencies… [ban-bot]
Dependency analysis found 0 affected files
Errors occurred while compiling module 'ban-bot'
javac 17.0.2 was used to compile java sources
Finished, saving caches…
Compilation failed: errors: 1; warnings: 0
Executing post-compile tasks…
Loading Ant configuration...
Running Ant tasks...
Synchronizing output directories…
14/02/2022 17:31 - Build completed with 1 error and 0 warnings in 2 sec, 878 ms
```

**Comment by Auties00** [comment]
> ```
> Executing pre-compile tasks…
> Loading Ant configuration...
> Running Ant tasks...
> Cleaning output directories…
> Running 'before' tasks
> Checking sources
> Copying resources... [ban-bot]
> Parsing java… [ban-bot]
> java: An exception has occurred in the compiler (17.0.2). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
> java: java.util.ServiceConfigurationError: com.sun.source.util.Plugin: Provider it.auties.whatsapp.compiler.UnsupportedPlugin not found
> java: 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
> java: 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
> java: 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
> java: 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
> java: 	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
> java: 	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
> java: 	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:220)
> java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.prepareCompiler(JavacTaskImpl.java:204)
> java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:101)
> java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
> java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
> java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
> java: 	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:238)
> java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.lambda$compileJava$2(JavaBuilder.java:518)
> java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.invokeJavac(JavaBuilder.java:564)
> java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:516)
> java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:359)
> java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:284)
> java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:238)
> java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1507)
> java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1141)
> java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1288)
> java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1106)
> java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:877)
> java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:459)
> java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:197)
> java: 	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:131)
> java: 	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:334)
> java: 	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:162)
> java: 	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:218)
> java: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> java: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> java: 	at java.base/java.lang.Thread.run(Thread.java:833)
> java: Compilation failed: internal java compiler error
> Checking dependencies… [ban-bot]
> Dependency analysis found 0 affected files
> Errors occurred while compiling module 'ban-bot'
> javac 17.0.2 was used to compile java sources
> Finished, saving caches…
> Compilation failed: errors: 1; warnings: 0
> Executing post-compile tasks…
> Loading Ant configuration...
> Running Ant tasks...
> Synchronizing output directories…
> 14/02/2022 17:31 - Build completed with 1 error and 0 warnings in 2 sec, 878 ms
> ```

Are you on the multi device branch?

**Comment by brunoaduarte** [comment]
> 
> Are you on the multi device branch?

Yes 👍

**Comment by Auties00** [comment]
Once the branch is done, I will update the examples

**Comment by Auties00** [comment]
Fixed in latest commit
