### ISSUE TITLE
Problem when initialize a new WhatsappAPI

### ISSUE THREAD

**Issue by frederico0102** [Auties00/WhatsappWeb4j#119]
error is in this line when this.socket = new WhatsappWebSocket(configuration, manager);
![Screenshot_1](https://user-images.githubusercontent.com/20929655/156650506-0515cdbc-ab32-4e23-9c8f-30290eae7ad4.png)

**Comment by Auties00** [comment]
> error is in this line when this.socket = new WhatsappWebSocket(configuration, manager); ![Screenshot_1](https://user-images.githubusercontent.com/20929655/156650506-0515cdbc-ab32-4e23-9c8f-30290eae7ad4.png)

Are you using spring boot?
