### ISSUE TITLE
找不到这个类了

### ISSUE THREAD

**Issue by zhengshengjie666** [Auties00/WhatsappWeb4j#120]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project whatsappweb4j: Compilation failure: Compilation failure:
[ERROR] /D:/works/whatsapp-workspace/WhatsappWeb4j/src/main/java/it/auties/whatsapp/model/contact/ContactJid.java:[6,34] 找不到符号
[ERROR]   符号:   类 ProtobufValueProvider
[ERROR]   位置: 程序包 it.auties.protobuf.encoder
[ERROR] /D:/works/whatsapp-workspace/WhatsappWeb4j/src/main/java/it/auties/whatsapp/model/contact/ContactJid.java:[28,97] 找不到符号
[ERROR]   符号: 类 ProtobufValueProvider

**Comment by Auties00** [comment]
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project whatsappweb4j: Compilation failure: Compilation failure: [ERROR] /D:/works/whatsapp-workspace/WhatsappWeb4j/src/main/java/it/auties/whatsapp/model/contact/ContactJid.java:[6,34] 找不到符号 [ERROR] 符号: 类 ProtobufValueProvider [ERROR] 位置: 程序包 it.auties.protobuf.encoder [ERROR] /D:/works/whatsapp-workspace/WhatsappWeb4j/src/main/java/it/auties/whatsapp/model/contact/ContactJid.java:[28,97] 找不到符号 [ERROR] 符号: 类 ProtobufValueProvider

Yeah some artifacts are not public yet, that's why it's failing
