### ISSUE TITLE
Docs: add build instructions

### ISSUE THREAD

**Issue by KishanBagaria** [Auties00/WhatsappWeb4j#122]
Been unable to run this.

```
    implementation("com.github.auties00", "whatsappweb4j", "3.0-SNAPSHOT")
```

3.0-SNAPSHOT isn't published. How should we link it to the multidevicebeta branch of whatsappweb4j? Have tried [instructions here](https://stackoverflow.com/questions/18748436/is-it-possible-to-declare-git-repository-as-dependency-in-android-gradle) with no avail.

**Comment by Auties00** [comment]
> Been unable to run this.
> 
> ```
>     implementation("com.github.auties00", "whatsappweb4j", "3.0-SNAPSHOT")
> ```
> 
> 3.0-SNAPSHOT isn't published. How should we link it to the multidevicebeta branch of whatsappweb4j? Have tried [instructions here](https://stackoverflow.com/questions/18748436/is-it-possible-to-declare-git-repository-as-dependency-in-android-gradle) with no avail.

You have to clone the multi device branch and run mvn install
But even that won't work because it depends on some artifacts that are not yet public 
So you'll have to wait sorry
