### ISSUE TITLE
The multidevice support is needed

### ISSUE THREAD

**Issue by OnlyCris** [Auties00/WhatsappWeb4j#124]
Multisupport beta is not more a beta. this feature is now a part of whatsapp and it's impossibile to use the library with this feature. please fix it and make it workable

**Comment by Auties00** [comment]
Sorry to say, but this is pretty obvious. The md branch is technically ready but there is a bug with message sending that makes it not usable today. I've been working on it for the last two months, but I can't seem to find the problem

**Comment by 19Maury85** [comment]
> Sorry to say, but this is pretty obvious. The md branch is technically ready but there is a bug with message sending that makes it not usable today. I've been working on it for the last two months, but I can't seem to find the problem

there is a way to checkout this branch and try to help you?

**Comment by Auties00** [comment]
> > Sorry to say, but this is pretty obvious. The md branch is technically ready but there is a bug with message sending that makes it not usable today. I've been working on it for the last two months, but I can't seem to find the problem
> 
> there is a way to checkout this branch and try to help you?

Yeah: https://github.com/Auties00/WhatsappWeb4j/tree/multidevicebeta

**Comment by pfthink** [comment]
when i run multidevicebeta branch ,some exception eg: java.io.UncheckedIOException: Cannot list known ids ,
how to resolve ,whats means of ids?

**Comment by shmezi** [comment]
Hey, sorry to bother, is there any update on this?

**Comment by Auties00** [comment]
> Hey, sorry to bother, is there any update on this?

I'm working on it, sadly there are still some issues

**Comment by shmezi** [comment]
Got it, any eta do you think?

**Comment by Auties00** [comment]
> Got it, any eta do you think?

I just fixed messages so probably a week

**Comment by OnlyCris** [comment]
Hey @Auties00 how the work is going?

**Comment by Auties00** [comment]
> Hey @Auties00 how the work is going?

Everything's working as of now, expect state writes. In other words you can send messages, receive messages, create groups and everything else but you can't mute, pin or mark chats as read

**Comment by storm1101** [comment]
Hi Auties00, do you check if it works sending messages from bot if you receive the command /hi from WhatsApp web?. Thanks

**Comment by Auties00** [comment]
> Hi Auties00, do you check if it works sending messages from bot if you receive the command /hi from WhatsApp web?. Thanks

Yeah it obviously works, all text messages are supported

**Comment by Auties00** [comment]
> Ah ma sei italiano

Eh sì :)

**Comment by OnlyCris** [comment]
esattamente, cosa manca all'update decisivo nella quale verrà implementato il supporto per il multidevice?

**Comment by OnlyCris** [comment]
#126

**Comment by Auties00** [comment]
> esattamente, cosa manca all'update decisivo nella quale verrà implementato il supporto per il multidevice?

That it's not stable yet
