### ISSUE TITLE
Nothing seems to be working?

### ISSUE THREAD

**Issue by Dustinhoefer** [Auties00/WhatsappWeb4j#127]
Hello everyone,

I am probybly doing something wrong here. I am using the code from the examples (which I added a print for all open chats to), but none are present. 
The console keeps on printing "[47m  [0m[47m  [0m[40m  [0m[47m  [0m[40m  [0m[40m  [0m[40m " in a loop...
Whatsapp Web is opened in Chrome. Am I missing a step?

Kind regards
Dustin

**Comment by storm1101** [comment]
This is the qr code that you have to scan

**Comment by storm1101** [comment]
Change the code if you dont understand the visualization ;)

**Comment by Dustinhoefer** [comment]
Ok, found the string behind the qr code and generated one online. Might fork and add some code for this :D

**Comment by Auties00** [comment]
> Ok, found the string behind the qr code and generated one online. Might fork and add some code for this :D

You are probably using a terminal that doesn't support ASCII codes. Use another terminal or implement the onQr method

**Comment by OnlyCris** [comment]
i'm using intellij (with the 2.2.7 version it works correctly) and i have the same problem

**Comment by OnlyCris** [comment]
![image](https://user-images.githubusercontent.com/71846602/171923168-5315d91c-24f1-4b4a-815b-bbe349d302a4.png)

**Comment by OnlyCris** [comment]
> Ok, found the string behind the qr code and generated one online. Might fork and add some code for this :D

how did you found the string?

**Comment by Auties00** [comment]
> i'm using intellij (with the 2.2.7 version it works correctly) and i have the same problem

Use debug instead of run and it will open the right console. Alternatively run from git bash

**Comment by Auties00** [comment]
Btw commits will now be in the master branch, switch to that branch
