### ISSUE TITLE
Problem using Lombok + Eclipse + whatsappweb4j

### ISSUE THREAD

**Issue by Dustinhoefer** [Auties00/WhatsappWeb4j#128]
Hey,

did anyone face this error before?

![image](https://user-images.githubusercontent.com/9034378/171968360-ea424036-d9f8-458f-95b2-ddd2d0f53116.png)

I am using a fresh copy of the current eclipse version with a lombok added. When importing the project with maven, I am immediately getting the above mentioned error ...

Kind regards
Dustin

**Comment by Auties00** [comment]
> Hey,
> 
> did anyone face this error before?
> 
> ![image](https://user-images.githubusercontent.com/9034378/171968360-ea424036-d9f8-458f-95b2-ddd2d0f53116.png)
> 
> I am using a fresh copy of the current eclipse version with a lombok added. When importing the project with maven, I am immediately getting the above mentioned error ...
> 
> Kind regards Dustin

Are you using Java 17 to compile? Have you tried to clean your build and retry?

**Comment by Dustinhoefer** [comment]
> > Hey,
> > did anyone face this error before?
> > ![image](https://user-images.githubusercontent.com/9034378/171968360-ea424036-d9f8-458f-95b2-ddd2d0f53116.png)
> > I am using a fresh copy of the current eclipse version with a lombok added. When importing the project with maven, I am immediately getting the above mentioned error ...
> > Kind regards Dustin
> 
> Are you using Java 17 to compile? Have you tried to clean your build and retry?

Yes, I am using JDK 17. clean and everything did not work :/

**Comment by Auties00** [comment]
> > > Hey,
> > > did anyone face this error before?
> > > ![image](https://user-images.githubusercontent.com/9034378/171968360-ea424036-d9f8-458f-95b2-ddd2d0f53116.png)
> > > I am using a fresh copy of the current eclipse version with a lombok added. When importing the project with maven, I am immediately getting the above mentioned error ...
> > > Kind regards Dustin
> > 
> > 
> > Are you using Java 17 to compile? Have you tried to clean your build and retry?
> 
> Yes, I am using JDK 17. clean and everything did not work :/

It's kind of strange. No one has had any problems compiling. Can you try to use Javac instead of the eclipse compiler, maybe it's a Lombok bug
