### ISSUE TITLE
Crash when we kill process and start again

### ISSUE THREAD

**Issue by storm1101** [Auties00/WhatsappWeb4j#130]
Main call:

CommandManager.instance().addCommand(new HelloCommand());
Whatsapp.lastConnection().connect().get();

When we kill process and start again the library throw this exception:

jun 07, 2022 11:37:12 A. M. it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure
WARNING: Received status code 400 at MESSAGE(NullPointerException: Missing session for 34666666666:3.0. Known sessions: {}): handling failure
java.lang.NullPointerException: Missing session for 34666666666:3.0. Known sessions: {}
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at it.auties.whatsapp.crypto.SessionCipher.lambda$loadSession$13(SessionCipher.java:239)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at it.auties.whatsapp.crypto.SessionCipher.loadSession(SessionCipher.java:239)
	at it.auties.whatsapp.crypto.SessionCipher.loadSession(SessionCipher.java:234)
	at it.auties.whatsapp.crypto.SessionCipher.lambda$decrypt$8(SessionCipher.java:144)
	at it.auties.whatsapp.util.CipherScheduler.run(CipherScheduler.java:23)
	at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:143)
	at it.auties.whatsapp.binary.BinarySocket$MessageHandler.decodeCipheredMessage(BinarySocket.java:1263)
	at it.auties.whatsapp.binary.BinarySocket$MessageHandler.decodeMessage(BinarySocket.java:1211)
	at it.auties.whatsapp.binary.BinarySocket$MessageHandler.lambda$decode$35(BinarySocket.java:1203)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.binary.BinarySocket$MessageHandler.decode(BinarySocket.java:1203)
	at it.auties.whatsapp.binary.BinarySocket$StreamHandler.digestMessage(BinarySocket.java:539)
	at it.auties.whatsapp.binary.BinarySocket$StreamHandler.digest(BinarySocket.java:526)
	at it.auties.whatsapp.binary.BinarySocket.handleNode(BinarySocket.java:206)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.binary.BinarySocket.onBinary(BinarySocket.java:201)

Thanks for all

**Comment by Auties00** [comment]
> Main call:
> 
> CommandManager.instance().addCommand(new HelloCommand()); Whatsapp.lastConnection().connect().get();
> 
> When we kill process and start again the library throw this exception:
> 
> jun 07, 2022 11:37:12 A. M. it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure WARNING: Received status code 400 at MESSAGE(NullPointerException: Missing session for 34666666666:3.0. Known sessions: {}): handling failure java.lang.NullPointerException: Missing session for 34657769647:3.0. Known sessions: {} at java.base/java.util.Objects.requireNonNull(Objects.java:233) at it.auties.whatsapp.crypto.SessionCipher.lambda$loadSession$13(SessionCipher.java:239) at java.base/java.util.Optional.orElseGet(Optional.java:364) at it.auties.whatsapp.crypto.SessionCipher.loadSession(SessionCipher.java:239) at it.auties.whatsapp.crypto.SessionCipher.loadSession(SessionCipher.java:234) at it.auties.whatsapp.crypto.SessionCipher.lambda$decrypt$8(SessionCipher.java:144) at it.auties.whatsapp.util.CipherScheduler.run(CipherScheduler.java:23) at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:143) at it.auties.whatsapp.binary.BinarySocket$MessageHandler.decodeCipheredMessage(BinarySocket.java:1263) at it.auties.whatsapp.binary.BinarySocket$MessageHandler.decodeMessage(BinarySocket.java:1211) at it.auties.whatsapp.binary.BinarySocket$MessageHandler.lambda$decode$35(BinarySocket.java:1203) at java.base/java.lang.Iterable.forEach(Iterable.java:75) at it.auties.whatsapp.binary.BinarySocket$MessageHandler.decode(BinarySocket.java:1203) at it.auties.whatsapp.binary.BinarySocket$StreamHandler.digestMessage(BinarySocket.java:539) at it.auties.whatsapp.binary.BinarySocket$StreamHandler.digest(BinarySocket.java:526) at it.auties.whatsapp.binary.BinarySocket.handleNode(BinarySocket.java:206) at java.base/java.lang.Iterable.forEach(Iterable.java:75) at it.auties.whatsapp.binary.BinarySocket.onBinary(BinarySocket.java:201)
> 
> Thanks for all

Are you using version 3.0-RC1?

**Comment by storm1101** [comment]
Yes, is the last version of the trunk

**Comment by storm1101** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.github.auties00</groupId>
    <artifactId>whatsappweb4j</artifactId>
    <version>3.0-RC2-SNAPSHOT</version>
    <name>${project.groupId}:${project.artifactId}</name>
    <description>Standalone fully-featured Whatsapp Web API for Java and Kotlin</description>
    <url>https://github.com/Auties00/WhatsappWeb4j</url>
    <developers>
        <developer>
            <name>Alessandro Autiero</name>
            <email>alautiero@gmail.com</email>
        </developer>
    </developers>
    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://www.opensource.org/licenses/mit-license.php</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <scm>
        <url>https://github.com/Auties00/WhatsappWeb4j/tree/master</url>
        <connection>scm:git:https://github.com/Auties00/WhatsappWeb4j.git</connection>
        <tag>whatsappweb4j-2.1.4</tag>
    </scm>
    <distributionManagement>
        <snapshotRepository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
        <repository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
        </repository>
    </distributionManagement>
    <profiles>
        <profile>
            <id>release-sign-artifacts</id>
            <activation>
                <property>
                    <name>performRelease</name>
                    <value>true</value>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>${maven.gpg.plugin.version}</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
    <packaging>jar</packaging>

    <repositories>
        <repository>
            <id>projectlombok.org</id>
            <url>https://projectlombok.org/edge-releases</url>
        </repository>
    </repositories>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>17</java.version>
        <maven.surefire.plugin.version>3.0.0-M5</maven.surefire.plugin.version>
        <maven.gpg.plugin.version>1.6</maven.gpg.plugin.version>
        <maven.compiler.plugin.version>3.8.1</maven.compiler.plugin.version>
        <maven.source.plugin.version>3.0.1</maven.source.plugin.version>
        <maven.javadoc.plugin.version>3.2.0</maven.javadoc.plugin.version>
        <maven.deploy.plugin.version>2.8.2</maven.deploy.plugin.version>
        <nexus.staging.maven.plugin.version>1.6.7</nexus.staging.maven.plugin.version>
        <bouncy.castle.version>1.70</bouncy.castle.version>
        <zxing.version>3.5.0</zxing.version>
        <protoc.version>1.13</protoc.version>
        <tyrus.version>2.0.2</tyrus.version>
        <lombok.version>1.18.24</lombok.version>
        <junit.version>5.8.2</junit.version>
        <jna.version>5.11.0</jna.version>
        <jackson.version>2.13.3</jackson.version>
        <jackson.modules.version>2.13.3</jackson.modules.version>
        <jackson.map.version>1.3</jackson.map.version>
        <curve25519.version>1.1</curve25519.version>
        <bytes.version>1.2</bytes.version>
        <ffmpeg.version>0.7.0</ffmpeg.version>
        <classgraph.version>4.8.146</classgraph.version>
        <reflection.version>1.2</reflection.version>
        <caffeine.version>3.1.0</caffeine.version>
        <lazysodium.version>5.1.1</lazysodium.version>
        <delombok.plugin.version>1.18.24</delombok.plugin.version>
        <delombok.input>${project.basedir}\src\main\java</delombok.input>
        <delombok.output>${project.build.directory}\delombok</delombok.output>
    </properties>

    <build>
        <plugins>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <release>${java.version}</release>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <compilerArg>--enable-preview</compilerArg>
                    </compilerArgs>
                    <failOnError>true</failOnError>
                </configuration>
            </plugin>

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>${maven.javadoc.plugin.version}</version>
                <executions>
                    <execution>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <sourcepath>${delombok.output}</sourcepath>
                    <release>${java.version}</release>
                    <failOnError>true</failOnError>
                    <additionalOptions>--enable-preview</additionalOptions>
                    <debug>true</debug>
                    <verbose>true</verbose>
                </configuration>
            </plugin>

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>org.junit.jupiter</groupId>
                        <artifactId>junit-jupiter-engine</artifactId>
                        <version>${junit.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <argLine>--enable-preview</argLine>
                </configuration>
            </plugin>

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>${maven.source.plugin.version}</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            
            <plugin>
                <groupId>com.github.auties00</groupId>
                <artifactId>delombok-plugin</artifactId>
                <version>${delombok.plugin.version}</version>
                <configuration>
                    <rootDirectory>${project.build.sourceDirectory}</rootDirectory>
                    <outputDirectory>${delombok.output}</outputDirectory>
                    <excludedFiles>
                        <excludedFile>module-info.java</excludedFile>
                    </excludedFiles>
                    <parameters>
                        <encoding>UTF-8</encoding>
                    </parameters>
                </configuration>
                <executions>
                    <execution>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>delombok</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>${maven.javadoc.plugin.version}</version>
                <executions>
                    <execution>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <sourcepath>${delombok.output}</sourcepath>
                    <release>${java.version}</release>
                    <failOnError>true</failOnError>
                    <additionalOptions>--enable-preview</additionalOptions>
                    <debug>true</debug>
                    <verbose>true</verbose>
                </configuration>
            </plugin>

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>${maven.deploy.plugin.version}</version>
                <executions>
                    <execution>
                        <id>default-deploy</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.sonatype.plugins</groupId>
                <artifactId>nexus-staging-maven-plugin</artifactId>
                <version>${nexus.staging.maven.plugin.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <serverId>ossrh</serverId>
                    <nexusUrl>https://s01.oss.sonatype.org/</nexusUrl>
                    <autoReleaseAfterClose>true</autoReleaseAfterClose>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.tyrus</groupId>
            <artifactId>tyrus-server</artifactId>
            <version>${tyrus.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>javase</artifactId>
            <version>${zxing.version}</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15on</artifactId>
            <version>${bouncy.castle.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.auties00</groupId>
            <artifactId>protoc-api</artifactId>
            <version>${protoc.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.auties00</groupId>
            <artifactId>reflection</artifactId>
            <version>${reflection.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${jackson.modules.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
            <version>${jackson.modules.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.auties00</groupId>
            <artifactId>map-module</artifactId>
            <version>${jackson.map.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.auties00</groupId>
            <artifactId>curve25519</artifactId>
            <version>${curve25519.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.classgraph</groupId>
            <artifactId>classgraph</artifactId>
            <version>${classgraph.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
            <version>${caffeine.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.auties00</groupId>
            <artifactId>bytes</artifactId>
            <version>${bytes.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.goterl</groupId>
            <artifactId>lazysodium-java</artifactId>
            <version>${lazysodium.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>${jna.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>

**Comment by storm1101** [comment]
I attach pom file. Rename it from xls to xml.

Yes it happens every time i scan QR code and kill process to start again.

jun 07, 2022 10:21:24 P. M. it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure
WARNING: Received status code 400 at MESSAGE(NullPointerException: Missing session for 34666666666:1.0. Known sessions: {}): handling failure
java.lang.NullPointerException: Missing session for 34666666666:1.0. Known sessions: {}
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at it.auties.whatsapp.crypto.SessionCipher.lambda$loadSession$13(SessionCipher.java:239)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at it.auties.whatsapp.crypto.SessionCipher.loadSession(SessionCipher.java:239)
	at it.auties.whatsapp.crypto.SessionCipher.loadSession(SessionCipher.java:234)
	at it.auties.whatsapp.crypto.SessionCipher.lambda$decrypt$8(SessionCipher.java:144)
	at it.auties.whatsapp.util.CipherScheduler.run(CipherScheduler.java:23)
	at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:143)
	at it.auties.whatsapp.binary.BinarySocket$MessageHandler.decodeCipheredMessage(BinarySocket.java:1263)
	at it.auties.whatsapp.binary.BinarySocket$MessageHandler.decodeMessage(BinarySocket.java:1211)
	at it.auties.whatsapp.binary.BinarySocket$MessageHandler.lambda$decode$35(BinarySocket.java:1203)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.binary.BinarySocket$MessageHandler.decode(BinarySocket.java:1203)
	at it.auties.whatsapp.binary.BinarySocket$StreamHandler.digestMessage(BinarySocket.java:539)
	at it.auties.whatsapp.binary.BinarySocket$StreamHandler.digest(BinarySocket.java:526)
	at it.auties.whatsapp.binary.BinarySocket.handleNode(BinarySocket.java:206)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.binary.BinarySocket.onBinary(BinarySocket.java:201)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652)
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:560)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800)
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
	at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)


 
[pom.xls](https://github.com/Auties00/WhatsappWeb4j/files/8856321/pom.xls)

**Comment by Auties00** [comment]
> I attach pom file. Rename it from xls to xml.
> 
> Yes it happens every time i scan QR code and kill process to start again.
> 
> jun 07, 2022 10:21:24 P. M. it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure WARNING: Received status code 400 at MESSAGE(NullPointerException: Missing session for 34666666666:1.0. Known sessions: {}): handling failure java.lang.NullPointerException: Missing session for 34666666666:1.0. Known sessions: {} at java.base/java.util.Objects.requireNonNull(Objects.java:233) at it.auties.whatsapp.crypto.SessionCipher.lambda$loadSession$13(SessionCipher.java:239) at java.base/java.util.Optional.orElseGet(Optional.java:364) at it.auties.whatsapp.crypto.SessionCipher.loadSession(SessionCipher.java:239) at it.auties.whatsapp.crypto.SessionCipher.loadSession(SessionCipher.java:234) at it.auties.whatsapp.crypto.SessionCipher.lambda$decrypt$8(SessionCipher.java:144) at it.auties.whatsapp.util.CipherScheduler.run(CipherScheduler.java:23) at it.auties.whatsapp.crypto.SessionCipher.decrypt(SessionCipher.java:143) at it.auties.whatsapp.binary.BinarySocket$MessageHandler.decodeCipheredMessage(BinarySocket.java:1263) at it.auties.whatsapp.binary.BinarySocket$MessageHandler.decodeMessage(BinarySocket.java:1211) at it.auties.whatsapp.binary.BinarySocket$MessageHandler.lambda$decode$35(BinarySocket.java:1203) at java.base/java.lang.Iterable.forEach(Iterable.java:75) at it.auties.whatsapp.binary.BinarySocket$MessageHandler.decode(BinarySocket.java:1203) at it.auties.whatsapp.binary.BinarySocket$StreamHandler.digestMessage(BinarySocket.java:539) at it.auties.whatsapp.binary.BinarySocket$StreamHandler.digest(BinarySocket.java:526) at it.auties.whatsapp.binary.BinarySocket.handleNode(BinarySocket.java:206) at java.base/java.lang.Iterable.forEach(Iterable.java:75) at it.auties.whatsapp.binary.BinarySocket.onBinary(BinarySocket.java:201) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553) at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652) at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:560) at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800) at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183) at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70) at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819) at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725) at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452) at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91) at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68) at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248) at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88) at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246) at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178) at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118) at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96) at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51) at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510) at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82) at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83) at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34) at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101) at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) at java.base/java.lang.Thread.run(Thread.java:833)
> 
> [pom.xls](https://github.com/Auties00/WhatsappWeb4j/files/8856321/pom.xls)

You are using the wrong version, use 3.0-RC1 instead of 3.0-RC2-SNAPSHOT. also are you killing the process using intellij or manually?

**Comment by storm1101** [comment]
I am killing the process with eclipse ide. I think that is a kill

**Comment by storm1101** [comment]
Good morning Auties00, 
With 3.0-RC1 revision we have the same error code. Error code 400 at MESSAGE...... when we stop and restart the process daemon.

Thanks

**Comment by Auties00** [comment]
> I am killing the process with eclipse ide. I think that is a kill

Can you check if the data is serialized correctly when the process is killed?

**Comment by storm1101** [comment]
> Can you check if the data is serialized correctly when the process is killed?


I have modify the data for security:

**store.json:**
{"id":4467}

**keys.json:**
{"id":4467,"noiseKeyPair":{"publicKey":"V3urmbrvlnmY3G4jdgFM+wL8873fHED7RcSSf4JcuHI=","privateKey":"qOVoO+42x7gig9uABUaQbfN23ZG8HaPAH/U4W5GrHGc="},"ephemeralKeyPair":{"publicKey":"ZTV8YIHYCcNhW4BPbvxvkKiWkZ1Rfnr0Koeu2394ZxI=","privateKey":"+HquiiQAQrBAmqclmzS9YWcnlr24OGx5w2dyY6yofXE="},"identityKeyPair":{"publicKey":"GWpV4ayJfvSPspGaYxH/VaW1XqbvIiVKDQMzwSDlsUg=","privateKey":"YIQVA9hBVp4dMbnnZ3IQPhfR0KeWNLONUKsCoBwlZGM="},"signedKeyPair":{"id":4467,"keyPair":{"publicKey":"hdxdyUp9Vl89bbbf9Kufdgq7EdsKb9EGuCJddVHQHgc=","privateKey":"gKdLsw3Z0Km/BXSMAokoSR3w/dIhsyX/CovQo4tCzXI="},"signature":"KTivu3xrA8dYBUeLBsIC4jbygqrJvTpAvt7iHCmlOV57vul87vNLnIHHwD4eEG07kQ/D50dBkdxLXx4jfcH5BA=="},"companion":"34666666666:12@s.whatsapp.net","companionKey":"9/8zbineqqffffmWsZtN3YtyLfG4klgSdBjm3PiVQ2Q=","companionIdentity":{"details":"CMCfffcFEjmugZUGGAw=","accountSignatureKey":"K7fffSIb40DdstoN9V/gNKAhFLBNLT7fOR9B3/h3rwc=","accountSignature":"cfffpOAPbz+goCwvwwO3XvysUseOIhGCfff/doO7LlN2lHv2WO1NExD8oVJU+gDLLSRV5AjLGzebYScC9iKVAQ==","deviceSignature":"tKlSBfffQgKNc5teBHP3IxGTyeOKHU6+b0nFkaUGSPowbGS0jvH322OzJ6/T7xpsmfK4fffigSKCopNoTC5ptBg=="},"senderKeys":[],"receiverKeys":[],"sessions":[],"hashStates":[]}

**Comment by Auties00** [comment]
> sessions

It looks like a serialization issue. So what you need to do is print Whatsapp#keys in the onDisconnect listener and check if the serialized data matches the keys.json.

**Comment by storm1101** [comment]
> check

Ok, i'll do that. Did you reproduce the bug in your PC?

**Comment by Auties00** [comment]
https://github.com/Auties00/WhatsappWeb4j/issues/133 tracking here
