### ISSUE TITLE
1 is not a valid ephemeral time

### ISSUE THREAD

**Issue by JoseHM8A** [Auties00/WhatsappWeb4j#131]
![image](https://user-images.githubusercontent.com/70950705/172502673-ab3fdaf1-a482-4673-96c6-6498d4143345.png)
 
When i try to start my app, this error appears

**Comment by Auties00** [comment]
> ![image](https://user-images.githubusercontent.com/70950705/172502673-ab3fdaf1-a482-4673-96c6-6498d4143345.png)
> 
> When i try to start my app, this error appears

Can you send your full code?

**Comment by JoseHM8A** [comment]
> > ![image](https://user-images.githubusercontent.com/70950705/172502673-ab3fdaf1-a482-4673-96c6-6498d4143345.png)
> > When i try to start my app, this error appears
> 
> Can you send your full code?

package com.DarkerBot;

import it.auties.whatsapp.api.HistoryLength;
import it.auties.whatsapp.api.SerializationStrategy;
import it.auties.whatsapp.api.Whatsapp;
import it.auties.whatsapp.api.WhatsappOptions;
import it.auties.whatsapp.model.signal.auth.Version;

import java.util.concurrent.ExecutionException;

public class WhatsappBot {
    public static void main(String... args) throws ExecutionException, InterruptedException {
        // Implement only the options that you need!
        var configuration = WhatsappOptions.newOptions()
                .id(66666) // A random unique ID associated with the session
                .version(new Version(2, 2212, 7)) // The version of this client, make sure it's not too outdated
                .url("wss://web.whatsapp.com/ws") // The URL of WhatsappWeb's Socket
                .serialization(false)
                .historyLength(HistoryLength.THREE_MONTHS) // The amount of chat history that Whatsapp sends to the client on the first scan
                .create(); // Creates an instance of WhatsappOptions
        var api = Whatsapp.newConnection(configuration);
        api.lastConnection().connect().get();
    }
}

**Comment by JoseHM8A** [comment]
Can you help me?

**Comment by Auties00** [comment]
> Can you help me?

Working on a fix xP

**Comment by JoseHM8A** [comment]
> > Can you help me?
> 
> Working on a fix xP

Ok, and if u can verify the reason that sendMessage dont work on groups, i'll apreciate.
The bot is sending as if the chat were a user, ("@s.whatsapp.net")

**Comment by Auties00** [comment]
> > > Can you help me?
> > 
> > 
> > Working on a fix xP
> 
> Ok, and if u can verify the reason that sendMessage dont work on groups, i'll apreciate. The bot is sending as if the chat were a user, ("@s.whatsapp.net")

Yeah already fixed, I'm waiting to push
