### ISSUE TITLE
Cannot quote message correctly 

### ISSUE THREAD

**Issue by shmezi** [Auties00/WhatsappWeb4j#132]
Sorry Im sure this is super simple, I just cannot seem to find any method to reply to a message (as in quote another message)
I've tried many methods and checked the javaDocs a bunch.

**Comment by shmezi** [comment]
Ye, I got that.. just didnt really understand where to get the MessageInfo, I've looked inside the message context etc.
Im trying to just reply to a message when a user sends it.

(Side note, may be nice to have a small disc server for people to help each other)

**Comment by Auties00** [comment]
> Ye, I got that.. just didnt really understand where to get the MessageInfo, I've looked inside the message context etc. Im trying to just reply to a message when a user sends it.
> 
> (Side note, may be nice to have a small disc server for people to help each other)

You need to implement the onNewMessage(MessageInfo) method inside a WhatsappListener

**Comment by shmezi** [comment]
![image](https://user-images.githubusercontent.com/67468040/172848934-162d6b81-cc38-4621-953d-74cccee7f56e.png)
 Already did.. I just cant for the life of me find what the reference is for the last argument in it (The context or something.)

**Comment by shmezi** [comment]
![image](https://user-images.githubusercontent.com/67468040/172860872-a5ee63d4-ecd4-4855-977b-3073768792b4.png)
Here I even tried 1 to 1 what one of the examples what it was showing however, yet still no luck..
![image](https://user-images.githubusercontent.com/67468040/172861193-a0353152-1034-42f2-94da-cceb3cfb6567.png)
It just sends the message not quoting the one I reference.

**Comment by Auties00** [comment]
> ![image](https://user-images.githubusercontent.com/67468040/172860872-a5ee63d4-ecd4-4855-977b-3073768792b4.png) Here I even tried 1 to 1 what one of the examples what it was showing however, yet still no luck.. ![image](https://user-images.githubusercontent.com/67468040/172861193-a0353152-1034-42f2-94da-cceb3cfb6567.png) It just sends the message not quoting the one I reference.

This is the right peace of code, but it's not working. It's a bug definitely

**Comment by Auties00** [comment]
> I have some more bugs Ive encountered would you like an issue for each one or all in one

You can tell me right here

**Comment by shmezi** [comment]
![Screenshot_20220609-234619_WhatsAppBusiness.jpg](https://user-images.githubusercontent.com/67468040/172941643-dec30190-7f88-46a5-a551-751a0a591fe1.jpg)

Kinda odd thing happened, no clue who this is, did I leak something in my stack trace in the other issue I posted?

**Comment by Auties00** [comment]
> Reference in n

You leaked your number here: https://github.com/Auties00/WhatsappWeb4j/issues/133
No magic sadly :/

**Comment by shmezi** [comment]
Might be a good idea not to include that type of info in an error. also errors gotta be fixed, at some point in the future Ill make a quality of life pr touching up methods making it just nicer to work with

**Comment by Auties00** [comment]
> Might be a good idea not to include that type of info in an error. also errors gotta be fixed, at some point in the future Ill make a quality of life pr touching up methods making it just nicer to work with

Thanks :) 
Yeah it's probably not a good idea to have sensitive info there, but then you wouldn't be able to print the sessions which is also kind of bad for error tracking.

**Comment by shmezi** [comment]
> > Might be a good idea not to include that type of info in an error. also errors gotta be fixed, at some point in the future Ill make a quality of life pr touching up methods making it just nicer to work with
> 
> Thanks :) 
> Yeah it's probably not a good idea to have sensitive info there, but then you wouldn't be able to print the sessions which is also kind of bad for error tracking. 

Instead of using a phone number as the session id I would use something like a random string or have the user define it, then in a config have a mapping if that's what you need internally

**Comment by Auties00** [comment]
> > > Might be a good idea not to include that type of info in an error. also errors gotta be fixed, at some point in the future Ill make a quality of life pr touching up methods making it just nicer to work with
> > 
> > 
> > Thanks :)
> > Yeah it's probably not a good idea to have sensitive info there, but then you wouldn't be able to print the sessions which is also kind of bad for error tracking.
> 
> Instead of using a phone number as the session id I would use something like a random string or have the user define it, then in a config have a mapping if that's what you need internally

Yeah the phone number is used in the session address and it's needed for session decryption. Perhaps I could exclude that field from the toString method simply

**Comment by shmezi** [comment]
Was this fixed in the new update?

**Comment by Auties00** [comment]
@shmezi fixed in 3.0-RC11

**Comment by shmezi** [comment]
Issue seems to be resolved from my minimal testing :)
