### ISSUE TITLE
Problem using WA-Business

### ISSUE THREAD

**Issue by OnlyCris** [Auties00/WhatsappWeb4j#134]
Jun 09, 2022 4:13:39 PM it.auties.whatsapp.binary.BinarySocket$AppStateHandler processSyncActions
INFO: Unsupported sync: LabelEditAction(name=Pagato, color=3, predefinedId=4, deleted=false)
Jun 09, 2022 4:13:39 PM it.auties.whatsapp.binary.BinarySocket$AppStateHandler processSyncActions
INFO: Unsupported sync: LabelEditAction(name=Ordine completato, color=5, predefinedId=5, deleted=false)
Jun 09, 2022 4:13:39 PM it.auties.whatsapp.binary.BinarySocket$AppStateHandler processSyncActions
INFO: Unsupported sync: LabelEditAction(name=Nuovo cliente, color=1, predefinedId=1, deleted=false)
Jun 09, 2022 4:13:39 PM it.auties.whatsapp.binary.BinarySocket$AppStateHandler processSyncActions
INFO: Unsupported sync: LabelEditAction(name=Nuovo ordine, color=2, predefinedId=2, deleted=false)
Jun 09, 2022 4:13:39 PM it.auties.whatsapp.binary.BinarySocket$AppStateHandler processSyncActions
INFO: Unsupported sync: QuickReplyAction(shortcut=grazie, message=‎Grazie per il tuo ordine. Torna presto a trovarci!, keywords=null, count=0, deleted=false)
Jun 09, 2022 4:13:39 PM it.auties.whatsapp.binary.BinarySocket$AppStateHandler processSyncActions
INFO: Unsupported sync: LabelEditAction(name=In attesa di pagamento, color=0, predefinedId=3, deleted=false)

**Comment by Auties00** [comment]
> Jun 09, 2022 4:13:39 PM it.auties.whatsapp.binary.BinarySocket$AppStateHandler processSyncActions INFO: Unsupported sync: LabelEditAction(name=Pagato, color=3, predefinedId=4, deleted=false) Jun 09, 2022 4:13:39 PM it.auties.whatsapp.binary.BinarySocket$AppStateHandler processSyncActions INFO: Unsupported sync: LabelEditAction(name=Ordine completato, color=5, predefinedId=5, deleted=false) Jun 09, 2022 4:13:39 PM it.auties.whatsapp.binary.BinarySocket$AppStateHandler processSyncActions INFO: Unsupported sync: LabelEditAction(name=Nuovo cliente, color=1, predefinedId=1, deleted=false) Jun 09, 2022 4:13:39 PM it.auties.whatsapp.binary.BinarySocket$AppStateHandler processSyncActions INFO: Unsupported sync: LabelEditAction(name=Nuovo ordine, color=2, predefinedId=2, deleted=false) Jun 09, 2022 4:13:39 PM it.auties.whatsapp.binary.BinarySocket$AppStateHandler processSyncActions INFO: Unsupported sync: QuickReplyAction(shortcut=grazie, message=‎Grazie per il tuo ordine. Torna presto a trovarci!, keywords=null, count=0, deleted=false) Jun 09, 2022 4:13:39 PM it.auties.whatsapp.binary.BinarySocket$AppStateHandler processSyncActions INFO: Unsupported sync: LabelEditAction(name=In attesa di pagamento, color=0, predefinedId=3, deleted=false)

Yeah those aren't bugs, it's simply a warning to tell you that the API doesn't know what to do with them. You can still listen for those actions using onAction
