### ISSUE TITLE
Problem with german umlauts (ä,ü,ö) and potentially more special characters

### ISSUE THREAD

**Issue by ZiemlichUndead** [Auties00/WhatsappWeb4j#138]
Hi,

I noticed that sending a message with W4J (RC2) containing any umlauts (ä,ü,ö) or "ß" will result in the message just not being sent.
There is no error produced in console, nothing else happens other that the message will not be sent out if it contains one of these characters (only tested the mentioned ones).

Receiving messages with those characters does not seem to be a problem. The messages get passed to a WhatsappListener correctly formatted without issues.

**Comment by Auties00** [comment]
> Hi,
> 
> I noticed that sending a message with W4J (RC2) containing any umlauts (ä,ü,ö) or "ß" will result in the message just not being sent. There is no error produced in console, nothing else happens other that the message will not be sent out if it contains one of these characters (only tested the mentioned ones).
> 
> Receiving messages with those characters does not seem to be a problem. The messages get passed to a WhatsappListener correctly formatted without issues.

Can you check if some function errors out using the debugger? Btw i can also look at this. Someone mentioned a while ago a similar issue for Hebrew

**Comment by Auties00** [comment]
Can confirm that this is a bug

**Comment by Auties00** [comment]
Fixed in 3.0-RC11
