### ISSUE TITLE
Socket failure at APP_STATE_SYNC (RC6)

### ISSUE THREAD

**Issue by JoseHM8A** [Auties00/WhatsappWeb4j#139]
```
Jun 19, 2022 12:57:23 PM it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure
WARNING: Socket failure at APP_STATE_SYNC(java.lang.RuntimeException: Cannot parse patch)
Jun 19
, 2022 12:57:24 PM it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure
WARNING: Saved stacktrace at: C:\Users\Darker\.whatsappweb4j\exceptions\1655643444063.txt
Jun 19, 2022 12:57:24 PM it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure
WARNING: Restoring session
```
[1655643444063.txt](https://github.com/Auties00/WhatsappWeb4j/files/8935542/1655643444063.txt)

On first run (RC6) , the bot started normally, but sending all the messages in: "waiting for message, this can take a while"

When i tried to run again (re-scanning the code), this error throws

**Comment by Auties00** [comment]
> ```
> Jun 19, 2022 12:57:23 PM it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure
> WARNING: Socket failure at APP_STATE_SYNC(java.lang.RuntimeException: Cannot parse patch)
> Jun 19
> , 2022 12:57:24 PM it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure
> WARNING: Saved stacktrace at: C:\Users\Darker\.whatsappweb4j\exceptions\1655643444063.txt
> Jun 19, 2022 12:57:24 PM it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure
> WARNING: Restoring session
> ```
> 
> [1655643444063.txt](https://github.com/Auties00/WhatsappWeb4j/files/8935542/1655643444063.txt)
> 
> On first run (RC6) , the bot started normally, but sending all the messages in: "waiting for message, this can take a while"
> 
> When i tried to run again (re-scanning the code), this error throws

As far as I can tell everything should be working now
