### ISSUE TITLE
Socket failure at ERRANEOUS_NODE (RC12)

### ISSUE THREAD

**Issue by JoseHM8A** [Auties00/WhatsappWeb4j#148]
```
Jun 28, 2022 11:13:30 AM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$0
WARNING: Socket failure at ERRONEOUS_NODE
Jun 28, 2022 11:13:30 AM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$0
WARNING: Saved stacktrace at: C:\Users\Darker\.whatsappweb4j\exceptions\1656414810575.txt
Jun 28, 2022 11:13:30 AM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$0
WARNING: Ignoring failure
```

The SOCKET FAILURE error, closing the session is solved, and quoted messages are now working!!

This issue is not an SUPER ERROR or any like this, but just to let you know. When I start my bot at the first time, and it's syncing messages **(I think)**, when I send a command **(like "/hello")**, sendMessage() works fine, but when I send again, the bot takes a long time to receive other messages (after the first sendMessage)

Now it's working so-so (sometimes stops to receive again), but just so you know this happens

[1656414810575.txt](https://github.com/Auties00/WhatsappWeb4j/files/9000499/1656414810575.txt)
[1656414796820.txt](https://github.com/Auties00/WhatsappWeb4j/files/9000500/1656414796820.txt)
[1656414790570.txt](https://github.com/Auties00/WhatsappWeb4j/files/9000501/1656414790570.txt)
[1656414856856.txt](https://github.com/Auties00/WhatsappWeb4j/files/9000502/1656414856856.txt)
[1656414850574.txt](https://github.com/Auties00/WhatsappWeb4j/files/9000503/1656414850574.txt)
[1656414830573.txt](https://github.com/Auties00/WhatsappWeb4j/files/9000504/1656414830573.txt)

- The first "/ping" sends normally, when i type "/ping" again (ping or other commands), the bot takes a long time to receive the message and reply again

_Originally posted by @JoseHM8A in https://github.com/Auties00/WhatsappWeb4j/issues/143#issuecomment-1168581688_

**Comment by Auties00** [comment]
> ```
> Jun 28, 2022 11:13:30 AM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$0
> WARNING: Socket failure at ERRONEOUS_NODE
> Jun 28, 2022 11:13:30 AM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$0
> WARNING: Saved stacktrace at: C:\Users\Darker\.whatsappweb4j\exceptions\1656414810575.txt
> Jun 28, 2022 11:13:30 AM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$0
> WARNING: Ignoring failure
> ```
> 
> The SOCKET FAILURE error, closing the session is solved, and quoted messages are now working!!
> 
> This issue is not an SUPER ERROR or any like this, but just to let you know. When I start my bot at the first time, and it's syncing messages **(I think)**, when I send a command **(like "/hello")**, sendMessage() works fine, but when I send again, the bot takes a long time to receive other messages (after the first sendMessage)
> 
> Now it's working so-so (sometimes stops to receive again), but just so you know this happens
> 
> [1656414810575.txt](https://github.com/Auties00/WhatsappWeb4j/files/9000499/1656414810575.txt) [1656414796820.txt](https://github.com/Auties00/WhatsappWeb4j/files/9000500/1656414796820.txt) [1656414790570.txt](https://github.com/Auties00/WhatsappWeb4j/files/9000501/1656414790570.txt) [1656414856856.txt](https://github.com/Auties00/WhatsappWeb4j/files/9000502/1656414856856.txt) [1656414850574.txt](https://github.com/Auties00/WhatsappWeb4j/files/9000503/1656414850574.txt) [1656414830573.txt](https://github.com/Auties00/WhatsappWeb4j/files/9000504/1656414830573.txt)
> 
> * The first "/ping" sends normally, when i type "/ping" again (ping or other commands), the bot takes a long time to receive the message and reply again
> 
> _Originally posted by @JoseHM8A in [#143 (comment)](https://github.com/Auties00/WhatsappWeb4j/issues/143#issuecomment-1168581688)_

Yeah this is not this library's fault. You can test it yourself by sending and receiving messages using the app. If your number is fresh and you start to use WhatsApp web immediately whatsapp will limit your number for like a day. It could happen a couple of times, but it will fix itself. It's not really anything I can fix. For the errors I'm working on a new version that should fix all of them

**Comment by Auties00** [comment]
if you need further help reopen the issue
