### ISSUE TITLE
Stops working

### ISSUE THREAD

**Issue by glassbilen** [Auties00/WhatsappWeb4j#149]
I keep having this problem where when I load a old session it doesn't work, and when reauthenticating, it for a short duration.

Stacktrace:
WARNING: Restoring session
jun 27, 2022 12:08:27 P.áM. it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure
WARNING: Socket failure at UNKNOWN(mac check in GCM failed)
jun 27, 2022 12:08:27 P.áM. it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure
WARNING: Saved stacktrace at: C:\Users\lukas.whatsappweb4j\exceptions\1656324507034.txt
jun 27, 2022 12:08:27 P.áM. it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure
WARNING: Restoring session

In fike:
org.bouncycastle.crypto.InvalidCipherTextException: mac check in GCM failed
	at org.bouncycastle.crypto.modes.GCMBlockCipher.doFinal(Unknown Source)
	at it.auties.whatsapp.crypto.AesGmc.encrypt(AesGmc.java:37)
	at it.auties.whatsapp.binary.BinaryMessage.toNode(BinaryMessage.java:54)
	at it.auties.whatsapp.binary.BinaryMessage.lambda$toNodes$0(BinaryMessage.java:48)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at it.auties.whatsapp.binary.BinaryMessage.toNodes(BinaryMessage.java:49)
	at it.auties.whatsapp.binary.BinarySocket.onBinary(BinarySocket.java:200)
	at jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652)
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:560)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800)
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
	at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by glassbilen** [comment]
> > I keep having this problem where when I load a old session it doesn't work, and when reauthenticating, it for a short duration.
> > Stacktrace: WARNING: Restoring session jun 27, 2022 12:08:27 P.áM. it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure WARNING: Socket failure at UNKNOWN(mac check in GCM failed) jun 27, 2022 12:08:27 P.áM. it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure WARNING: Saved stacktrace at: C:\Users\lukas.whatsappweb4j\exceptions\1656324507034.txt jun 27, 2022 12:08:27 P.áM. it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure WARNING: Restoring session
> > In fike: org.bouncycastle.crypto.InvalidCipherTextException: mac check in GCM failed at org.bouncycastle.crypto.modes.GCMBlockCipher.doFinal(Unknown Source) at it.auties.whatsapp.crypto.AesGmc.encrypt(AesGmc.java:37) at it.auties.whatsapp.binary.BinaryMessage.toNode(BinaryMessage.java:54) at it.auties.whatsapp.binary.BinaryMessage.lambda$toNodes$0(BinaryMessage.java:48) at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) at it.auties.whatsapp.binary.BinaryMessage.toNodes(BinaryMessage.java:49) at it.auties.whatsapp.binary.BinarySocket.onBinary(BinarySocket.java:200) at jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553) at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652) at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:560) at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800) at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183) at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70) at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819) at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725) at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452) at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91) at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68) at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248) at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88) at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246) at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178) at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118) at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96) at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51) at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510) at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82) at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83) at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34) at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101) at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) at java.base/java.lang.Thread.run(Thread.java:833)
> 
> Have you deleted all the old sessions after upgrading version?

Yes

**Comment by Auties00** [comment]
> > > I keep having this problem where when I load a old session it doesn't work, and when reauthenticating, it for a short duration.
> > > Stacktrace: WARNING: Restoring session jun 27, 2022 12:08:27 P.áM. it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure WARNING: Socket failure at UNKNOWN(mac check in GCM failed) jun 27, 2022 12:08:27 P.áM. it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure WARNING: Saved stacktrace at: C:\Users\lukas.whatsappweb4j\exceptions\1656324507034.txt jun 27, 2022 12:08:27 P.áM. it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure WARNING: Restoring session
> > > In fike: org.bouncycastle.crypto.InvalidCipherTextException: mac check in GCM failed at org.bouncycastle.crypto.modes.GCMBlockCipher.doFinal(Unknown Source) at it.auties.whatsapp.crypto.AesGmc.encrypt(AesGmc.java:37) at it.auties.whatsapp.binary.BinaryMessage.toNode(BinaryMessage.java:54) at it.auties.whatsapp.binary.BinaryMessage.lambda$toNodes$0(BinaryMessage.java:48) at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) at it.auties.whatsapp.binary.BinaryMessage.toNodes(BinaryMessage.java:49) at it.auties.whatsapp.binary.BinarySocket.onBinary(BinarySocket.java:200) at jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553) at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652) at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:560) at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800) at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183) at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70) at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819) at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725) at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452) at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91) at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68) at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248) at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88) at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246) at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178) at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118) at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96) at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51) at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510) at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82) at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83) at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34) at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101) at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) at java.base/java.lang.Thread.run(Thread.java:833)
> > 
> > 
> > Have you deleted all the old sessions after upgrading version?
> 
> Yes

What version are you using?

**Comment by glassbilen** [comment]
> > > > I keep having this problem where when I load a old session it doesn't work, and when reauthenticating, it for a short duration.
> > > > Stacktrace: WARNING: Restoring session jun 27, 2022 12:08:27 P.áM. it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure WARNING: Socket failure at UNKNOWN(mac check in GCM failed) jun 27, 2022 12:08:27 P.áM. it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure WARNING: Saved stacktrace at: C:\Users\lukas.whatsappweb4j\exceptions\1656324507034.txt jun 27, 2022 12:08:27 P.áM. it.auties.whatsapp.binary.BinarySocket$ErrorHandler handleFailure WARNING: Restoring session
> > > > In fike: org.bouncycastle.crypto.InvalidCipherTextException: mac check in GCM failed at org.bouncycastle.crypto.modes.GCMBlockCipher.doFinal(Unknown Source) at it.auties.whatsapp.crypto.AesGmc.encrypt(AesGmc.java:37) at it.auties.whatsapp.binary.BinaryMessage.toNode(BinaryMessage.java:54) at it.auties.whatsapp.binary.BinaryMessage.lambda$toNodes$0(BinaryMessage.java:48) at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) at it.auties.whatsapp.binary.BinaryMessage.toNodes(BinaryMessage.java:49) at it.auties.whatsapp.binary.BinarySocket.onBinary(BinarySocket.java:200) at jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553) at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652) at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:560) at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:800) at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183) at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70) at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819) at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:725) at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452) at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91) at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68) at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248) at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88) at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246) at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178) at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118) at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96) at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51) at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510) at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82) at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83) at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34) at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101) at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) at java.base/java.lang.Thread.run(Thread.java:833)
> > > 
> > > 
> > > Have you deleted all the old sessions after upgrading version?
> > 
> > 
> > Yes
> 
> What version are you using?

RC6
