### ISSUE TITLE
The proxy cannot be used

### ISSUE THREAD

**Issue by hwck** [Auties00/WhatsappWeb4j#15]
hi! this is a good project ,because jakarta websocket not support proxy, can we use tyrus ClientManager ?
thx

**Comment by GedMarc** [comment]
Sigh, it isn't modular 

So I asked to go back to raw so we can build distributions, adding it in denies any hope of deploying anything you build.... unless you break the golden rule of never run a JDK in production... 




What do you mean doesn't support proxies,

**Comment by Auties00** [comment]
> hi! this is a good project ,because jakarta websocket not support proxy, can we use tyrus ClientManager ?
> thx

Hello, can you please be more specific about which functionality you need?

**Comment by hwck** [comment]
> > hi! this is a good project ,because jakarta websocket not support proxy, can we use tyrus ClientManager ?
> > thx
> 
> Hello, can you please be more specific about which functionality you need?

because don't use proxy, i can't use whatsapp.

[](https://blogs.oracle.com/pavelbucek/websocket-via-http-proxy)

**Comment by Auties00** [comment]
> > > hi! this is a good project ,because jakarta websocket not support proxy, can we use tyrus ClientManager ?
> > > thx
> > 
> > 
> > Hello, can you please be more specific about which functionality you need?
> 
> because don't use proxy, i can't use whatsapp.

Oh, so whatsapp is blocked in your country and you need to use a proxy to connect to it?

**Comment by hwck** [comment]
> > > > hi! this is a good project ,because jakarta websocket not support proxy, can we use tyrus ClientManager ?
> > > > thx
> > > 
> > > 
> > > Hello, can you please be more specific about which functionality you need?
> > 
> > 
> > because don't use proxy, i can't use whatsapp.
> 
> Oh, so whatsapp is blocked in your country and you need to use a proxy to connect to it?

yes, i must use a  proxy to connect  it

**Comment by hwck** [comment]
I want to know when to support Java 11，i see you say   that it might not be important to support Java 11 as of now

**Comment by Auties00** [comment]
> I want to know when to support Java 11，i see you say that it might not be important to support Java 11 as of now

Yeah, I've chosen to wait for Java 17 as it will be a LTS. For now, only Java 16 is supported

**Comment by hwck** [comment]
> > I want to know when to support Java 11，i see you say that it might not be important to support Java 11 as of now
> 
> Yeah, I've chosen to wait for Java 17 as it will be a LTS. For now, only Java 16 is supported

ok , i see. thanks

**Comment by GedMarc** [comment]
@hwck I think I ran into your issue - 

Pre-connecting the container to the websocket works to override proxies/configs without any dependency or implementation specific configs - 
Configure the client with the appropriate proxy settings as per, you can use an empty listener as the client connection overrides that during initialization 
https://docs.oracle.com/en/java/javase/15/docs/api/java.net.http/java/net/http/HttpClient.html#newWebSocketBuilder()

```
HttpClient client = HttpClient.newHttpClient();
		CompletableFuture<WebSocket> ws = client.newWebSocketBuilder()
		                                        .header("Origin","https://web.whatsapp.com")
		                                        //.header("Host","web.whatsapp.com")
		                                        .buildAsync(URI.create("wss://web.whatsapp.com/ws"), new WebSocket.Listener()
		                                        {
			                                        @Override
			                                        public void onOpen(WebSocket webSocket)
			                                        {
				                                        WebSocket.Listener.super.onOpen(webSocket);
			                                        }
			
			                                        @Override
			                                        public CompletionStage<?> onText(WebSocket webSocket, CharSequence data, boolean last)
			                                        {
				                                        return WebSocket.Listener.super.onText(webSocket, data, last);
			                                        }
			
			                                        @Override
			                                        public CompletionStage<?> onBinary(WebSocket webSocket, ByteBuffer data, boolean last)
			                                        {
				                                        return WebSocket.Listener.super.onBinary(webSocket, data, last);
			                                        }
			
			                                        @Override
			                                        public CompletionStage<?> onPing(WebSocket webSocket, ByteBuffer message)
			                                        {
				                                        return WebSocket.Listener.super.onPing(webSocket, message);
			                                        }
			
			                                        @Override
			                                        public CompletionStage<?> onPong(WebSocket webSocket, ByteBuffer message)
			                                        {
				                                        return WebSocket.Listener.super.onPong(webSocket, message);
			                                        }
			
			                                        @Override
			                                        public CompletionStage<?> onClose(WebSocket webSocket, int statusCode, String reason)
			                                        {
				                                        return WebSocket.Listener.super.onClose(webSocket, statusCode, reason);
			                                        }
			
			                                        @Override
			                                        public void onError(WebSocket webSocket, Throwable error)
			                                        {
				                                        WebSocket.Listener.super.onError(webSocket, error);
			                                        }
		                                        });
		
		WebSocket webSocket1 = ws.get();
```

**Comment by GedMarc** [comment]
@Auties00 This method actually removes the need for JSR entirely, and makes the web socket control java native lol

Is it worth a PR? I'm doing a bit deeper testing but it looks very promising
