### ISSUE TITLE
QR-Code image

### ISSUE THREAD

**Issue by edofredo** [Auties00/WhatsappWeb4j#155]
Hi,

I would like to show the QR-Code in a JLabel in my app. 
Using toFile() I get the image at temporary directory and it opens automatically. Is  there a way to control the path of the QR-Code Image that is created when connect() is executed? Also I don´t want it to open automatically.
Thank you.

**Comment by Auties00** [comment]
> Hi,
> 
> I would like to show the QR-Code in a JLabel in my app. Using toFile() I get the image at temporary directory and it opens automatically. Is there a way to control the path of the QR-Code Image that is created when connect() is executed? Also I don´t want it to open automatically. Thank you.

Check version RC15, you can now handle the file however you like

**Comment by JoseHM8A** [comment]
RC15 isnt avaliable on maven

**Comment by Auties00** [comment]
> RC15 isnt avaliable on maven
> 
> ![image](https://user-images.githubusercontent.com/70950705/179626022-591b2085-40e4-4c6a-bb84-298005eb6740.png)

Should already be available:
https://search.maven.org/artifact/com.github.auties00/whatsappweb4j/3.0-RC15/jar

**Comment by Auties00** [comment]
You can also checkout the GitHub packages section

**Comment by edofredo** [comment]
@Auties00 thank you for this upgrade. Got RC15 from Packages

**Comment by edofredo** [comment]
Hi @Auties00 , I reopen because I tried out RC15 and I cannot log into Whatsapp with the QR-Code_Image. RC14 works fine.
The code I use in RC15 is:
Path path = Paths.get("C:\\Users\\Edofredo\\Documents\\NetBeansProjects\\WhatsappServidor\\qrCode.jpg");
var configuration = Whatsapp.Options.newOptions().qrHandler(QrHandler.toFile(path, QrHandler.ToFileConsumer.toTerminal())).build();
        conexion = Whatsapp.newConnection(configuration);
conexion.connect().join();

Thanks

**Comment by Auties00** [comment]
> Hi @Auties00 , I reopen because I tried out RC15 and I cannot log into Whatsapp with the QR-Code_Image. RC14 works fine. The code I use in RC15 is: Path path = Paths.get("C:\Users\Edofredo\Documents\NetBeansProjects\WhatsappServidor\qrCode.jpg"); var configuration = Whatsapp.Options.newOptions().qrHandler(QrHandler.toFile(path, QrHandler.ToFileConsumer.toTerminal())).build(); conexion = Whatsapp.newConnection(configuration); conexion.connect().join();
> 
> Thanks

What do you mean by you can't connect exactly?

**Comment by edofredo** [comment]
I read the generated QR with my phone and it is not able to sign in.

**Comment by Auties00** [comment]
> I read the generated QR with my phone and it is not able to sign in.

Does the api throw an exception? Does Whatsapp throw an exception?

**Comment by edofredo** [comment]
No exception is thrown. Api keeps generating QR-Code images. I scan them with phone but the device is not able to link to Whatsapp. It´s like as the QR-image is not valid to link to the account.

**Comment by Auties00** [comment]
> No exception is thrown. Api keeps generating QR-Code images. I scan them with phone but the device is not able to link to Whatsapp. It´s like as the QR-image is not valid to link to the account.

Oh that's because you are not scanning it correctly. Make sure that your camera is aligned with the monitor angle and that it has a good enough quality. Also try with the terminal to see if the file is problem. Finally can you send an example qr code so I can check if it's correct(they expire after a new one in generated so it should not be Dangerous)

**Comment by edofredo** [comment]
![NotWorkingQrRC15](https://user-images.githubusercontent.com/79934744/179924342-7d2a0735-dcb1-4aa3-9720-b045d041259a.jpg)
![WorkingQrRC14](https://user-images.githubusercontent.com/79934744/179924358-bfed2a67-0aed-41e4-a0e4-b37e569cb25d.jpg)

Hi, here I upload 2 Qr codes.

1. Not Working Qr from RC15: starts with Optional[2@F7E...
2. WorkingQr from RC14: starts with 2@fB1s...

Could you please check. Thank you

**Comment by Auties00** [comment]
> ![NotWorkingQrRC15](https://user-images.githubusercontent.com/79934744/179924342-7d2a0735-dcb1-4aa3-9720-b045d041259a.jpg) ![WorkingQrRC14](https://user-images.githubusercontent.com/79934744/179924358-bfed2a67-0aed-41e4-a0e4-b37e569cb25d.jpg)
> 
> Hi, here I upload 2 Qr codes.
> 
> 1. Not Working Qr from RC15: starts with Optional[2@F7E...
> 2. WorkingQr from RC14: starts with 2@fB1s...
> 
> Could you please check. Thank you

I've fixed the issue but i noticed that i broke many things in the previous days. Once it's all fixed i'll push a new version

**Comment by Auties00** [comment]
> ![NotWorkingQrRC15](https://user-images.githubusercontent.com/79934744/179924342-7d2a0735-dcb1-4aa3-9720-b045d041259a.jpg) ![WorkingQrRC14](https://user-images.githubusercontent.com/79934744/179924358-bfed2a67-0aed-41e4-a0e4-b37e569cb25d.jpg)
> 
> Hi, here I upload 2 Qr codes.
> 
> 1. Not Working Qr from RC15: starts with Optional[2@F7E...
> 2. WorkingQr from RC14: starts with 2@fB1s...
> 
> Could you please check. Thank you

As soon as RC17 becomes avaialble on maven central, it should be fixed

**Comment by edofredo** [comment]
ok, thank you for your work. I fixed provisionally the issue with QrCode yesterday by reading de bad QrCode into String, deleting Optional[ and ] (the extra charachters that where added in RC15) and encoding the corrected String back to QrCode image.
