### ISSUE TITLE
On using the lib

### ISSUE THREAD

**Issue by abay94** [Auties00/WhatsappWeb4j#156]
Hello, please help with the following error:

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Failed on call to `getDeclaredMethods()` on class `it.auties.whatsapp.model.request.Request`, problem: (java.lang.NoClassDefFoundError) jakarta/websocket/Session

do I need to implement lib of jakarta.websocket additionally? 
because I used only this (likes a lot)) lib
thanks

**Comment by abay94** [comment]
or maybe some conflicts with 'org.springframework.boot:spring-boot-starter-websocket' ((

**Comment by abay94** [comment]
I did add jakarta.websocket:jakarta.websocket-client-api:2.1.0 additionally, but it stacks and after killing throws next exception:
jakarta.websocket.DeploymentException

**Comment by Auties00** [comment]
> I did add jakarta.websocket:jakarta.websocket-client-api:2.1.0 additionally, but it stacks and after killing throws next exception: jakarta.websocket.DeploymentException

https://github.com/Auties00/WhatsappWeb4j/issues/105
Follow the instructions here if you are using spring boot. I have no clue why this is needed, maybe there's a conflict between jakartaee and spring boot for some reason

**Comment by abay94** [comment]
thank you,I did solve it, big and great work!!!
