### ISSUE TITLE
Could not find com.github.auties00:link-preview:1.3.

### ISSUE THREAD

**Issue by ZiemlichUndead** [Auties00/WhatsappWeb4j#158]
Hey I dunno if im doing sth wrong but it seems I cannot get RC17 through maven because it requires your link-preview which as far as i know is not on maven yet.

`:ChatBot:test: Could not find com.github.auties00:link-preview:1.3.
Required by:
    project :ChatBot > com.github.auties00:whatsappweb4j:3.0-RC17`

I can kinda get around it by downloading link preview but when i try to build a jar file that still wont work.

**Comment by Auties00** [comment]
> Hey I dunno if im doing sth wrong but it seems I cannot get RC17 through maven because it requires your link-preview which as far as i know is not on maven yet.
> 
> `:ChatBot:test: Could not find com.github.auties00:link-preview:1.3. Required by: project :ChatBot > com.github.auties00:whatsappweb4j:3.0-RC17`
> 
> I can kinda get around it by downloading link preview but when i try to build a jar file that still wont work.

Yeah I will upload it tomorrow. I didn't notice it wasn't on maven central. Sorry

**Comment by Auties00** [comment]
> Hey I dunno if im doing sth wrong but it seems I cannot get RC17 through maven because it requires your link-preview which as far as i know is not on maven yet.
> 
> `:ChatBot:test: Could not find com.github.auties00:link-preview:1.3. Required by: project :ChatBot > com.github.auties00:whatsappweb4j:3.0-RC17`
> 
> I can kinda get around it by downloading link preview but when i try to build a jar file that still wont work.

Pushed, should become available within a few hours
