### ISSUE TITLE
Generated QR-Code not recognized by WhatsApp mobile client

### ISSUE THREAD

**Issue by ZeusInBlack73** [Auties00/WhatsappWeb4j#159]
Hi, 

the QR code is generated, successfully evaluated by Camera and/or QR reader app, but not recognized by WhatsApp mobile client. Therefore, the login does not work. Have the guys from Whatsapp changed something or am I doing something wrong? Is the problem known? I am using WhatsApp client version 2.22.15.74 on Android.

Thanks.

**Comment by Auties00** [comment]
> 

What version of this lib are you using?

**Comment by ZeusInBlack73** [comment]
Using Version 3.0-RC17

**Comment by Auties00** [comment]
> Using Version 3.0-RC17

Seems weird, though try RC18 and lmk

**Comment by ZeusInBlack73** [comment]
> > Using Version 3.0-RC17
> 
> Seems weird, though try RC18 and lmk

Can't install the new dependency from maven or git, dependencies for 3.0-RC18 or master-SNAPSHOT (jitpack.io) is not available. Could you reproduce the described problem with the QR code?

**Comment by Auties00** [comment]
> > > Using Version 3.0-RC17
> > 
> > 
> > Seems weird, though try RC18 and lmk
> 
> Can't install the new dependency from maven or git, dependencies for 3.0-RC18 or master-SNAPSHOT (jitpack.io) is not available. Could you reproduce the described problem with the QR code?

Sorry it takes a while for maven to get the dependency. Try again in an hour or so

**Comment by ZeusInBlack73** [comment]
The problem was that I took the QR from the console of the development environment. Directly on the system console it works fine. Thanks for creating and providing the api.
