### ISSUE TITLE
Can't use with java 11

### ISSUE THREAD

**Issue by syifarahmat** [Auties00/WhatsappWeb4j#16]
Can't use with java 11 
Error : 
![image](https://user-images.githubusercontent.com/11779955/116351379-c8202580-a81d-11eb-9e59-bcb0699aab68.png)

**Comment by syifarahmat** [comment]
Is it possible that you can convert / create a version that was built using Java version 11, to make customization easier 🙏🙏🙏🙏

**Comment by Auties00** [comment]
> Is it possible that you can convert / create a version that was built using Java version 11, to make customization easier 🙏🙏🙏🙏

Hello as of now I'm only committing to support Java 16 as Java 17, the next version, will be a LTS. I've noticed though that many people are asking for Java 11 support, the problem is that I'm using way too many new features and removing them would require a major change to the code base that would need to be reverted as soon as Java 17 comes out.

**Comment by GedMarc** [comment]
I did a full suite on the JDK 11 compatibility, it removes too much from the optimizations of the new Java versions and has an impact on operation, and class structure of the files. 

JDK 17 is the finalization LTS of the modular implementation however, so this is correct, as JDK 11 is missing fundamental features required for Modularization

**Comment by syifarahmat** [comment]
Ok thank's 

> > Is it possible that you can convert / create a version that was built using Java version 11, to make customization easier 🙏🙏🙏🙏
> 
> Hello as of now I'm only committing to support Java 16 as Java 17, the next version, will be a LTS. I've noticed though that many people are asking for Java 11 support, the problem is that I'm using way too many new features and removing them would require a major change to the code base that would need to be reverted as soon as Java 17 comes out.

Ok, thank's 👍👍👍

**Comment by Auties00** [comment]
> Ok thank's
> 
> > > Is it possible that you can convert / create a version that was built using Java version 11, to make customization easier 🙏🙏🙏🙏
> > 
> > 
> > Hello as of now I'm only committing to support Java 16 as Java 17, the next version, will be a LTS. I've noticed though that many people are asking for Java 11 support, the problem is that I'm using way too many new features and removing them would require a major change to the code base that would need to be reverted as soon as Java 17 comes out.
> 
> Ok, thank's 👍👍👍

Also, is there a specific reason why you want to use a java 11 other than it's the lts?

**Comment by syifarahmat** [comment]
> > Ok thank's
> > > > Is it possible that you can convert / create a version that was built using Java version 11, to make customization easier 🙏🙏🙏🙏
> > > 
> > > 
> > > Hello as of now I'm only committing to support Java 16 as Java 17, the next version, will be a LTS. I've noticed though that many people are asking for Java 11 support, the problem is that I'm using way too many new features and removing them would require a major change to the code base that would need to be reverted as soon as Java 17 comes out.
> > 
> > 
> > Ok, thank's 👍👍👍
> 
> Also, is there a specific reason why you want to use a java 11 other than it's the lts?

Yes ... I'm building a very complex system using spring boot with a jhipster gateway with multiple microservices as separate modules.  and currently jhipster only supports java 11.

**Comment by GedMarc** [comment]
JHipster sadly does not support JDK 11 yet, only backwards compatible to classpath mode - You will have no choice but to deploy a JDK to production instead of an operational runtime - 

What you are looking for is a backwards classpath mode system, not a modular one sadly - 

You should be able to use a shade on the artifacts to remove all module-info's across the board so that you can run in that JDK 1.8 mode on JDK 11 - 
But you will lose a good 40% or more performance in doing so (resulting in the loads of complaints about performance from running in backwards mode on modular JVM's)

That should solve your running problem, but I think careful in your chosen path, 
It is very likely classpath mode will be dropped for JRT in the very near future making your brand new development out of date in under a year

**Comment by syifarahmat** [comment]
> JHipster sadly does not support JDK 11 yet, only backwards compatible to classpath mode - You will have no choice but to deploy a JDK to production instead of an operational runtime -
> 
> What you are looking for is a backwards classpath mode system, not a modular one sadly -
> 
> You should be able to use a shade on the artifacts to remove all module-info's across the board so that you can run in that JDK 1.8 mode on JDK 11 -
> But you will lose a good 40% or more performance in doing so (resulting in the loads of complaints about performance from running in backwards mode on modular JVM's)
> 
> That should solve your running problem, but I think careful in your chosen path,
> It is very likely classpath mode will be dropped for JRT in the very near future making your brand new development out of date in under a year

Thank you for the explanation. 👍👍👍👍👍👍
I only use a small part of the technology offered by jHipster which includes gateway and microservices mode.

I completely overhauled and did not use the generator, focusing more on access to the dynamics of the microservices.

**Comment by GedMarc** [comment]
If you are going for Java in the MicroService space, take a look at GuicedEE and maybe Istio - as far as I'm aware they are the only JDK 11 compatible MicroService frameworks available today. 
MicroProfile and spring are CDI systems so it is inherently incapable of modularisation, relying on invalid encapsulation to operate.

Just a thought :)

**Comment by syifarahmat** [comment]
> If you are going for Java in the MicroService space, take a look at GuicedEE and maybe Istio - as far as I'm aware they are the only JDK 11 compatible MicroService frameworks available today.
> MicroProfile, Jakarta and spring are CDI systems so it is inherently incapable of modularisation, relying on invalid encapsulation and external files to the system in order to operate.
> 
> Just a thought :)

Yes, thank you for the explanation. 🙏🙏🙏
Are there alternatives other than jhipster? if anyone share here 😀😀😀😀
