### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class it.auties.whatsapp.util.JacksonProvider

### ISSUE THREAD

**Issue by mooziii** [Auties00/WhatsappWeb4j#160]
```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class it.auties.whatsapp.util.JacksonProvider
        at it.auties.whatsapp.util.Preferences.readAsInternal(Preferences.java:62)
        at it.auties.whatsapp.util.Preferences.readJson(Preferences.java:57)
        at it.auties.whatsapp.controller.Store.of(Store.java:171)
        at it.auties.whatsapp.api.Whatsapp.<init>(Whatsapp.java:81)
        at it.auties.whatsapp.api.Whatsapp.newConnection(Whatsapp.java:126)
        at it.auties.whatsapp.api.Whatsapp.lastConnection(Whatsapp.java:180)
        at me.obsilabor.bootstrap.Bootstrapper.main(Bootstrapper.java:15)
```

![image](https://user-images.githubusercontent.com/63669478/180778408-c01b43e7-14dd-44f0-a102-28a0a9a380e3.png)

This only happens when running a compiled jar, `gradlew run` or running through intellij works fine 

### Versions

 Java 17 combinded with Kotlin, Gradle 7.4.2, running on Linux (doesn't work on windows too) 
WhatsAppWeb4j Version: `com.github.auties00:whatsappweb4j:3.0-RC13`, doesn't work on newer ones too (RC17 didn't work because of #158, ill try this version in a second; Doesn't work either

**Comment by mooziii** [comment]
If it has something to do with the issue, my listener is written in kotlin

**Comment by Auties00** [comment]
> ```
> Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class it.auties.whatsapp.util.JacksonProvider
>         at it.auties.whatsapp.util.Preferences.readAsInternal(Preferences.java:62)
>         at it.auties.whatsapp.util.Preferences.readJson(Preferences.java:57)
>         at it.auties.whatsapp.controller.Store.of(Store.java:171)
>         at it.auties.whatsapp.api.Whatsapp.<init>(Whatsapp.java:81)
>         at it.auties.whatsapp.api.Whatsapp.newConnection(Whatsapp.java:126)
>         at it.auties.whatsapp.api.Whatsapp.lastConnection(Whatsapp.java:180)
>         at me.obsilabor.bootstrap.Bootstrapper.main(Bootstrapper.java:15)
> ```
> 
> ![image](https://user-images.githubusercontent.com/63669478/180778408-c01b43e7-14dd-44f0-a102-28a0a9a380e3.png)
> 
> This only happens when running a compiled jar, `gradlew run` or running through intellij works fine
> 
> ### Versions
> Java 17 combinded with Kotlin, Gradle 7.4.2, running on Linux (doesn't work on windows too) WhatsAppWeb4j Version: `com.github.auties00:whatsappweb4j:3.0-RC13`, doesn't work on newer ones too (RC17 didn't work because of #158, ill try this version in a second; Doesn't work either

So the problem is probably in how you are building the jar. Can you send your full build.gradle?

**Comment by mooziii** [comment]
```kotlin
plugins {
    kotlin("jvm") version "1.7.10"
    kotlin("plugin.serialization") version "1.7.10"
    id("com.github.johnrengelman.shadow") version "7.1.2"
    application
}

group = "me.obsilabor"
version = "1.0.0"

repositories {
    mavenCentral()
}

application {
    mainClass.set("me.obsilabor.bootstrap.Bootstrapper")
}

dependencies {
    implementation("com.github.auties00:whatsappweb4j:3.0-RC17")
    implementation("io.ktor:ktor-client-core:2.0.3")
    implementation("io.ktor:ktor-client-cio:2.0.3")
    implementation("io.ktor:ktor-client-content-negotiation:2.0.3")
    implementation("io.ktor:ktor-serialization-kotlinx-json:2.0.3")
}

tasks {
    shadowJar {
        manifest {
            attributes(
                "Main-Class" to "me.obsilabor.bootstrap.Bootstrapper"
            )
        }
    }
    compileJava {
        options.encoding = "UTF-8"
        options.compilerArgs.plusAssign("--enable-preview")
        options.release.set(17)
    }
}
```
this is my build.gradle.kts

**Comment by Auties00** [comment]
> 

You need to build a jar with dependencies: 
https://stackoverflow.com/questions/4871656/using-gradle-to-build-a-jar-with-dependencies

**Comment by mooziii** [comment]
I'll try this soon but isn't that exactly what the shadowjar plugins does?

**Comment by Auties00** [comment]
> I'll try this soon but isn't that exactly what the shadowjar plugins does?

Yeah, but I think that you would need to run the shadowJar task in particular which is something that you may not be doing

**Comment by mooziii** [comment]
I edited my buildscript to fit the one from your [WhatsappWebRequestAnalyzer's build.gradle.kts](https://github.com/Auties00/WhatsappWebRequestAnalyzer/blob/master/build.gradle.kts) which creates this jar if i'm not completely blind..

Still doesn't work, same error

**Comment by Auties00** [comment]
> I edited my buildscript to fit the one from your [WhatsappWebRequestAnalyzer's build.gradle.kts](https://github.com/Auties00/WhatsappWebRequestAnalyzer/blob/master/build.gradle.kts) which creates this jar if i'm not completely blind..
> 
> Still doesn't work, same error

You are probably looking at the wrong jar as multiple are generated. It should be in the target/lib i think

**Comment by mooziii** [comment]
I don't have a `target` directory. The jar with the `-with-dependencies` suffix is in `build/libs`

**Comment by Auties00** [comment]
> I don't have a `target` directory. The jar with the `-with-dependencies` suffix is in `build/libs`

yeah that's the one you should be using

**Comment by mooziii** [comment]
Same error with the fat jar
![image](https://user-images.githubusercontent.com/63669478/181221178-dd3e38e7-dcbe-4236-80b3-9512d621bf50.png)

**Comment by Auties00** [comment]
> Same error with the fat jar ![image](https://user-images.githubusercontent.com/63669478/181221178-dd3e38e7-dcbe-4236-80b3-9512d621bf50.png)

Can you send the jar?

**Comment by xNoobyyy** [comment]
Hi!
I have the exact same error as described above, even from within IntelliJ. My Jar-File contains the requested class (via "jar tf MY_JAR_FILE.jar"). Maybe some uncaught exception occurred and propagated up to the actual ClassLoader attempting to load the class?

**Comment by mooziii** [comment]
So i decided to create a whole new project with just the initialization of WhatsappWeb4j and a basic listener, same issue.

i can't upload jar files here so here's the download: https://workupload.com/file/6hdYn5rFFrP

**Comment by Auties00** [comment]
> So i decided to create a whole new project with just the initialization of WhatsappWeb4j and a basic listener, same issue.
> 
> i can't upload jar files here so here's the download: https://workupload.com/file/6hdYn5rFFrP

I found the error, just add --enable-preview. I didn't think about that for some reason

**Comment by Auties00** [comment]
> Hi! I have the exact same error as described above, even from within IntelliJ. My Jar-File contains the requested class (via "jar tf MY_JAR_FILE.jar"). Maybe some uncaught exception occurred and propagated up to the actual ClassLoader attempting to load the class? Using RC18 and Java 17 with preview-features enabled btw!

You don't have preview features enabled probably

**Comment by mooziii** [comment]
It works now, thanks a lot!
