### ISSUE TITLE
Get full chat history

### ISSUE THREAD

**Issue by Tiebe** [Auties00/WhatsappWeb4j#161]
I'm trying to get the full chat history from a chat. How would I be able to achieve this?

I currently have an `onNewMessage` listener, and getting the messages with `message.chat().messages()`, but it only gives me the past 32 messages. How can I get more?

**Comment by Auties00** [comment]
> I'm trying to get the full chat history from a chat. How would I be able to achieve this?
> 
> I currently have an `onNewMessage` listener, and getting the messages with `message.chat().messages()`, but it only gives me the past 32 messages. How can I get more?

By default whatsapp sends only the messages in the last three months. If you need more you can set the history length option in Whatsapp.Options to one year. When you first scan the qr code, the messages will be sent in chunks. Listen to onChatMessages(read the documentation for that) and you should be done

**Comment by Tiebe** [comment]
With both options, it only pulls the last 32 messages per contact, although I have sent many more than that.

**Comment by Auties00** [comment]
> With both options, it only pulls the last 32 messages per contact, although I have sent many more than that.

So try to create a new session and put a print in onChatMessages and check if the chat is the one you need and see how many chunks you receive
