### ISSUE TITLE
Message sending stops working after several hours

### ISSUE THREAD

**Issue by abay94** [Auties00/WhatsappWeb4j#163]
After logging IN, messages are sent without an error for about 2-3 hours, but then it stops working. Log messages look  like this:
 
(1)
Cannot send Request[id=0c-210, body=Node[description=iq, attributes={xmlns=usync, to=s.whatsapp.net, id=0c-210, type=get}, content=[Node[description=usync, attributes={mode=query, context=message, index=0, last=true, sid=0c-209}, content=[Node[description=query, content=[Node[description=devices, attributes={version=2}]]], Node[description=list, content=[Node[description=user, attributes={jid=**********@s.whatsapp.net}], Node[description=user, attributes={jid=**********@s.whatsapp.net}]]]]]]], future=java.util.concurrent.CompletableFuture@35cbcff6[Not completed], caller=java.lang.RuntimeException]
	at it.auties.whatsapp.model.request.Request.send(Request.java:125)
	at it.auties.whatsapp.model.request.Request.send(Request.java:86)
	at it.auties.whatsapp.socket.Socket.send(Socket.java:261)
	at it.auties.whatsapp.socket.Socket.sendQuery(Socket.java:323)
	at it.auties.whatsapp.socket.Socket.sendQuery(Socket.java:303)
	at it.auties.whatsapp.socket.MessageHandler.queryDevices(MessageHandler.java:287)
	at it.auties.whatsapp.socket.MessageHandler.getDevices(MessageHandler.java:273)
	at it.auties.whatsapp.socket.MessageHandler.encode(MessageHandler.java:99)
	at it.auties.whatsapp.socket.Socket.sendMessage(Socket.java:299)
	at it.auties.whatsapp.api.Whatsapp.sendMessage(Whatsapp.java:920)
	at it.auties.whatsapp.api.Whatsapp.sendMessage(Whatsapp.java:899)
	at it.auties.whatsapp.api.Whatsapp.sendMessage(Whatsapp.java:813)

removed phone numbers)

(2)
java.lang.RuntimeException: Cannot decrypt message with type skmsg inside status@broadcast from *************@s.whatsapp.net
	at it.auties.whatsapp.socket.MessageHandler.decodeMessageBytes(MessageHandler.java:492)
	at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:421)
	at it.auties.whatsapp.socket.MessageHandler.lambda$decode$35(MessageHandler.java:369)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:369)
	at it.auties.whatsapp.socket.Socket.readMessage(Socket.java:294)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:64)
	at it.auties.whatsapp.socket.Socket.handleNode(Socket.java:175)

I did not find a problem why this happened

**Comment by Auties00** [comment]
> After logging IN, messages are sent without an error for about 2-3 hours, but then it stops working. Log messages look  like this:
> 
> (1) Cannot send Request[id=0c-210, body=Node[description=iq, attributes={xmlns=usync, to=s.whatsapp.net, id=0c-210, type=get}, content=[Node[description=usync, attributes={mode=query, context=message, index=0, last=true, sid=0c-209}, content=[Node[description=query, content=[Node[description=devices, attributes={version=2}]]], Node[description=list, content=[Node[description=user, attributes={jid=**********@s.whatsapp.net}], Node[description=user, attributes={jid=**********@s.whatsapp.net}]]]]]]], future=java.util.concurrent.CompletableFuture@35cbcff6[Not completed], caller=java.lang.RuntimeException] at it.auties.whatsapp.model.request.Request.send(Request.java:125) at it.auties.whatsapp.model.request.Request.send(Request.java:86) at it.auties.whatsapp.socket.Socket.send(Socket.java:261) at it.auties.whatsapp.socket.Socket.sendQuery(Socket.java:323) at it.auties.whatsapp.socket.Socket.sendQuery(Socket.java:303) at it.auties.whatsapp.socket.MessageHandler.queryDevices(MessageHandler.java:287) at it.auties.whatsapp.socket.MessageHandler.getDevices(MessageHandler.java:273) at it.auties.whatsapp.socket.MessageHandler.encode(MessageHandler.java:99) at it.auties.whatsapp.socket.Socket.sendMessage(Socket.java:299) at it.auties.whatsapp.api.Whatsapp.sendMessage(Whatsapp.java:920) at it.auties.whatsapp.api.Whatsapp.sendMessage(Whatsapp.java:899) at it.auties.whatsapp.api.Whatsapp.sendMessage(Whatsapp.java:813)
> 
> removed phone numbers)
> 
> (2) java.lang.RuntimeException: Cannot decrypt message with type skmsg inside status@broadcast from *************@s.whatsapp.net at it.auties.whatsapp.socket.MessageHandler.decodeMessageBytes(MessageHandler.java:492) at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:421) at it.auties.whatsapp.socket.MessageHandler.lambda$decode$35(MessageHandler.java:369) at java.base/java.lang.Iterable.forEach(Iterable.java:75) at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:369) at it.auties.whatsapp.socket.Socket.readMessage(Socket.java:294) at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:64) at it.auties.whatsapp.socket.Socket.handleNode(Socket.java:175)
> 
> I did not find a problem why this happened

Does everything else keep working? Is it just message sending?

**Comment by abay94** [comment]
yeap, only sending message failed, but interestingly I did try to send every 5 minutes to 5 numbers, then it can be sent first message and other 4 messages were failed, I did repeat for 7-8 times, the same result, Maybe I did make some errors I am not sure

**Comment by Auties00** [comment]
> yeap, only sending message failed, but interestingly I did try to send every 5 minutes to 5 numbers, then it can be sent first message and other 4 messages were failed, I did repeat for 7-8 times, the same result, Maybe I did make some errors I am not sure

After some hours or immediately? What version are you using btw?

**Comment by abay94** [comment]
sorry, RC18, this case was - immediately

**Comment by Auties00** [comment]
> sorry, RC18, this case was - immediately

Does this happen with all sessions? Have you tried to delete the current one and to reproduce it?

**Comment by abay94** [comment]
After reproducing it goes well, maybe I did some errors(
