### ISSUE TITLE
Modify default path of .whatsappweb4j directory

### ISSUE THREAD

**Issue by edofredo** [Auties00/WhatsappWeb4j#164]
Hi @Auties00, is it possible to modify the path of the .whatsappweb4j directory so that I can store it elsewhere?

**Comment by Auties00** [comment]
> Hi @Auties00, is it possible to modify the path of the .whatsappweb4j directory so that I can store it elsewhere?

Yeah but you'll have to write a custom serializer,, check the readme

**Comment by edofredo** [comment]
Oh, I hadn´t seen it. Thanks

**Comment by edofredo** [comment]
I implemented the CustomSerializer and it works fine. Thank you. With defaultSerialization(), for getting keys & store of previous sessions you have Whatsapp.listConnections(). Is there a way to get the List<Whatsapp> from keys & stores using the location from CustomSerializer?

**Comment by edofredo** [comment]
I implemented the CustomSerializer and it works fine. Thank you. With default serialization, for getting keys & store of previous sessions you have Whatsapp.listConnections(). Is there a way to get the List of Whatsapp objects from previous sessions using the location from CustomSerializer?

**Comment by Auties00** [comment]
> I implemented the CustomSerializer and it works fine. Thank you. With default serialization, for getting keys & store of previous sessions you have Whatsapp.listConnections(). Is there a way to get the List of Whatsapp objects from previous sessions using the location from CustomSerializer?

Oh well I never thought about that, I should implement a service for that

**Comment by Auties00** [comment]
> I implemented the CustomSerializer and it works fine. Thank you. With default serialization, for getting keys & store of previous sessions you have Whatsapp.listConnections(). Is there a way to get the List of Whatsapp objects from previous sessions using the location from CustomSerializer?

In the latest version, I've added a ids() method inside ControllerProvider, previously ControllerSerializer, to handle this use case. Also added documentation to the readme. Thanks for the suggestion
