### ISSUE TITLE
How to get Audio File from AudioMessage

### ISSUE THREAD

**Issue by xNoobyyy** [Auties00/WhatsappWeb4j#165]
Idk if I'm just stupid or something (I probably am) but how do I get an audio file from an AudioMessage?
edit: is this even possible?

**Comment by Auties00** [comment]
> Idk if I'm just stupid or something (I probably am) but how do I get an audio file from an AudioMessage? edit: is this even possible?

If you have a message info, access the message, check if it's a MediaMessage and then use decodedMedia()

**Comment by xNoobyyy** [comment]
Does this work for voice messages (and if yes, do I have to check for a file format or is it the same every time)?

**Comment by xNoobyyy** [comment]
opus, got it!

**Comment by Auties00** [comment]
> Does this work for voice messages (and if yes, do I have to check for a file format or is it the same every time)?

Works for every file, maybe I should add a function to write it to a file easily
