### ISSUE TITLE
Whatsapp disconnects all sessions

### ISSUE THREAD

**Issue by ZiemlichUndead** [Auties00/WhatsappWeb4j#166]
I have now seen it mulltiple times that WhatsappWeb4j(RC18) just gets disconnected by Whatsapp for some reason.
When I go to linked devices in Whatsapp I get a pop up that says an error occured and whatsapp manually disconnected all my Whatsapp Web sessions.
I always thought this might be happening due to other errors I am seeing in my console but i have had this happen now with no exception being thrown at all.

I havent saved any logs or screenshots of this yet but i will do so when it happens again

**Comment by Auties00** [comment]
> I have now seen it mulltiple times that WhatsappWeb4j(RC18) just gets disconnected by Whatsapp for some reason. When I go to linked devices in Whatsapp I get a pop up that says an error occured and whatsapp manually disconnected all my Whatsapp Web sessions. I always thought this might be happening due to other errors I am seeing in my console but i have had this happen now with no exception being thrown at all.
> 
> I havent saved any logs or screenshots of this yet but i will do so when it happens again

Well no exceptions should be thrown at all. Can you send them?

**Comment by ZiemlichUndead** [comment]
> > I have now seen it mulltiple times that WhatsappWeb4j(RC18) just gets disconnected by Whatsapp for some reason. When I go to linked devices in Whatsapp I get a pop up that says an error occured and whatsapp manually disconnected all my Whatsapp Web sessions. I always thought this might be happening due to other errors I am seeing in my console but i have had this happen now with no exception being thrown at all.
> > I havent saved any logs or screenshots of this yet but i will do so when it happens again
> 
> Well no exceptions should be thrown at all. Can you send them?

Problem hasn't happened again since i wrote this.
When thinking about the scenario I can imagine that the disconnect might have happened due to me debugging things which caused timeouts or other problems resulting in the logoff.

I will post if i see this again.

**Comment by ZiemlichUndead** [comment]
To update you. I had this happening one more time in the entire duration this issue has been open. I took a screenshot (only German text tho). 
![Screenshot_20220812-152339](https://user-images.githubusercontent.com/19202897/187946974-a11904cf-dcfd-4151-8318-e82334dae890.jpg)

The moment this happened I think I was playing around with multiple instances of whatsappweb4j running on different IPs. 
I feel like this happens really rarely and has something to do with registering clients and their IP addresses (Maybe WhatsApp disconnects Sessions if it detects a too far distance between sessions?).
Overall i don't think this is an issue with whatsappweb4j right now.

**Comment by Auties00** [comment]
> To update you. I had this happening one more time in the entire duration this issue has been open. I took a screenshot (only German text tho). ![Screenshot_20220812-152339](https://user-images.githubusercontent.com/19202897/187946974-a11904cf-dcfd-4151-8318-e82334dae890.jpg)
> 
> The moment this happened I think I was playing around with multiple instances of whatsappweb4j running on different IPs. I feel like this happens really rarely and has something to do with registering clients and their IP addresses (Maybe WhatsApp disconnects Sessions if it detects a too far distance between sessions?). Overall i don't think this is an issue with whatsappweb4j right now.

Gonna archive it for now then, if something new comes up reopen the issue
