### ISSUE TITLE
Business version whatsapp message withdrawal

### ISSUE THREAD

**Issue by liufei940309** [Auties00/WhatsappWeb4j#170]
The enterprise version of whatsapp message is deleted and synchronized on all devices. There is a bug on the mobile phone

  public CompletableFuture<MessageInfo> delete(@NonNull MessageInfo info, boolean everyone) {
        if (everyone) {
            var message = ProtocolMessage.newProtocolMessageBuilder()
                    .type(ProtocolMessage.ProtocolMessageType.REVOKE)
                    .key(info.key())
                    .build();
            return sendMessage(info.chatJid(), message);
        }
}

**Comment by Auties00** [comment]
> The enterprise version of whatsapp message is deleted and synchronized on all devices. There is a bug on the mobile phone
> 
> public CompletableFuture delete(@nonnull MessageInfo info, boolean everyone) { if (everyone) { var message = ProtocolMessage.newProtocolMessageBuilder() .type(ProtocolMessage.ProtocolMessageType.REVOKE) .key(info.key()) .build(); return sendMessage(info.chatJid(), message); } }

So it should delete messages for everyone always if the account is a business one?

**Comment by liufei9263liya** [comment]
Log in to the enterprise version of whatsapp to delete all messages on the device failed to delete, can not sync mobile phone

**Comment by liufei9263liya** [comment]
`   public CompletableFuture<MessageInfo> delete(@NonNull MessageInfo info, boolean everyone) {
        if (everyone) {
            ProtocolMessage protocolMessage=new ProtocolMessage();
            protocolMessage.type(ProtocolMessage.ProtocolMessageType.REVOKE);
            protocolMessage.key(info.key());
            return sendMessage(info.chatJid(), protocolMessage);
        }`

**Comment by Auties00** [comment]
> Log in to the enterprise version of whatsapp to delete all messages on the device failed to delete, can not sync mobile phone

I see, it's a bug probably
