### ISSUE TITLE
Media message download error

### ISSUE THREAD

**Issue by liufei940309** [Auties00/WhatsappWeb4j#171]
`  public byte[] download(AttachmentProvider provider, Store store) {
        return getDownloadUrls(provider, store).stream()
                .map(url -> download(provider, url))
                .flatMap(Optional::stream)
                .findFirst()
                .orElseThrow(
                        () -> new IllegalStateException("Cannot download encrypted media: no suitable host found"));
    }`

Media message download error

**Comment by Auties00** [comment]
> ` public byte[] download(AttachmentProvider provider, Store store) { return getDownloadUrls(provider, store).stream() .map(url -> download(provider, url)) .flatMap(Optional::stream) .findFirst() .orElseThrow( () -> new IllegalStateException("Cannot download encrypted media: no suitable host found")); }`
> 
> Media message download error

What type of media are you trying to decide?

**Comment by liufei9263liya** [comment]
Pictures and documents are wrong













At 2022-09-03 05:58:07, "Alessandro Autiero" ***@***.***> wrote:

public byte[] download(AttachmentProvider provider, Store store) { return getDownloadUrls(provider, store).stream() .map(url -> download(provider, url)) .flatMap(Optional::stream) .findFirst() .orElseThrow( () -> new IllegalStateException("Cannot download encrypted media: no suitable host found")); }

Media message download error

What type of media are you trying to decode?

**Comment by Auties00** [comment]
> Pictures and documents are wrong At 2022-09-03 05:58:07, "Alessandro Autiero" ***@***.***> wrote: public byte[] download(AttachmentProvider provider, Store store) { return getDownloadUrls(provider, store).stream() .map(url -> download(provider, url)) .flatMap(Optional::stream) .findFirst() .orElseThrow( () -> new IllegalStateException("Cannot download encrypted media: no suitable host found")); } Media message download error What type of media are you trying to decode? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

After looking into it, it looks like Whatsapp returns a 404 status error. I'm not sure what do to be honest

**Comment by Auties00** [comment]
I've concluded that it's because Whatsapp sends a 404 status for older messages, I don't know how to fix it to be honest. I can see that the web app actually loads it somehow. I'll look into it

**Comment by Auties00** [comment]
Managed to fix it by implementing media reuploads, I'll see if it works well but the fix is already committed just not in any release
