### ISSUE TITLE
syncType is marked non-null but is null

### ISSUE THREAD

**Issue by tomlux** [Auties00/WhatsappWeb4j#172]
Hy,
while testing your latest version (https://github.com/Auties00/WhatsappWeb4j/commit/7b27fd6b6b79a8dc0ba805e1ac2b4262ff14b01e), I'm getting this error during startup:

**syncType is marked non-null but is null**
This happens only on the first run during creating the ".whatsappweb4j" datastore.
A second run with an existing datastore in ".whatsappweb4j" is running without error.
After deleting the ".whatsappweb4j" folder, the error reappears again on first run.

> com.fasterxml.jackson.databind.JsonMappingException: syncType is marked non-null but is null
 at [Source: (byte[])[1872 bytes]; byte offset: #2] (through reference chain: it.auties.whatsapp.model.sync.HistorySync$HistorySyncBuilder["syncType"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:276)

**Comment by Auties00** [comment]
> Hy, while testing your latest version ([7b27fd6](https://github.com/Auties00/WhatsappWeb4j/commit/7b27fd6b6b79a8dc0ba805e1ac2b4262ff14b01e)), I'm getting this error during startup:
> 
> **syncType is marked non-null but is null** This happens only on the first run during creating the ".whatsappweb4j" datastore. A second run with an existing datastore in ".whatsappweb4j" is running without error. After deleting the ".whatsappweb4j" folder, the error reappears again on first run.
> 
> > com.fasterxml.jackson.databind.JsonMappingException: syncType is marked non-null but is null
> > at [Source: (byte[])[1872 bytes]; byte offset: #2] (through reference chain: it.auties.whatsapp.model.sync.HistorySync$HistorySyncBuilder["syncType"])
> > at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:276)

Does that happen also with the previous version?

**Comment by Auties00** [comment]
Reviewing every issue right now turns out that this issue messed up all of the session history. Thanks very much for reporting it

**Comment by Auties00** [comment]
Should be fixed in RC19, please lmk

**Comment by tomlux** [comment]
this is working, thanks
