### ISSUE TITLE
Unable to build 3.0-RC19 - Maven artifact version 3.0-RC19 not published

### ISSUE THREAD

**Issue by jkaa** [Auties00/WhatsappWeb4j#173]
- Maven artifact with version 3.0-RC19 not published
- building locally fails on dependency resolution for 'com.github.auties00:qr-terminal:jar:1.2' - artifact also not published [see issue here](https://github.com/Auties00/QrToTerminal/issues/1)

**Comment by Auties00** [comment]
Will fix all of these issues by the end of the week, just started school so I need a moment

**Comment by Auties00** [comment]
> * Maven artifact with version 3.0-RC19 not published
> * building locally fails on dependency resolution for 'com.github.auties00:qr-terminal:jar:1.2' - artifact also not published [see issue here](https://github.com/Auties00/QrToTerminal/issues/1)

Should be fixed, lmk
