### ISSUE TITLE
ButtonsMessage doesn't render in the recipient whatsapp client

### ISSUE THREAD

**Issue by fill341** [Auties00/WhatsappWeb4j#178]
Hi! I have a weird issue. 
When i'm trying to send a TextMessage or an ImageMessage - it renders fine on both sides(recipient whatsapp client, and connected to the app client). But that's not working for ButtonsMessage, and actually ListMessage too. In 99% i have nothing in the recipient client. But, it always renders fine in the connected client. Did i miss something?

**Comment by Auties00** [comment]
> Hi! I have a weird issue. When i'm trying to send a TextMessage or an ImageMessage - it renders fine on both sides(recipient whatsapp client, and connected to the app client). But that's not working for ButtonsMessage, and actually ListMessage too. In 99% i have nothing in the recipient client. But, it always renders fine in the connected client. Did i miss something?

Are you using the latest version of Whatsapp?

**Comment by fill341** [comment]
Yeah, i've tested that in the latest ios client and the web client too.

**Comment by ssouza** [comment]
```java
var buttons = List.of(ButtonRow.of("First option", "A nice description"),
      ButtonRow.of("Second option", "A nice description"),
      ButtonRow.of("Third option", "A nice description")); // Create some buttons
var section = ButtonSection.of("First section", buttons); // Create a section from those buttons
var otherButtons = List.of(ButtonRow.of("First option", "A nice description"),
      ButtonRow.of("Second option", "A nice description"),
      ButtonRow.of("Third option", "A nice description")); // Create some other buttons
var anotherSection = ButtonSection.of("First section", otherButtons); // Create another section from those buttons
var listMessage = ListMessage.newListMessageBuilder() // Create a list message builder
      .sections(List.of(section, anotherSection)) // Set the sections
      .button("Click me") // Set the button name that opens the menu
      .title("A nice title") // Set the title of the message
      .description("A nice description") // Set the description of the message
      .footer("A nice footer") // Set the footer of the message
      .type(ListMessage.Type.SINGLE_SELECT) // Set the type of the message
      .build(); // Create a list message
api.sendMessage(contact, listMessage);
```

This example with ListMessage didn't work (version RC-18)

**Comment by fill341** [comment]
Yeah, i've tested with the latest version from source code and with version 3.0-RC18, trying to send ButtonsMessage like this
`                whatsapp.sendMessage(update.chat().jid(),
                        ButtonsMessage.newButtonsWithTextHeaderMessageBuilder()
                                .body("Are you sure?")
                                .header("question")
                                .footer("footer")
                                .buttons(List.of(
                                        Button.newResponseButton(UUID.randomUUID().toString(), "Yes!"),
                                        Button.newResponseButton(UUID.randomUUID().toString(), "No!")
                                ))
                                .build()
                );`

In both versions issue the same, the connected whatsapp client showing the message, but clients who text to him - doesn't. However, LocationMessage, TextMessage, ImageMessage works fine on both sides.

**Comment by Auties00** [comment]
> Yeah, i've tested with the latest version from source code and with version 3.0-RC18, trying to send ButtonsMessage like this
> 
> ```
>  whatsapp.sendMessage(update.chat().jid(),
>         ButtonsMessage.newButtonsWithTextHeaderMessageBuilder()
>                 .body("Are you sure?")
>                 .header("question")
>                 .footer("footer")
>                 .buttons(List.of(
>                         Button.newResponseButton(UUID.randomUUID().toString(), "Yes!"),
>                         Button.newResponseButton(UUID.randomUUID().toString(), "No!")
>                 ))
>                 .build()
> );
> ```
> 
> In both versions issue the same, the connected whatsapp client showing the message, but clients who text to him - doesn't. However, LocationMessage, TextMessage, ImageMessage works fine on both sides.

It's definitely a WhatsApp bug, in my region everything's working fine. Can you try to wrap the message in an ephemeral one and see if it works?

**Comment by Auties00** [comment]
Looks like there's a similar issue for Baileys(https://github.com/adiwajshing/Baileys/issues/2132), I will guess that it's indeed a WhatsApp bug

**Comment by fill341** [comment]
I've tested the bug in https://github.com/adiwajshing/Baileys, i've changed the example to send ButtonsForm, and it's working. I'm able to send form and see it in all the clients. So it's not the whatsapp client bug.

**Comment by Auties00** [comment]
> I've tested the bug in https://github.com/adiwajshing/Baileys, i've changed the example to send ButtonsForm, and it's working. I'm able to send form and see it in all the clients. So it's not the whatsapp client bug.
> 
> ```
> await sock.sendMessage(msg.key.remoteJid!, {
> 		text: "Hi it's button message",
> 		footer: 'Hello World',
> 		buttons: [
> 			{ buttonId: 'id1', buttonText: { displayText: 'Button 1' }, type: 1 },
> 			{ buttonId: 'id2', buttonText: { displayText: 'Button 2' }, type: 1 },
> 			{ buttonId: 'id3', buttonText: { displayText: 'Button 3' }, type: 1 }
> 		],
> 	})
> ```

As I've said can you try the same with my library but by wrapping the message in an ephemeral one to see if it works?

**Comment by cm-creativecentral** [comment]
> 

then how can i send call buttons

**Comment by Auties00** [comment]
> > 
> 
> then how can i send call buttons

What?

**Comment by fill341** [comment]
> > I've tested the bug in https://github.com/adiwajshing/Baileys, i've changed the example to send ButtonsForm, and it's working. I'm able to send form and see it in all the clients. So it's not the whatsapp client bug.
> 
> > 
> 
> > ```
> 
> > await sock.sendMessage(msg.key.remoteJid!, {
> 
> > 		text: "Hi it's button message",
> 
> > 		footer: 'Hello World',
> 
> > 		buttons: [
> 
> > 			{ buttonId: 'id1', buttonText: { displayText: 'Button 1' }, type: 1 },
> 
> > 			{ buttonId: 'id2', buttonText: { displayText: 'Button 2' }, type: 1 },
> 
> > 			{ buttonId: 'id3', buttonText: { displayText: 'Button 3' }, type: 1 }
> 
> > 		],
> 
> > 	})
> 
> > ```
> 
> 
> 
> As I've said can you try the same with my library but by wrapping the message in an ephemeral one to see if it works?

Ah, sorry, forgot to mention. I've already tested it with the ephemeral message. It's the same. I have been debugging the library, but looks like it correctly send messages to all the clients. May be something wrong in a message content. I dunno.

**Comment by Auties00** [comment]
> > As I've said can you try the same with my library but by wrapping the message in an ephemeral one to see if it works?
> 
> Ah, sorry, forgot to mention. I've already tested it with the ephemeral message. It's the same. I have been debugging the library, but looks like it's correctly send messages to all the clients. May be something wrong in a message content. I dunno.

I've just tried the buttons message and I can see it on all of my devices without any problems. Any way to replicate it?

**Comment by Auties00** [comment]
Just tried a list message, same thing

**Comment by Auties00** [comment]
> > As I've said can you try the same with my library but by wrapping the message in an ephemeral one to see if it works?
> 
> Ah, sorry, forgot to mention. I've already tested it with the ephemeral message. It's the same. I have been debugging the library, but looks like it's correctly send messages to all the clients. May be something wrong in a message content. I dunno.

Never mind, I managed to reproduce it and it should be fixed. Please check RC20

**Comment by fill341** [comment]
> > > As I've said can you try the same with my library but by wrapping the message in an ephemeral one to see if it works?
> > 
> > 
> > Ah, sorry, forgot to mention. I've already tested it with the ephemeral message. It's the same. I have been debugging the library, but looks like it's correctly send messages to all the clients. May be something wrong in a message content. I dunno.
> 
> Never mind, I managed to reproduce it and it should be fixed. Please check RC24

Thx! It's working! I really appreciate that.
