### ISSUE TITLE
Missing QR-Terminal 2.0

### ISSUE THREAD

**Issue by eaceto** [Auties00/WhatsappWeb4j#179]
First of all, this is such an amazing implamentation of the WhatsApp Web API. Well done! :clap: 

I have an issue trying to use versions equals or newer than 3.0-RC20 because

   > Could not resolve all files for configuration ':compileClasspath'.
      > Could not find com.github.auties00:qr-terminal:2.0.
        Searched in the following locations:
          - https://repo.maven.apache.org/maven2/com/github/auties00/qr-terminal/2.0/qr-terminal-2.0.pom
        If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
        Required by:
            project : > com.github.auties00:whatsappweb4j:3.0-RC20

Latest stable and working release is RC19, which uses an older version (but published) of QR Terminal. 

I found out QR Terminal 2.0 is not published in Maven Central. Could you please upload it?

Thanks!

**Comment by Auties00** [comment]
> First of all, this is such an amazing implamentation of the WhatsApp Web API. Well done! 👏
> 
> I have an issue trying to use versions equals or newer than 3.0-RC20 because
> 
> > Could not resolve all files for configuration ':compileClasspath'.
> > > Could not find com.github.auties00:qr-terminal:2.0.
> > Searched in the following locations:
> > - https://repo.maven.apache.org/maven2/com/github/auties00/qr-terminal/2.0/qr-terminal-2.0.pom
> > If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
> > Required by:
> > project : > com.github.auties00:whatsappweb4j:3.0-RC20
> 
> Latest stable and working release is RC19, which uses an older version (but published) of QR Terminal.
> 
> I found out QR Terminal 2.0 is not published in Maven Central. Could you please upload it?
> 
> Thanks!

Thank you very much, sorry but I pushed out too many releases today and I lost track of some things. I pushed the QR terminal library to 2.0, please also upgrade to RC24
