### ISSUE TITLE
The api does not show QR when updating to 3.0RC19

### ISSUE THREAD

**Issue by diegoalbertosaez** [Auties00/WhatsappWeb4j#180]
With the default configuration I get this on the console and not the QR:
â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ
â–ˆâ–ˆ â–„â–„â–„â–„â–„ â–ˆâ–ˆ â–„ â–€â–ˆâ–„ â–„â–„â–€â–€ â–€â–€ â–„ â–„ â–ˆâ–€â–„ â–„â–ˆâ–„â–€â–€â–ˆ   â–„ â–€â–ˆâ–ˆ â–„â–„â–„â–„â–„ â–ˆâ–ˆ
â–ˆâ–ˆ â–ˆ   â–ˆ â–ˆâ–€ â–„â–„â–„  â–„â–ˆ   â–ˆ â–€â–„ â–„â–€â–€â–€â–„ â–„ â–€â–„â–ˆâ–€â–ˆâ–„ â–€â–€â–€â–„â–€â–ˆ â–ˆ   â–ˆ â–ˆâ–ˆ
â–ˆâ–ˆ â–ˆâ–„â–„â–„â–ˆ â–ˆâ–„â–„â–€ â–„â–€â–€â–€â–€â–„ â–„â–€â–„â–€â–„ â–„â–„â–„  â–„â–„â–ˆâ–ˆâ–€â–ˆâ–ˆ â–ˆâ–„â–„â–„ â–ˆâ–ˆâ–ˆ â–ˆâ–„â–„â–„â–ˆ â–ˆâ–ˆ
â–ˆâ–ˆâ–„â–„â–„â–„â–„â–„â–„â–ˆâ–„â–€â–„â–ˆâ–„â–ˆ â–€â–„â–€ â–€ â–ˆâ–„â–ˆ â–ˆâ–„â–ˆ â–ˆâ–„â–€â–„â–ˆ â–€â–„â–ˆ â–ˆâ–„â–€ â–ˆâ–„â–ˆâ–„â–„â–„â–„â–„â–„â–„â–ˆâ–ˆ
â–ˆâ–ˆâ–„ â–€â–ˆâ–ˆâ–„â–„ â–ˆâ–„â–ˆâ–ˆâ–„â–„  â–ˆâ–„ â–„ â–€â–€â–€â–„  â–„   â–„â–ˆâ–€â–€â–„â–„â–€ â–€â–ˆ  â–„ â–€â–€â–ˆ â–„â–€â–ˆâ–€â–ˆâ–ˆ
â–ˆâ–ˆâ–€â–„â–ˆâ–„ â–€â–„â–ˆâ–„â–„   â–€â–„  â–ˆâ–ˆâ–ˆâ–„â–€â–ˆ â–€â–ˆâ–ˆâ–ˆâ–ˆ â–€â–„â–ˆâ–„â–„â–ˆâ–„â–€â–ˆâ–€â–€  â–ˆâ–„â–„â–ˆâ–€â–ˆâ–ˆâ–„â–€â–ˆâ–ˆâ–ˆ
â–ˆâ–ˆâ–€â–ˆâ–ˆ â–€â–„â–„â–€â–€â–ˆâ–€â–ˆâ–„â–€ â–€â–„â–ˆ  â–„â–ˆ â–€  â–€â–„â–€â–€ â–€â–„â–€â–ˆâ–€ â–€â–ˆ â–„â–ˆâ–€â–€â–„ â–ˆâ–€ â–„â–ˆ â–€â–ˆâ–ˆ
â–ˆâ–ˆâ–ˆ â–€â–„ â–€â–„ â–„â–„ â–€â–ˆâ–€â–€â–„â–„â–„â–€â–ˆâ–ˆ â–€â–ˆâ–€ â–€â–ˆâ–€  â–€â–ˆâ–ˆ â–ˆâ–„ â–€â–ˆâ–„ â–€â–„â–€â–„â–ˆâ–€â–„â–„â–€ â–€â–ˆâ–ˆ
â–ˆâ–ˆâ–ˆ â–ˆâ–€â–„â–€â–„ â–„â–€â–ˆâ–„â–€â–€â–ˆâ–ˆâ–ˆ  â–€â–ˆâ–€â–€ â–„  â–ˆâ–€â–€ â–„â–€â–€â–„â–„  â–ˆâ–ˆâ–€ â–€â–„â–„ â–„ â–„â–ˆ â–„â–„â–ˆâ–ˆ
â–ˆâ–ˆâ–ˆ  â–ˆâ–ˆ â–„â–ˆ  â–ˆâ–„â–€â–€ â–ˆâ–„â–€ â–ˆ â–„â–€ â–€â–€â–ˆâ–ˆ â–„â–„ â–€â–ˆ â–€â–ˆâ–ˆâ–„â–„â–€ â–€ â–€ â–ˆ â–„â–€â–ˆâ–€â–„â–ˆâ–ˆ
â–ˆâ–ˆâ–€â–„â–„â–„â–ˆ â–„â–€â–„â–„â–„â–ˆâ–€ â–€ â–€     â–ˆâ–„ â–ˆâ–€â–€â–ˆâ–€â–€ â–ˆâ–€â–€â–„ â–„ â–€â–ˆ â–€ â–€ â–€â–„ â–€â–ˆâ–„â–ˆâ–ˆâ–ˆ
â–ˆâ–ˆâ–ˆ  â–„â–„â–ˆâ–„ â–€â–€â–„â–„ â–„  â–„â–€ â–€â–„â–ˆâ–€â–„â–€ â–„â–ˆâ–ˆâ–€ â–ˆâ–ˆ â–„â–ˆ â–„â–„â–„â–ˆ  â–ˆ â–„â–€â–„â–€ â–„â–€â–€â–ˆâ–ˆ
â–ˆâ–ˆâ–€â–ˆâ–€â–€ â–„â–„â–„   â–„ â–ˆâ–ˆ  â–€â–„ â–ˆâ–€â–„â–ˆ â–„â–„â–„  â–€â–€â–„â–€â–ˆâ–ˆ â–„â–„â–€â–„  â–„ â–„â–„â–„  â–ˆâ–€â–„â–ˆâ–ˆ
â–ˆâ–ˆâ–€â–„â–„â–ˆ â–ˆâ–„â–ˆ â–„â–ˆâ–€â–€ â–ˆ â–„â–ˆ â–€ â–„â–€  â–ˆâ–„â–ˆ â–ˆ  â–€â–ˆâ–€â–€â–ˆ   â–ˆâ–ˆâ–ˆâ–„ â–ˆâ–„â–ˆ  â–€â–ˆâ–€â–ˆâ–ˆ
â–ˆâ–ˆâ–„â–ˆ â–ˆ â–„â–„  â–„â–€â–„â–€â–„â–ˆâ–ˆâ–„   â–„â–€â–ˆ â–„â–„  â–„ â–€ â–ˆ â–„â–€  â–ˆâ–€â–€â–€â–€â–€â–„    â–€â–„ â–€â–ˆâ–ˆ
â–ˆâ–ˆâ–„ â–ˆâ–€ â–€â–„â–„â–„â–€â–ˆâ–ˆâ–ˆ â–„ â–ˆ â–„â–ˆâ–„â–„â–ˆ â–€ â–ˆ â–„ â–€â–ˆâ–ˆ â–ˆâ–„ â–„ â–€â–ˆâ–„â–€â–„ â–ˆâ–„â–ˆâ–„ â–„â–ˆâ–„â–ˆâ–ˆ
â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ â–€â–€â–„â–€â–€  â–ˆâ–ˆâ–€â–€â–ˆâ–€â–€â–„â–€ â–€â–ˆ â–€â–„â–ˆâ–€â–ˆâ–„â–€â–„â–ˆâ–€â–€  â–ˆâ–€â–ˆâ–ˆâ–€â–€â–ˆâ–„â–€â–„â–ˆâ–€â–ˆâ–ˆâ–„â–€â–ˆâ–ˆ
â–ˆâ–ˆ â–€ â–ˆâ–€ â–„â–ˆâ–„â–„ â–€  â–€â–ˆâ–ˆâ–ˆâ–„â–ˆâ–€â–„â–ˆâ–ˆâ–€â–€â–€ â–„ â–€â–ˆâ–„â–„â–€â–€â–„ â–„â–„â–€  â–ˆ â–„â–€ â–„â–€â–„â–ˆâ–€â–ˆâ–ˆ
â–ˆâ–ˆâ–„ â–„â–„â–€ â–„â–„ â–€â–ˆâ–„â–€â–€  â–„â–€  â–„  â–„â–„â–ˆâ–„â–€â–ˆâ–„ â–ˆâ–„â–ˆâ–„â–ˆ â–„â–„â–€â–„â–€ â–„ â–€â–„â–€ â–€   â–ˆâ–ˆ
â–ˆâ–ˆâ–„â–„â–„â–€â–ˆâ–€â–„â–€â–€â–„â–ˆâ–„â–„â–„â–„â–„  â–€â–„â–€â–ˆâ–€â–ˆâ–„â–€â–„  â–„â–ˆâ–„â–„â–€ â–„â–„â–„â–„ â–ˆâ–ˆ â–„â–ˆâ–€â–€â–ˆ  â–€â–€â–ˆâ–ˆâ–ˆ
â–ˆâ–ˆâ–€â–„â–€ â–€â–ˆâ–„â–ˆâ–„ â–„â–€â–€â–„â–„ â–€â–ˆ  â–ˆâ–€â–ˆâ–ˆâ–ˆâ–ˆâ–€  â–€  â–ˆ â–ˆ â–„ â–ˆ â–ˆ â–€â–€â–€â–€ â–„â–€â–ˆâ–ˆâ–€ â–ˆâ–ˆ
â–ˆâ–ˆâ–„ â–€â–„â–„â–„â–„â–ˆâ–„â–ˆâ–„ â–„â–ˆ  â–€â–„â–„ â–ˆ â–ˆâ–„â–€â–ˆ â–ˆâ–ˆâ–„ â–„ â–„â–„â–ˆâ–„ â–„â–€â–„â–„â–ˆâ–ˆ â–€ â–€â–€ â–ˆ â–„â–ˆâ–ˆ
â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–„â–ˆâ–ˆâ–„â–ˆ â–„â–€â–„â–€â–ˆâ–„ â–€â–€â–„ â–€ â–ˆâ–„ â–„â–„â–„ â–€ â–€â–€ â–€â–„â–„â–€ â–ˆâ–€â–€â–€â–€ â–„â–„â–„ â–€ â–„â–„â–ˆâ–ˆ
â–ˆâ–ˆ â–„â–„â–„â–„â–„ â–ˆ â–ˆâ–€â–„â–ˆâ–€ â–ˆâ–„â–„â–ˆâ–„â–€ â–€  â–ˆâ–„â–ˆ â–€â–„â–„â–„â–„â–€â–€â–ˆâ–€  â–„â–„â–ˆ  â–ˆâ–„â–ˆ â–€â–ˆâ–€â–€â–ˆâ–ˆ
â–ˆâ–ˆ â–ˆ   â–ˆ â–ˆâ–ˆâ–€â–€â–€â–ˆ â–ˆâ–ˆâ–„â–ˆâ–€ â–„â–ˆ  â–„â–„â–„ â–„  â–ˆ â–€â–„â–€â–„â–€â–ˆâ–€â–„  â–„ â–„â–„ â–„  â–€â–„â–ˆâ–ˆ
â–ˆâ–ˆ â–ˆâ–„â–„â–„â–ˆ â–ˆâ–€â–€â–„â–ˆâ–ˆâ–„â–€â–ˆâ–€â–€â–„â–„â–„â–ˆâ–ˆ â–ˆâ–ˆâ–„â–„â–€â–„â–€ â–ˆâ–ˆ   â–ˆâ–„â–„â–€â–ˆâ–€â–„â–ˆâ–€â–€â–€â–„â–€ â–ˆ â–ˆâ–ˆ
â–ˆâ–ˆâ–„â–„â–„â–„â–„â–„â–„â–ˆâ–„â–ˆâ–„â–ˆâ–„â–„â–ˆâ–ˆâ–„â–ˆâ–„â–„â–ˆâ–ˆâ–ˆâ–„â–„â–„â–„â–ˆâ–ˆâ–„â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–„â–„â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–„â–ˆâ–„â–„â–„â–„â–ˆâ–„â–ˆâ–ˆâ–ˆâ–ˆ
â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€

**Comment by Auties00** [comment]
> With the default configuration I get this on the console and not the QR: â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ â–ˆâ–ˆ â–„â–„â–„â–„â–„ â–ˆâ–ˆ â–„ â–€â–ˆâ–„ â–„â–„â–€â–€ â–€â–€ â–„ â–„ â–ˆâ–€â–„ â–„â–ˆâ–„â–€â–€â–ˆ â–„ â–€â–ˆâ–ˆ â–„â–„â–„â–„â–„ â–ˆâ–ˆ â–ˆâ–ˆ â–ˆ â–ˆ â–ˆâ–€ â–„â–„â–„ â–„â–ˆ â–ˆ â–€â–„ â–„â–€â–€â–€â–„ â–„ â–€â–„â–ˆâ–€â–ˆâ–„ â–€â–€â–€â–„â–€â–ˆ â–ˆ â–ˆ â–ˆâ–ˆ â–ˆâ–ˆ â–ˆâ–„â–„â–„â–ˆ â–ˆâ–„â–„â–€ â–„â–€â–€â–€â–€â–„ â–„â–€â–„â–€â–„ â–„â–„â–„ â–„â–„â–ˆâ–ˆâ–€â–ˆâ–ˆ â–ˆâ–„â–„â–„ â–ˆâ–ˆâ–ˆ â–ˆâ–„â–„â–„â–ˆ â–ˆâ–ˆ â–ˆâ–ˆâ–„â–„â–„â–„â–„â–„â–„â–ˆâ–„â–€â–„â–ˆâ–„â–ˆ â–€â–„â–€ â–€ â–ˆâ–„â–ˆ â–ˆâ–„â–ˆ â–ˆâ–„â–€â–„â–ˆ â–€â–„â–ˆ â–ˆâ–„â–€ â–ˆâ–„â–ˆâ–„â–„â–„â–„â–„â–„â–„â–ˆâ–ˆ â–ˆâ–ˆâ–„ â–€â–ˆâ–ˆâ–„â–„ â–ˆâ–„â–ˆâ–ˆâ–„â–„ â–ˆâ–„ â–„ â–€â–€â–€â–„ â–„ â–„â–ˆâ–€â–€â–„â–„â–€ â–€â–ˆ â–„ â–€â–€â–ˆ â–„â–€â–ˆâ–€â–ˆâ–ˆ â–ˆâ–ˆâ–€â–„â–ˆâ–„ â–€â–„â–ˆâ–„â–„ â–€â–„ â–ˆâ–ˆâ–ˆâ–„â–€â–ˆ â–€â–ˆâ–ˆâ–ˆâ–ˆ â–€â–„â–ˆâ–„â–„â–ˆâ–„â–€â–ˆâ–€â–€ â–ˆâ–„â–„â–ˆâ–€â–ˆâ–ˆâ–„â–€â–ˆâ–ˆâ–ˆ â–ˆâ–ˆâ–€â–ˆâ–ˆ â–€â–„â–„â–€â–€â–ˆâ–€â–ˆâ–„â–€ â–€â–„â–ˆ â–„â–ˆ â–€ â–€â–„â–€â–€ â–€â–„â–€â–ˆâ–€ â–€â–ˆ â–„â–ˆâ–€â–€â–„ â–ˆâ–€ â–„â–ˆ â–€â–ˆâ–ˆ â–ˆâ–ˆâ–ˆ â–€â–„ â–€â–„ â–„â–„ â–€â–ˆâ–€â–€â–„â–„â–„â–€â–ˆâ–ˆ â–€â–ˆâ–€ â–€â–ˆâ–€ â–€â–ˆâ–ˆ â–ˆâ–„ â–€â–ˆâ–„ â–€â–„â–€â–„â–ˆâ–€â–„â–„â–€ â–€â–ˆâ–ˆ â–ˆâ–ˆâ–ˆ â–ˆâ–€â–„â–€â–„ â–„â–€â–ˆâ–„â–€â–€â–ˆâ–ˆâ–ˆ â–€â–ˆâ–€â–€ â–„ â–ˆâ–€â–€ â–„â–€â–€â–„â–„ â–ˆâ–ˆâ–€ â–€â–„â–„ â–„ â–„â–ˆ â–„â–„â–ˆâ–ˆ â–ˆâ–ˆâ–ˆ â–ˆâ–ˆ â–„â–ˆ â–ˆâ–„â–€â–€ â–ˆâ–„â–€ â–ˆ â–„â–€ â–€â–€â–ˆâ–ˆ â–„â–„ â–€â–ˆ â–€â–ˆâ–ˆâ–„â–„â–€ â–€ â–€ â–ˆ â–„â–€â–ˆâ–€â–„â–ˆâ–ˆ â–ˆâ–ˆâ–€â–„â–„â–„â–ˆ â–„â–€â–„â–„â–„â–ˆâ–€ â–€ â–€ â–ˆâ–„ â–ˆâ–€â–€â–ˆâ–€â–€ â–ˆâ–€â–€â–„ â–„ â–€â–ˆ â–€ â–€ â–€â–„ â–€â–ˆâ–„â–ˆâ–ˆâ–ˆ â–ˆâ–ˆâ–ˆ â–„â–„â–ˆâ–„ â–€â–€â–„â–„ â–„ â–„â–€ â–€â–„â–ˆâ–€â–„â–€ â–„â–ˆâ–ˆâ–€ â–ˆâ–ˆ â–„â–ˆ â–„â–„â–„â–ˆ â–ˆ â–„â–€â–„â–€ â–„â–€â–€â–ˆâ–ˆ â–ˆâ–ˆâ–€â–ˆâ–€â–€ â–„â–„â–„ â–„ â–ˆâ–ˆ â–€â–„ â–ˆâ–€â–„â–ˆ â–„â–„â–„ â–€â–€â–„â–€â–ˆâ–ˆ â–„â–„â–€â–„ â–„ â–„â–„â–„ â–ˆâ–€â–„â–ˆâ–ˆ â–ˆâ–ˆâ–€â–„â–„â–ˆ â–ˆâ–„â–ˆ â–„â–ˆâ–€â–€ â–ˆ â–„â–ˆ â–€ â–„â–€ â–ˆâ–„â–ˆ â–ˆ â–€â–ˆâ–€â–€â–ˆ â–ˆâ–ˆâ–ˆâ–„ â–ˆâ–„â–ˆ â–€â–ˆâ–€â–ˆâ–ˆ â–ˆâ–ˆâ–„â–ˆ â–ˆ â–„â–„ â–„â–€â–„â–€â–„â–ˆâ–ˆâ–„ â–„â–€â–ˆ â–„â–„ â–„ â–€ â–ˆ â–„â–€ â–ˆâ–€â–€â–€â–€â–€â–„ â–€â–„ â–€â–ˆâ–ˆ â–ˆâ–ˆâ–„ â–ˆâ–€ â–€â–„â–„â–„â–€â–ˆâ–ˆâ–ˆ â–„ â–ˆ â–„â–ˆâ–„â–„â–ˆ â–€ â–ˆ â–„ â–€â–ˆâ–ˆ â–ˆâ–„ â–„ â–€â–ˆâ–„â–€â–„ â–ˆâ–„â–ˆâ–„ â–„â–ˆâ–„â–ˆâ–ˆ â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ â–€â–€â–„â–€â–€ â–ˆâ–ˆâ–€â–€â–ˆâ–€â–€â–„â–€ â–€â–ˆ â–€â–„â–ˆâ–€â–ˆâ–„â–€â–„â–ˆâ–€â–€ â–ˆâ–€â–ˆâ–ˆâ–€â–€â–ˆâ–„â–€â–„â–ˆâ–€â–ˆâ–ˆâ–„â–€â–ˆâ–ˆ â–ˆâ–ˆ â–€ â–ˆâ–€ â–„â–ˆâ–„â–„ â–€ â–€â–ˆâ–ˆâ–ˆâ–„â–ˆâ–€â–„â–ˆâ–ˆâ–€â–€â–€ â–„ â–€â–ˆâ–„â–„â–€â–€â–„ â–„â–„â–€ â–ˆ â–„â–€ â–„â–€â–„â–ˆâ–€â–ˆâ–ˆ â–ˆâ–ˆâ–„ â–„â–„â–€ â–„â–„ â–€â–ˆâ–„â–€â–€ â–„â–€ â–„ â–„â–„â–ˆâ–„â–€â–ˆâ–„ â–ˆâ–„â–ˆâ–„â–ˆ â–„â–„â–€â–„â–€ â–„ â–€â–„â–€ â–€ â–ˆâ–ˆ â–ˆâ–ˆâ–„â–„â–„â–€â–ˆâ–€â–„â–€â–€â–„â–ˆâ–„â–„â–„â–„â–„ â–€â–„â–€â–ˆâ–€â–ˆâ–„â–€â–„ â–„â–ˆâ–„â–„â–€ â–„â–„â–„â–„ â–ˆâ–ˆ â–„â–ˆâ–€â–€â–ˆ â–€â–€â–ˆâ–ˆâ–ˆ â–ˆâ–ˆâ–€â–„â–€ â–€â–ˆâ–„â–ˆâ–„ â–„â–€â–€â–„â–„ â–€â–ˆ â–ˆâ–€â–ˆâ–ˆâ–ˆâ–ˆâ–€ â–€ â–ˆ â–ˆ â–„ â–ˆ â–ˆ â–€â–€â–€â–€ â–„â–€â–ˆâ–ˆâ–€ â–ˆâ–ˆ â–ˆâ–ˆâ–„ â–€â–„â–„â–„â–„â–ˆâ–„â–ˆâ–„ â–„â–ˆ â–€â–„â–„ â–ˆ â–ˆâ–„â–€â–ˆ â–ˆâ–ˆâ–„ â–„ â–„â–„â–ˆâ–„ â–„â–€â–„â–„â–ˆâ–ˆ â–€ â–€â–€ â–ˆ â–„â–ˆâ–ˆ â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–„â–ˆâ–ˆâ–„â–ˆ â–„â–€â–„â–€â–ˆâ–„ â–€â–€â–„ â–€ â–ˆâ–„ â–„â–„â–„ â–€ â–€â–€ â–€â–„â–„â–€ â–ˆâ–€â–€â–€â–€ â–„â–„â–„ â–€ â–„â–„â–ˆâ–ˆ â–ˆâ–ˆ â–„â–„â–„â–„â–„ â–ˆ â–ˆâ–€â–„â–ˆâ–€ â–ˆâ–„â–„â–ˆâ–„â–€ â–€ â–ˆâ–„â–ˆ â–€â–„â–„â–„â–„â–€â–€â–ˆâ–€ â–„â–„â–ˆ â–ˆâ–„â–ˆ â–€â–ˆâ–€â–€â–ˆâ–ˆ â–ˆâ–ˆ â–ˆ â–ˆ â–ˆâ–ˆâ–€â–€â–€â–ˆ â–ˆâ–ˆâ–„â–ˆâ–€ â–„â–ˆ â–„â–„â–„ â–„ â–ˆ â–€â–„â–€â–„â–€â–ˆâ–€â–„ â–„ â–„â–„ â–„ â–€â–„â–ˆâ–ˆ â–ˆâ–ˆ â–ˆâ–„â–„â–„â–ˆ â–ˆâ–€â–€â–„â–ˆâ–ˆâ–„â–€â–ˆâ–€â–€â–„â–„â–„â–ˆâ–ˆ â–ˆâ–ˆâ–„â–„â–€â–„â–€ â–ˆâ–ˆ â–ˆâ–„â–„â–€â–ˆâ–€â–„â–ˆâ–€â–€â–€â–„â–€ â–ˆ â–ˆâ–ˆ â–ˆâ–ˆâ–„â–„â–„â–„â–„â–„â–„â–ˆâ–„â–ˆâ–„â–ˆâ–„â–„â–ˆâ–ˆâ–„â–ˆâ–„â–„â–ˆâ–ˆâ–ˆâ–„â–„â–„â–„â–ˆâ–ˆâ–„â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–„â–„â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–„â–ˆâ–„â–„â–„â–„â–ˆâ–„â–ˆâ–ˆâ–ˆâ–ˆ â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€

Already fixed, use RC26
