### ISSUE TITLE
maven cannot download jars

### ISSUE THREAD

**Issue by zhengshengjie666** [Auties00/WhatsappWeb4j#182]
hi，dear Auties00
Could not find artifact com.github.auties00:protobuf-base:pom:1.17 in central (https://repo.maven.apache.org/maven2)
Could not find artifact com.github.auties00:protobuf-serializer:pom:1.17 in central (https://repo.maven.apache.org/maven2)
Could not find artifact com.github.auties00:qr-terminal:pom:2.2 in central (https://repo.maven.apache.org/maven2)

**Comment by Auties00** [comment]
> hi，dear Auties00 Could not find artifact com.github.auties00:protobuf-base:pom:1.17 in central (https://repo.maven.apache.org/maven2) Could not find artifact com.github.auties00:protobuf-serializer:pom:1.17 in central (https://repo.maven.apache.org/maven2) Could not find artifact com.github.auties00:qr-terminal:pom:2.2 in central (https://repo.maven.apache.org/maven2)

Don't use the latest commit, use the release that is out
