### ISSUE TITLE
3.0-RC27 not available in repo (dependency cannot be resolved in gradle)

### ISSUE THREAD

**Issue by xNoobyyy** [Auties00/WhatsappWeb4j#183]

**Comment by Auties00** [comment]
Can you show the error?

**Comment by xNoobyyy** [comment]
Well I mean, there just is no RC27 although it says it in the README.md ..

![image](https://user-images.githubusercontent.com/71840441/196223078-e1dd1b24-1129-45f2-b652-9dab816ef020.png)

**Comment by jdarmetzki** [comment]
protobuf-base, protobuf-serializer and qr-terminal are also unavailable in the required versions.

**Comment by Auties00** [comment]
> protobuf-base, protobuf-serializer and qr-terminal are also unavailable in the required versions when trying to build from source.

Yeah sorry I'm changing a lot of stuff so they are not public yet. they will be by the time I publish a stable release. the only issue left is the message decryption one you can find listed in the pinned issues. once I fix that I'll publish everything

**Comment by Auties00** [comment]
RC28 is now available on maven central for everyone to use!
