### ISSUE TITLE
Runtime Error: java.lang.NoClassDefFoundError: Could not initialize class it.auties.whatsapp.util.JacksonProvider

### ISSUE THREAD

**Issue by micherlinman** [Auties00/WhatsappWeb4j#185]
When I compile a standalone application with the follwing pom it works fine.

>     <build>
>         <plugins>
>             <plugin>
>                 <groupId>org.apache.maven.plugins</groupId>
>                 <artifactId>maven-compiler-plugin</artifactId>
>                 <version>3.3</version>
>                 <configuration>
>                     <source>17</source>
>                     <target>17</target>
>                     <compilerArgs>
>                         --enable-preview
>                     </compilerArgs>
>                 </configuration>
>             </plugin>
>         </plugins>
>     </build>
> 
>     <dependencies>
>         <dependency>
>             <groupId>com.github.auties00</groupId>
>             <artifactId>whatsappweb4j</artifactId>
>             <version>3.0-RC26</version>
>         </dependency>
>     </dependencies>

But I have to use the dependency in an Apache Storm application. There I use the same dependency and same build plugin, but lots of other dependencies from apache storm and some external. I get the following error. I tried to exclude fasterxml.jackson from whatsapp4j but it doesnt help. I get the error in the first line `var api = Whatsapp.firstConnection();` . What is wrong?

> java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: Could not initialize class it.auties.whatsapp.util.JacksonProvider
> 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
> 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
> Caused by: java.lang.NoClassDefFoundError: Could not initialize class it.auties.whatsapp.util.JacksonProvider
> 	at it.auties.whatsapp.util.Preferences.writeObject(Preferences.java:134)
> 	at it.auties.whatsapp.util.Preferences.lambda$writeJson$2(Preferences.java:116)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
> 	... 6 more

**Comment by xNoobyyy** [comment]
#160
