### ISSUE TITLE
BUILD FAILURE 

### ISSUE THREAD

**Issue by gu1llermo** [Auties00/WhatsappWeb4j#186]
-----------------< com.github.auties00:whatsappweb4j >------------------
Building com.github.auties00:whatsappweb4j 3.0-RC27
--------------------------------[ jar ]---------------------------------
The POM for com.github.auties00:protobuf-base:jar:1.17 is missing, no dependency information available
The POM for com.github.auties00:protobuf-serializer:jar:1.17 is missing, no dependency information available
The POM for com.github.auties00:qr-terminal:jar:2.2 is missing, no dependency information available
------------------------------------------------------------------------
BUILD FAILURE

Failed to execute goal on project whatsappweb4j: Could not resolve dependencies for project com.github.auties00:whatsappweb4j:jar:3.0-RC27: The following artifacts could not be resolved: com.github.auties00:protobuf-base:jar:1.17, com.github.auties00:protobuf-serializer:jar:1.17, com.github.auties00:qr-terminal:jar:2.2: com.github.auties00:protobuf-base:jar:1.17 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by xNoobyyy** [comment]
The latest version of qr-terminal is 2.1 and protobuf-base/serializer are not on mavencentral yet. Probably currently only on auties local repository.

**Comment by gu1llermo** [comment]
Thanks, I just cloned the project and couldn't use it because of this error. I don't know what I can do to be able to use it?

**Comment by xNoobyyy** [comment]
> Thanks, I just cloned the project and couldn't use it because of this error. I don't know what I can do to be able to use it?

The only way atm I think, is to go into each of the repositories that are missing on his GitHub and build/import them yourself via local repository

**Comment by Auties00** [comment]
I Will release them when I publish the next version(stable) of the library
