### ISSUE TITLE
Message read status not updating (RC26 & master)

### ISSUE THREAD

**Issue by NeilDuToit92** [Auties00/WhatsappWeb4j#187]
I am trying to achieve 2 things:
1. Figure out which messages have not been read before, I thought this would be possible by using the status, but both have `status=PENDING` - If this is not possible, I can just keep a list of ids to track this.
2. Mark the message so that the person sending it sees the blue tick. I already tried `whatsapp.markRead(chat.jid()).join()` when iterating `whatsapp.store().chats()`, but that just seems to hang indefinitely - should this work in RC26?

These are the messages as sent by the number not linked to the library. As you can see, one with blue ticks that I manually read on the phone and one without that I want to mark from this library:
![image](https://user-images.githubusercontent.com/2218598/200667419-2186c398-5df5-4ec8-a5f1-f9a30e6325b8.png)

Here are the two messages I get by iterating `whatsapp.store().chats().messages()`, but there are no obvious differences between the two:
`MessageInfo(key=MessageKey(chatJid=XXXXXX@s.whatsapp.net, fromMe=false, id=XXXXXXXXX, senderJid=Optional[XXXXXXXXX:5@s.whatsapp.net]), message=TextMessage(super=ContextualMessage(contextInfo=ContextInfo(quotedMessageId=Optional.empty, quotedMessageSenderJid=Optional.empty, quotedMessageSender=Optional.empty, quotedMessage=Optional.empty, quotedMessageChatJid=Optional.empty, quotedMessageChat=Optional.empty, mentions=null, conversionSource=null, conversionData=null, conversionDelaySeconds=0, forwardingScore=0, forwarded=false, quotedAd=null, placeholderKey=null, ephemeralExpiration=0, ephemeralSettingTimestamp=0, ephemeralSharedSecret=null, externalAdReply=null, entryPointConversionSource=null, entryPointConversionApp=null, entryPointConversionDelaySeconds=0, disappearingMode=null, actionLink=null, groupSubject=null, parentGroup=null)), text=This is a test 00001, matchedText=null, canonicalUrl=null, description=null, title=null, textArgb=null, backgroundArgb=null, font=null, previewType=null, thumbnail=null, doNotPlayInline=false), timestamp=1667938366, status=PENDING, individualStatus={}, senderJid=XXXXXXXXX:5@s.whatsapp.net, sender=Optional[Contact(jid=XXXXXXXXX@s.whatsapp.net, chosenName=XXXXXXXXXX, fullName=XXXXXXXXXX, shortName=null, lastKnownPresence=Optional.empty, lastSeen=Optional.empty)], messageC2STimestamp=0, ignore=false, starred=false, broadcast=false, pushName=XXXXXXXXXX, mediaCiphertextSha256=null, multicast=false, urlText=false, urlNumber=false, stubType=null, clearMedia=false, stubParameters=null, duration=0, labels=null, paymentInfo=null, finalLiveLocation=null, quotedPaymentInfo=null, ephemeralStartTimestamp=0, ephemeralDuration=0, enableEphemeral=false, ephemeralOutOfSync=false, businessPrivacyStatus=null, businessVerifiedName=null, mediaData=null, photoChange=null, receipt=null, reactions=null, quotedStickerData=null, futureProofData=null, psaStatus=null)`

`MessageInfo(key=MessageKey(chatJid=XXXXXX@s.whatsapp.net, fromMe=false, id=XXXXXXXXX, senderJid=Optional[XXXXXXXXX:5@s.whatsapp.net]), message=TextMessage(super=ContextualMessage(contextInfo=ContextInfo(quotedMessageId=Optional.empty, quotedMessageSenderJid=Optional.empty, quotedMessageSender=Optional.empty, quotedMessage=Optional.empty, quotedMessageChatJid=Optional.empty, quotedMessageChat=Optional.empty, mentions=null, conversionSource=null, conversionData=null, conversionDelaySeconds=0, forwardingScore=0, forwarded=false, quotedAd=null, placeholderKey=null, ephemeralExpiration=0, ephemeralSettingTimestamp=0, ephemeralSharedSecret=null, externalAdReply=null, entryPointConversionSource=null, entryPointConversionApp=null, entryPointConversionDelaySeconds=0, disappearingMode=null, actionLink=null, groupSubject=null, parentGroup=null)), text=This is a test 00002, matchedText=null, canonicalUrl=null, description=null, title=null, textArgb=null, backgroundArgb=null, font=null, previewType=null, thumbnail=null, doNotPlayInline=false), timestamp=1667938376, status=PENDING, individualStatus={}, senderJid=XXXXXXXXX:5@s.whatsapp.net, sender=Optional[Contact(jid=XXXXXXXXX@s.whatsapp.net, chosenName=XXXXXXXXXX, fullName=XXXXXXXXXX, shortName=null, lastKnownPresence=Optional.empty, lastSeen=Optional.empty)], messageC2STimestamp=0, ignore=false, starred=false, broadcast=false, pushName=XXXXXXXXXX, mediaCiphertextSha256=null, multicast=false, urlText=false, urlNumber=false, stubType=null, clearMedia=false, stubParameters=null, duration=0, labels=null, paymentInfo=null, finalLiveLocation=null, quotedPaymentInfo=null, ephemeralStartTimestamp=0, ephemeralDuration=0, enableEphemeral=false, ephemeralOutOfSync=false, businessPrivacyStatus=null, businessVerifiedName=null, mediaData=null, photoChange=null, receipt=null, reactions=null, quotedStickerData=null, futureProofData=null, psaStatus=null)`

**Comment by Auties00** [comment]
> I am trying to achieve 2 things:
> 
> 1. Figure out which messages have not been read before, I thought this would be possible by using the status, but both have `status=PENDING` - If this is not possible, I can just keep a list of ids to track this.
> 2. Mark the message so that the person sending it sees the blue tick. I already tried `whatsapp.markRead(chat.jid()).join()` when iterating `whatsapp.store().chats()`, but that just seems to hang indefinitely - should this work in RC26?
> 
> These are the messages as sent by the number not linked to the library. As you can see, one with blue ticks that I manually read on the phone and one without that I want to mark from this library: ![image](https://user-images.githubusercontent.com/2218598/200667419-2186c398-5df5-4ec8-a5f1-f9a30e6325b8.png)
> 
> Here are the two messages I get by iterating `whatsapp.store().chats().messages()`, but there are no obvious differences between the two: `MessageInfo(key=MessageKey(chatJid=XXXXXX@s.whatsapp.net, fromMe=false, id=XXXXXXXXX, senderJid=Optional[XXXXXXXXX:5@s.whatsapp.net]), message=TextMessage(super=ContextualMessage(contextInfo=ContextInfo(quotedMessageId=Optional.empty, quotedMessageSenderJid=Optional.empty, quotedMessageSender=Optional.empty, quotedMessage=Optional.empty, quotedMessageChatJid=Optional.empty, quotedMessageChat=Optional.empty, mentions=null, conversionSource=null, conversionData=null, conversionDelaySeconds=0, forwardingScore=0, forwarded=false, quotedAd=null, placeholderKey=null, ephemeralExpiration=0, ephemeralSettingTimestamp=0, ephemeralSharedSecret=null, externalAdReply=null, entryPointConversionSource=null, entryPointConversionApp=null, entryPointConversionDelaySeconds=0, disappearingMode=null, actionLink=null, groupSubject=null, parentGroup=null)), text=This is a test 00001, matchedText=null, canonicalUrl=null, description=null, title=null, textArgb=null, backgroundArgb=null, font=null, previewType=null, thumbnail=null, doNotPlayInline=false), timestamp=1667938366, status=PENDING, individualStatus={}, senderJid=XXXXXXXXX:5@s.whatsapp.net, sender=Optional[Contact(jid=XXXXXXXXX@s.whatsapp.net, chosenName=XXXXXXXXXX, fullName=XXXXXXXXXX, shortName=null, lastKnownPresence=Optional.empty, lastSeen=Optional.empty)], messageC2STimestamp=0, ignore=false, starred=false, broadcast=false, pushName=XXXXXXXXXX, mediaCiphertextSha256=null, multicast=false, urlText=false, urlNumber=false, stubType=null, clearMedia=false, stubParameters=null, duration=0, labels=null, paymentInfo=null, finalLiveLocation=null, quotedPaymentInfo=null, ephemeralStartTimestamp=0, ephemeralDuration=0, enableEphemeral=false, ephemeralOutOfSync=false, businessPrivacyStatus=null, businessVerifiedName=null, mediaData=null, photoChange=null, receipt=null, reactions=null, quotedStickerData=null, futureProofData=null, psaStatus=null)`
> 
> `MessageInfo(key=MessageKey(chatJid=XXXXXX@s.whatsapp.net, fromMe=false, id=XXXXXXXXX, senderJid=Optional[XXXXXXXXX:5@s.whatsapp.net]), message=TextMessage(super=ContextualMessage(contextInfo=ContextInfo(quotedMessageId=Optional.empty, quotedMessageSenderJid=Optional.empty, quotedMessageSender=Optional.empty, quotedMessage=Optional.empty, quotedMessageChatJid=Optional.empty, quotedMessageChat=Optional.empty, mentions=null, conversionSource=null, conversionData=null, conversionDelaySeconds=0, forwardingScore=0, forwarded=false, quotedAd=null, placeholderKey=null, ephemeralExpiration=0, ephemeralSettingTimestamp=0, ephemeralSharedSecret=null, externalAdReply=null, entryPointConversionSource=null, entryPointConversionApp=null, entryPointConversionDelaySeconds=0, disappearingMode=null, actionLink=null, groupSubject=null, parentGroup=null)), text=This is a test 00002, matchedText=null, canonicalUrl=null, description=null, title=null, textArgb=null, backgroundArgb=null, font=null, previewType=null, thumbnail=null, doNotPlayInline=false), timestamp=1667938376, status=PENDING, individualStatus={}, senderJid=XXXXXXXXX:5@s.whatsapp.net, sender=Optional[Contact(jid=XXXXXXXXX@s.whatsapp.net, chosenName=XXXXXXXXXX, fullName=XXXXXXXXXX, shortName=null, lastKnownPresence=Optional.empty, lastSeen=Optional.empty)], messageC2STimestamp=0, ignore=false, starred=false, broadcast=false, pushName=XXXXXXXXXX, mediaCiphertextSha256=null, multicast=false, urlText=false, urlNumber=false, stubType=null, clearMedia=false, stubParameters=null, duration=0, labels=null, paymentInfo=null, finalLiveLocation=null, quotedPaymentInfo=null, ephemeralStartTimestamp=0, ephemeralDuration=0, enableEphemeral=false, ephemeralOutOfSync=false, businessPrivacyStatus=null, businessVerifiedName=null, mediaData=null, photoChange=null, receipt=null, reactions=null, quotedStickerData=null, futureProofData=null, psaStatus=null)`

Can you try using the latest commit? Clone the repo and run mvn install than reference if from your project.

**Comment by NeilDuToit92** [comment]
Using the latest master branch, I am still not able to get it to mark the message to go to blue ticks.

Message sent `00007` (After the below has executed)
![image](https://user-images.githubusercontent.com/2218598/200903411-d2c6c590-cbcf-4f82-94e5-160efcdbe7c3.png)

My listener:
```
  @Override
  public void onNewMessage(Whatsapp whatsapp, MessageInfo info) {
    if (!(info.message().content() instanceof TextMessage textMessage)) {
      return;
    }
    System.out.println("Message Received: " + textMessage.text());
    var markStatus = whatsapp.markRead(info.chat()).join();
    System.out.println("markStatus: " + markStatus);
  }
  
  @Override
  public void onAction(Action action) {
    System.out.println("--------- onAction ---------");
    System.out.println(action);
  }
```

Logs:
```
Message Received: This is a test 00007
--------- onAction ---------
MarkChatAsReadAction(read=true, messageRange=ActionMessageRangeSync(lastMessageTimestamp=1668015886, lastSystemMessageTimestamp=null, messages=[SyncActionMessage(key=MessageKey(chatJid=XXXXXXXXXXXX:5@s.whatsapp.net, fromMe=false, id=3EB064B302F380494145, senderJid=Optional[XXXXXXXXXXXX@s.whatsapp.net]), timestamp=1668015886)]))
markStatus: Chat(jid=XXXXXXXXXXXX@s.whatsapp.net, messages=[MessageInfo(key=MessageKey(chatJid=XXXXXXXXXXXX@s.whatsapp.net, fromMe=false, id=3EB00B91A759E1881AA1, senderJid=Optional.empty), message=TextMessage(super=ContextualMessage(contextInfo=ContextInfo(quotedMessageId=Optional.empty, quotedMessageSenderJid=Optional.empty, quotedMessageSender=Optional.empty, quotedMessage=Optional.empty, quotedMessageChatJid=Optional.empty, quotedMessageChat=Optional.empty, mentions=null, conversionSource=null, conversionData=null, conversionDelaySeconds=0, forwardingScore=0, forwarded=false, quotedAd=null, placeholderKey=null, ephemeralExpiration=0, ephemeralSettingTimestamp=0, ephemeralSharedSecret=null, externalAdReply=null, entryPointConversionSource=null, entryPointConversionApp=null, entryPointConversionDelaySeconds=0, disappearingMode=null, actionLink=null, groupSubject=null, parentGroup=null)), text=This is a test 00004, matchedText=null, canonicalUrl=null, description=null, title=null, textArgb=null, backgroundArgb=null, font=null, previewType=null, thumbnail=null, doNotPlayInline=false), timestamp=1668015257, status=PENDING, individualStatus={}, senderJid=XXXXXXXXXXXX@s.whatsapp.net, sender=Optional.empty, messageC2STimestamp=0, ignore=false, starred=false, broadcast=false, pushName=null, mediaCiphertextSha256=null, multicast=false, urlText=false, urlNumber=false, stubType=null, clearMedia=false, stubParameters=null, duration=0, labels=null, paymentInfo=null, finalLiveLocation=null, quotedPaymentInfo=null, ephemeralStartTimestamp=0, ephemeralDuration=0, enableEphemeral=false, ephemeralOutOfSync=false, businessPrivacyStatus=null, businessVerifiedName=null, mediaData=null, photoChange=null, receipt=null, reactions=null, quotedStickerData=null, futureProofData=null, psaStatus=null), MessageInfo(key=MessageKey(chatJid=XXXXXXXXXXXX@s.whatsapp.net, fromMe=false, id=3EB0D9B47AF04B2B233A, senderJid=Optional.empty), message=TextMessage(super=ContextualMessage(contextInfo=ContextInfo(quotedMessageId=Optional.empty, quotedMessageSenderJid=Optional.empty, quotedMessageSender=Optional.empty, quotedMessage=Optional.empty, quotedMessageChatJid=Optional.empty, quotedMessageChat=Optional.empty, mentions=null, conversionSource=null, conversionData=null, conversionDelaySeconds=0, forwardingScore=0, forwarded=false, quotedAd=null, placeholderKey=null, ephemeralExpiration=0, ephemeralSettingTimestamp=0, ephemeralSharedSecret=null, externalAdReply=null, entryPointConversionSource=null, entryPointConversionApp=null, entryPointConversionDelaySeconds=0, disappearingMode=null, actionLink=null, groupSubject=null, parentGroup=null)), text=This is a test 00003, matchedText=null, canonicalUrl=null, description=null, title=null, textArgb=null, backgroundArgb=null, font=null, previewType=null, thumbnail=null, doNotPlayInline=false), timestamp=1667939280, status=PENDING, individualStatus={}, senderJid=XXXXXXXXXXXX@s.whatsapp.net, sender=Optional.empty, messageC2STimestamp=0, ignore=false, starred=false, broadcast=false, pushName=null, mediaCiphertextSha256=null, multicast=false, urlText=false, urlNumber=false, stubType=null, clearMedia=false, stubParameters=null, duration=0, labels=null, paymentInfo=null, finalLiveLocation=null, quotedPaymentInfo=null, ephemeralStartTimestamp=0, ephemeralDuration=0, enableEphemeral=false, ephemeralOutOfSync=false, businessPrivacyStatus=null, businessVerifiedName=null, mediaData=null, photoChange=null, receipt=null, reactions=null, quotedStickerData=null, futureProofData=null, psaStatus=null), MessageInfo(key=MessageKey(chatJid=XXXXXXXXXXXX@s.whatsapp.net, fromMe=false, id=3EB08F2D5EAAF45E47FC, senderJid=Optional.empty), message=TextMessage(super=ContextualMessage(contextInfo=ContextInfo(quotedMessageId=Optional.empty, quotedMessageSenderJid=Optional.empty, quotedMessageSender=Optional.empty, quotedMessage=Optional.empty, quotedMessageChatJid=Optional.empty, quotedMessageChat=Optional.empty, mentions=null, conversionSource=null, conversionData=null, conversionDelaySeconds=0, forwardingScore=0, forwarded=false, quotedAd=null, placeholderKey=null, ephemeralExpiration=0, ephemeralSettingTimestamp=0, ephemeralSharedSecret=null, externalAdReply=null, entryPointConversionSource=null, entryPointConversionApp=null, entryPointConversionDelaySeconds=0, disappearingMode=null, actionLink=null, groupSubject=null, parentGroup=null)), text=This is a test 00002, matchedText=null, canonicalUrl=null, description=null, title=null, textArgb=null, backgroundArgb=null, font=null, previewType=null, thumbnail=null, doNotPlayInline=false), timestamp=1667938376, status=PENDING, individualStatus={}, senderJid=XXXXXXXXXXXX@s.whatsapp.net, sender=Optional.empty, messageC2STimestamp=0, ignore=false, starred=false, broadcast=false, pushName=null, mediaCiphertextSha256=null, multicast=false, urlText=false, urlNumber=false, stubType=null, clearMedia=false, stubParameters=null, duration=0, labels=null, paymentInfo=null, finalLiveLocation=null, quotedPaymentInfo=null, ephemeralStartTimestamp=0, ephemeralDuration=0, enableEphemeral=false, ephemeralOutOfSync=false, businessPrivacyStatus=null, businessVerifiedName=null, mediaData=null, photoChange=null, receipt=null, reactions=null, quotedStickerData=null, futureProofData=null, psaStatus=null), MessageInfo(key=MessageKey(chatJid=XXXXXXXXXXXX@s.whatsapp.net, fromMe=false, id=3EB00F4FDB9E703AB089, senderJid=Optional.empty), message=TextMessage(super=ContextualMessage(contextInfo=ContextInfo(quotedMessageId=Optional.empty, quotedMessageSenderJid=Optional.empty, quotedMessageSender=Optional.empty, quotedMessage=Optional.empty, quotedMessageChatJid=Optional.empty, quotedMessageChat=Optional.empty, mentions=null, conversionSource=null, conversionData=null, conversionDelaySeconds=0, forwardingScore=0, forwarded=false, quotedAd=null, placeholderKey=null, ephemeralExpiration=0, ephemeralSettingTimestamp=0, ephemeralSharedSecret=null, externalAdReply=null, entryPointConversionSource=null, entryPointConversionApp=null, entryPointConversionDelaySeconds=0, disappearingMode=null, actionLink=null, groupSubject=null, parentGroup=null)), text=This is a test 00001, matchedText=null, canonicalUrl=null, description=null, title=null, textArgb=null, backgroundArgb=null, font=null, previewType=null, thumbnail=null, doNotPlayInline=false), timestamp=1667938366, status=PENDING, individualStatus={}, senderJid=XXXXXXXXXXXX@s.whatsapp.net, sender=Optional.empty, messageC2STimestamp=0, ignore=false, starred=false, broadcast=false, pushName=null, mediaCiphertextSha256=null, multicast=false, urlText=false, urlNumber=false, stubType=null, clearMedia=false, stubParameters=null, duration=0, labels=null, paymentInfo=null, finalLiveLocation=null, quotedPaymentInfo=null, ephemeralStartTimestamp=0, ephemeralDuration=0, enableEphemeral=false, ephemeralOutOfSync=false, businessPrivacyStatus=null, businessVerifiedName=null, mediaData=null, photoChange=null, receipt=null, reactions=null, quotedStickerData=null, futureProofData=null, psaStatus=null), MessageInfo(key=MessageKey(chatJid=XXXXXXXXXXXX@s.whatsapp.net, fromMe=false, id=3EB0EF5DF935FDC2F648, senderJid=Optional.empty), message=TextMessage(super=ContextualMessage(contextInfo=ContextInfo(quotedMessageId=Optional.empty, quotedMessageSenderJid=Optional.empty, quotedMessageSender=Optional.empty, quotedMessage=Optional.empty, quotedMessageChatJid=Optional.empty, quotedMessageChat=Optional.empty, mentions=null, conversionSource=null, conversionData=null, conversionDelaySeconds=0, forwardingScore=0, forwarded=false, quotedAd=null, placeholderKey=null, ephemeralExpiration=0, ephemeralSettingTimestamp=0, ephemeralSharedSecret=null, externalAdReply=null, entryPointConversionSource=null, entryPointConversionApp=null, entryPointConversionDelaySeconds=0, disappearingMode=null, actionLink=null, groupSubject=null, parentGroup=null)), text=This is a test 1, matchedText=null, canonicalUrl=null, description=null, title=null, textArgb=null, backgroundArgb=null, font=null, previewType=null, thumbnail=null, doNotPlayInline=false), timestamp=1667938356, status=PENDING, individualStatus={}, senderJid=XXXXXXXXXXXX@s.whatsapp.net, sender=Optional.empty, messageC2STimestamp=0, ignore=false, starred=false, broadcast=false, pushName=null, mediaCiphertextSha256=null, multicast=false, urlText=false, urlNumber=false, stubType=null, clearMedia=false, stubParameters=null, duration=0, labels=null, paymentInfo=null, finalLiveLocation=null, quotedPaymentInfo=null, ephemeralStartTimestamp=0, ephemeralDuration=0, enableEphemeral=false, ephemeralOutOfSync=false, businessPrivacyStatus=null, businessVerifiedName=null, mediaData=null, photoChange=null, receipt=null, reactions=null, quotedStickerData=null, futureProofData=null, psaStatus=null), MessageInfo(key=MessageKey(chatJid=XXXXXXXXXXXX@s.whatsapp.net, fromMe=false, id=3EB06910480AD7B13A27, senderJid=Optional.empty), message=TextMessage(super=ContextualMessage(contextInfo=ContextInfo(quotedMessageId=Optional.empty, quotedMessageSenderJid=Optional.empty, quotedMessageSender=Optional.empty, quotedMessage=Optional.empty, quotedMessageChatJid=Optional.empty, quotedMessageChat=Optional.empty, mentions=null, conversionSource=null, conversionData=null, conversionDelaySeconds=0, forwardingScore=0, forwarded=false, quotedAd=null, placeholderKey=null, ephemeralExpiration=0, ephemeralSettingTimestamp=0, ephemeralSharedSecret=null, externalAdReply=null, entryPointConversionSource=null, entryPointConversionApp=null, entryPointConversionDelaySeconds=0, disappearingMode=null, actionLink=null, groupSubject=null, parentGroup=null)), text=This is a test, matchedText=null, canonicalUrl=null, description=null, title=null, textArgb=null, backgroundArgb=null, font=null, previewType=null, thumbnail=null, doNotPlayInline=false), timestamp=1667938336, status=PENDING, individualStatus={}, senderJid=XXXXXXXXXXXX@s.whatsapp.net, sender=Optional.empty, messageC2STimestamp=0, ignore=false, starred=false, broadcast=false, pushName=null, mediaCiphertextSha256=null, multicast=false, urlText=false, urlNumber=false, stubType=null, clearMedia=false, stubParameters=null, duration=0, labels=null, paymentInfo=null, finalLiveLocation=null, quotedPaymentInfo=null, ephemeralStartTimestamp=0, ephemeralDuration=0, enableEphemeral=false, ephemeralOutOfSync=false, businessPrivacyStatus=null, businessVerifiedName=null, mediaData=null, photoChange=null, receipt=null, reactions=null, quotedStickerData=null, futureProofData=null, psaStatus=null), MessageInfo(key=MessageKey(chatJid=XXXXXXXXXXXX:5@s.whatsapp.net, fromMe=false, id=3EB04D6D340FC1D0DE76, senderJid=Optional[XXXXXXXXXXXX:5@s.whatsapp.net]), message=TextMessage(super=ContextualMessage(contextInfo=ContextInfo(quotedMessageId=Optional.empty, quotedMessageSenderJid=Optional.empty, quotedMessageSender=Optional.empty, quotedMessage=Optional.empty, quotedMessageChatJid=Optional.empty, quotedMessageChat=Optional.empty, mentions=null, conversionSource=null, conversionData=null, conversionDelaySeconds=0, forwardingScore=0, forwarded=false, quotedAd=null, placeholderKey=null, ephemeralExpiration=0, ephemeralSettingTimestamp=0, ephemeralSharedSecret=null, externalAdReply=null, entryPointConversionSource=null, entryPointConversionApp=null, entryPointConversionDelaySeconds=0, disappearingMode=null, actionLink=null, groupSubject=null, parentGroup=null)), text=This is a test 00005, matchedText=null, canonicalUrl=null, description=null, title=null, textArgb=null, backgroundArgb=null, font=null, previewType=null, thumbnail=null, doNotPlayInline=false), timestamp=1668015624, status=PENDING, individualStatus={}, senderJid=XXXXXXXXXXXX:5@s.whatsapp.net, sender=Optional[Contact(jid=XXXXXXXXXXXX@s.whatsapp.net, chosenName=XXXXXXXXXX, fullName=XXXXXXXXXX, shortName=null, lastKnownPresence=Optional[COMPOSING], lastSeen=Optional[2022-11-09T17:41:00.271020900Z[UTC]])], messageC2STimestamp=0, ignore=false, starred=false, broadcast=false, pushName=XXXXXXXXXXXX, mediaCiphertextSha256=null, multicast=false, urlText=false, urlNumber=false, stubType=null, clearMedia=false, stubParameters=null, duration=0, labels=null, paymentInfo=null, finalLiveLocation=null, quotedPaymentInfo=null, ephemeralStartTimestamp=0, ephemeralDuration=0, enableEphemeral=false, ephemeralOutOfSync=false, businessPrivacyStatus=null, businessVerifiedName=null, mediaData=null, photoChange=null, receipt=null, reactions=null, quotedStickerData=null, futureProofData=null, psaStatus=null), MessageInfo(key=MessageKey(chatJid=XXXXXXXXXXXX:5@s.whatsapp.net, fromMe=false, id=3EB04852C4D4680ED998, senderJid=Optional[XXXXXXXXXXXX:5@s.whatsapp.net]), message=TextMessage(super=ContextualMessage(contextInfo=ContextInfo(quotedMessageId=Optional.empty, quotedMessageSenderJid=Optional.empty, quotedMessageSender=Optional.empty, quotedMessage=Optional.empty, quotedMessageChatJid=Optional.empty, quotedMessageChat=Optional.empty, mentions=null, conversionSource=null, conversionData=null, conversionDelaySeconds=0, forwardingScore=0, forwarded=false, quotedAd=null, placeholderKey=null, ephemeralExpiration=0, ephemeralSettingTimestamp=0, ephemeralSharedSecret=null, externalAdReply=null, entryPointConversionSource=null, entryPointConversionApp=null, entryPointConversionDelaySeconds=0, disappearingMode=null, actionLink=null, groupSubject=null, parentGroup=null)), text=This is a test 00006, matchedText=null, canonicalUrl=null, description=null, title=null, textArgb=null, backgroundArgb=null, font=null, previewType=null, thumbnail=null, doNotPlayInline=false), timestamp=1668015662, status=PENDING, individualStatus={}, senderJid=XXXXXXXXXXXX:5@s.whatsapp.net, sender=Optional[Contact(jid=XXXXXXXXXXXX@s.whatsapp.net, chosenName=XXXXXXXXXXXX, fullName=XXXXXXXXXXXX, shortName=null, lastKnownPresence=Optional[COMPOSING], lastSeen=Optional[2022-11-09T17:41:00.271020900Z[UTC]])], messageC2STimestamp=0, ignore=false, starred=false, broadcast=false, pushName=XXXXXXXXXXXX, mediaCiphertextSha256=null, multicast=false, urlText=false, urlNumber=false, stubType=null, clearMedia=false, stubParameters=null, duration=0, labels=null, paymentInfo=null, finalLiveLocation=null, quotedPaymentInfo=null, ephemeralStartTimestamp=0, ephemeralDuration=0, enableEphemeral=false, ephemeralOutOfSync=false, businessPrivacyStatus=null, businessVerifiedName=null, mediaData=null, photoChange=null, receipt=null, reactions=null, quotedStickerData=null, futureProofData=null, psaStatus=null), MessageInfo(key=MessageKey(chatJid=XXXXXXXXXXXX:5@s.whatsapp.net, fromMe=false, id=3EB064B302F380494145, senderJid=Optional[XXXXXXXXXXXX:5@s.whatsapp.net]), message=TextMessage(super=ContextualMessage(contextInfo=ContextInfo(quotedMessageId=Optional.empty, quotedMessageSenderJid=Optional.empty, quotedMessageSender=Optional.empty, quotedMessage=Optional.empty, quotedMessageChatJid=Optional.empty, quotedMessageChat=Optional.empty, mentions=null, conversionSource=null, conversionData=null, conversionDelaySeconds=0, forwardingScore=0, forwarded=false, quotedAd=null, placeholderKey=null, ephemeralExpiration=0, ephemeralSettingTimestamp=0, ephemeralSharedSecret=null, externalAdReply=null, entryPointConversionSource=null, entryPointConversionApp=null, entryPointConversionDelaySeconds=0, disappearingMode=null, actionLink=null, groupSubject=null, parentGroup=null)), text=This is a test 00007, matchedText=null, canonicalUrl=null, description=null, title=null, textArgb=null, backgroundArgb=null, font=null, previewType=null, thumbnail=null, doNotPlayInline=false), timestamp=1668015886, status=PENDING, individualStatus={}, senderJid=XXXXXXXXXXXX:5@s.whatsapp.net, sender=Optional[Contact(jid=XXXXXXXXXXXX@s.whatsapp.net, chosenName=XXXXXXXXXXXX, fullName=XXXXXXXXXXXX, shortName=null, lastKnownPresence=Optional[COMPOSING], lastSeen=Optional[2022-11-09T19:44:44.841768800+02:00[Africa/Johannesburg]])], messageC2STimestamp=0, ignore=false, starred=false, broadcast=false, pushName=XXXXXXXXXXXX, mediaCiphertextSha256=null, multicast=false, urlText=false, urlNumber=false, stubType=null, clearMedia=false, stubParameters=null, duration=0, labels=null, paymentInfo=null, finalLiveLocation=null, quotedPaymentInfo=null, ephemeralStartTimestamp=0, ephemeralDuration=0, enableEphemeral=false, ephemeralOutOfSync=false, businessPrivacyStatus=null, businessVerifiedName=null, mediaData=null, photoChange=null, receipt=null, reactions=null, quotedStickerData=null, futureProofData=null, psaStatus=null)], newJid=Optional.empty, oldJid=Optional.empty, unreadMessages=0, ephemeralMessageDuration=OFF, ephemeralMessagesToggleTime=Optional.empty, timestamp=Optional[2022-11-09T19:34:17+02:00[Africa/Johannesburg]], name=XXXXXXXXXXXX, notSpam=true, archived=false, disappearInitiator=Optional[ChatDisappear(disappear=CHANGED_IN_CHAT)], token=null, tokenTimestamp=0, identityKey=[-116, -54, -16, -94, 44, 27, -100, 61, 78, -111, -85, -104, -51, 13, -54, 8, 78, -115, 76, 70, 16, -56, -55, -28, -113, -35, -10, 55, -21, -120, 127, 115], pinned=Optional.empty, mute=ChatMute[endTimeStamp=0], wallpaper=Optional.empty, mediaVisibility=DEFAULT, tokenSenderTimestamp=0, suspended=false, presences={Contact(jid=XXXXXXXXXXXX@s.whatsapp.net, chosenName=XXXXXXXXXXXX, fullName=XXXXXXXXXXXX, shortName=null, lastKnownPresence=Optional[COMPOSING], lastSeen=Optional[2022-11-09T17:41:00.271020900Z[UTC]])=COMPOSING, Contact(jid=XXXXXXXXXXXX@s.whatsapp.net, chosenName=XXXXXXXXXXXX, fullName=XXXXXXXXXXXX, shortName=null, lastKnownPresence=Optional[COMPOSING], lastSeen=Optional[2022-11-09T19:44:44.841768800+02:00[Africa/Johannesburg]])=COMPOSING}, participantsPreKeys=[])
```

**Comment by Auties00** [comment]
@NeilDuToit92 can you test the latest commit?

**Comment by NeilDuToit92** [comment]
Tried the last commit with the following in the listener, it still doesn't mark it as read to the sender.
```
  @Override
  public void onNewMessage(Whatsapp whatsapp, MessageInfo info) {
    if (!(info.message().content() instanceof TextMessage textMessage)) {
      return;
    }
    PageController.lastReceivedMessage = textMessage.text();
    System.out.println("Message Received: " + textMessage.text());
        whatsapp.markRead(info).join();
  }
```

**Comment by Auties00** [comment]
> Tried the last commit with the following in the listener, it still doesn't mark it as read to the sender.
> 
> ```
>   @Override
>   public void onNewMessage(Whatsapp whatsapp, MessageInfo info) {
>     if (!(info.message().content() instanceof TextMessage textMessage)) {
>       return;
>     }
>     PageController.lastReceivedMessage = textMessage.text();
>     System.out.println("Message Received: " + textMessage.text());
>     whatsapp.markRead(info).join();
>   }
> ```

Check the latest commit, I've just tested it and afaict it works

**Comment by NeilDuToit92** [comment]
I can confirm this is now working
