### ISSUE TITLE
How to Download Media in quotedMessage

### ISSUE THREAD

**Issue by fckvania** [Auties00/WhatsappWeb4j#188]

**Comment by Auties00** [comment]
> _No description provided._

You can use the chatJid and message id in the quotedMessage to get the actual message from the store(findMessageById(ContactJid, String)). Then you can download it normally using the Whatsapp class

**Comment by fckvania** [comment]
> > _No description provided._
> 
> You can use the chatJid and message id in the quotedMessage to get the actual message from the store(findMessageById(ContactJid, String)). Then you can download it normally using the Whatsapp class

Thanks
