### ISSUE TITLE
Messages sent after initial connection does not have a Receipt object

### ISSUE THREAD

**Issue by NeilDuToit92** [Auties00/WhatsappWeb4j#194]
Code being executed:
```
for (Chat chat : WhatsappApp.whatsapp.store().chats()) {
  for (MessageInfo messageInfo : chat.messages()) {
    if (!Objects.isNull(messageInfo.receipt()) {
      //Omitted - Reads data from messageInfo.receipt() into DTO for front-end use
    }
  }
}
```
For any message that was sent before linking (scanning QR code), the `MessageInfo` has a `Receipt` object, from which I can pull the `Delivered` and `Read` timestamps.
However, any message sent after linking does not have a Receipt Object (And does not update it).
All messages in this screenshot has been delivered and read by the other user (Screenshot uses above code to render HTML page).
![image](https://user-images.githubusercontent.com/2218598/208513539-7689d130-ce46-4a7b-901e-22e5dde16b3a.png)

When deleting the old link, and re-linking my device, the `Receipt` object is available on some the messages for which it was previously missing: 
![image](https://user-images.githubusercontent.com/2218598/208515039-a8ceea46-84f0-4d9a-b430-cf124ed50b2d.png)

Scenario:
1. Scan QR code
2. Send message with WhatsappWeb4j
3. Open message on receiver device
4. Execute code above
5. Receipt is null - expecting a value here
6. Create new connection with WhatsappWeb4j
7. Receipt is no longer null and works as expected

**Comment by Auties00** [comment]
> Code being executed:
> 
> ```
> for (Chat chat : WhatsappApp.whatsapp.store().chats()) {
>   for (MessageInfo messageInfo : chat.messages()) {
>     if (!Objects.isNull(messageInfo.receipt()) {
>       //Omitted - Reads data from messageInfo.receipt() into DTO for front-end use
>     }
>   }
> }
> ```
> 
> For any message that was sent before linking (scanning QR code), the `MessageInfo` has a `Receipt` object, from which I can pull the `Delivered` and `Read` timestamps. However, any message sent after linking does not have a Receipt Object (And does not update it). All messages in this screenshot has been delivered and read by the other user (Screenshot uses above code to render HTML page). ![image](https://user-images.githubusercontent.com/2218598/208513539-7689d130-ce46-4a7b-901e-22e5dde16b3a.png)
> 
> When deleting the old link, and re-linking my device, the `Receipt` object is available on some the messages for which it was previously missing: ![image](https://user-images.githubusercontent.com/2218598/208515039-a8ceea46-84f0-4d9a-b430-cf124ed50b2d.png)
> 
> Scenario:
> 
> 1. Scan QR code
> 2. Send message with WhatsappWeb4j
> 3. Open message on receiver device
> 4. Execute code above
> 5. Receipt is null - expecting a value here
> 6. Create new connection with WhatsappWeb4j
> 7. Receipt is no longer null and works as expected

So your complaint is valid, in short that's not really a receipt about what you are expecting. This type of receipt is for cryptographic data but should have never been filled out in the first place so I have no clue how you are even getting any values. I should have fixed it in the last commit by removing fields that are not filled. If you are looking for the message status(ex. delivered) use MessageInfo#status() or MessageInfo#individualStatus()

**Comment by NeilDuToit92** [comment]
I am looking for the Delivered and Read timestamps, as is visible when using WhatsApp Web when clicking on a message and going to `Message Info`, are you saying that this is not the same data as what is present in the `Receipt` object?

![image](https://user-images.githubusercontent.com/2218598/208750703-718657d2-45fe-4869-add3-c07585798c7c.png)

**Comment by Auties00** [comment]
> I am looking for the Delivered and Read timestamps, as is visible when using WhatsApp Web when clicking on a message and going to `Message Info`, are you saying that this is not the same data as what is present in the `Receipt` object?
> 
> ![image](https://user-images.githubusercontent.com/2218598/208750703-718657d2-45fe-4869-add3-c07585798c7c.png)

Looks like I need to look into it, you are right about using that object. I'll look at how Whatsapp handles it in their source and get back to you

**Comment by Auties00** [comment]
I've made some progress in the last commit, I'm working on it

**Comment by Auties00** [comment]
Can you verify if the receipts are now correct?

**Comment by NeilDuToit92** [comment]
I am on holiday until January, I'll check this again when I get back home.

**Comment by NeilDuToit92** [comment]
I tested this, and `readTimestamp` looks like it's working correctly now.
`deliveredTimestamp`, however has some issues.

Firstly, the getter is wrong for it - it is `Clock.parse(readTimestamp)`, should be `Clock.parse(deliveredTimestamp)`
Secondly, `MessageReceipt` sets `deliveredTimestamp` when the contructor is called, so it is populated when the message is sent, not when it is delivered.

1. Put the receiving phone into offline mode (No LTE/WiFi)
2. Send message via library
3. Open WhatsApp on phone linked to library
4. Message has 1 tick (Sent, not delivered)
5. Library has a delivered timestamp (wrong, should be null because message has not been delivered yet)
6. Turn WiFi on on receiving phone
7. Message gets 2 ticks on sending phone (this is when deliveredTimestamp should be set)
8. Open message on receiving phone
9. Ticks turn blue - readTimestamp is populated (Correct)

**Comment by Auties00** [comment]
> I tested this, and `readTimestamp` looks like it's working correctly now. `deliveredTimestamp`, however has some issues.
> 
> Firstly, the getter is wrong for it - it is `Clock.parse(readTimestamp)`, should be `Clock.parse(deliveredTimestamp)` Secondly, `MessageReceipt` sets `deliveredTimestamp` when the contructor is called, so it is populated when the message is sent, not when it is delivered.
> 
> 1. Put the receiving phone into offline mode (No LTE/WiFi)
> 2. Send message via library
> 3. Open WhatsApp on phone linked to library
> 4. Message has 1 tick (Sent, not delivered)
> 5. Library has a delivered timestamp (wrong, should be null because message has not been delivered yet)
> 6. Turn WiFi on on receiving phone
> 7. Message gets 2 ticks on sending phone (this is when deliveredTimestamp should be set)
> 8. Open message on receiving phone
> 9. Ticks turn blue - readTimestamp is populated (Correct)

Can you try the latest commit?

**Comment by NeilDuToit92** [comment]
Having issues with the latest commit when scanning QR code, did you change something that could be causing this?
I tried pulling the latest ModernProtobuf as well after getting this error, still getting the same error

```
java.lang.IndexOutOfBoundsException: Range [9, 9 + 7499105) out of bounds for length 10
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:82)
	at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:361)
	at java.base/java.util.Objects.checkFromIndexSize(Objects.java:411)
	at java.base/java.nio.HeapByteBuffer.get(HeapByteBuffer.java:191)
	at java.base/java.nio.ByteBuffer.get(ByteBuffer.java:910)
	at it.auties.bytes.Bytes.readBytes(Bytes.java:326)
	at it.auties.bytes.Bytes.readBuffer(Bytes.java:313)
	at it.auties.whatsapp.binary.MessageWrapper.<init>(MessageWrapper.java:31)
	at it.auties.whatsapp.binary.MessageWrapper.<init>(MessageWrapper.java:37)
	at it.auties.whatsapp.socket.SocketHandler.onBinary(SocketHandler.java:207)
	at jdk.internal.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:105)
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageBinary(WsFrameBase.java:602)
	at org.apache.tomcat.websocket.WsFrameBase.processDataBinary(WsFrameBase.java:561)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:307)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
	at org.apache.tomcat.websocket.WsFrameClient.processSocketRead(WsFrameClient.java:95)
	at org.apache.tomcat.websocket.WsFrameClient.resumeProcessing(WsFrameClient.java:212)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.doResumeProcessing(WsFrameClient.java:189)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.completed(WsFrameClient.java:163)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.completed(WsFrameClient.java:148)
	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$WrapperFuture.complete(AsyncChannelWrapperSecure.java:474)
	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$ReadTask.run(AsyncChannelWrapperSecure.java:338)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Auties00** [comment]
> Having issues with the latest commit when scanning QR code, did you change something that could be causing this?
> I tried pulling the latest ModernProtobuf as well after getting this error, still getting the same error
> 
> ```
> java.lang.IndexOutOfBoundsException: Range [9, 9 + 7499105) out of bounds for length 10
> 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
> 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:82)
> 	at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:361)
> 	at java.base/java.util.Objects.checkFromIndexSize(Objects.java:411)
> 	at java.base/java.nio.HeapByteBuffer.get(HeapByteBuffer.java:191)
> 	at java.base/java.nio.ByteBuffer.get(ByteBuffer.java:910)
> 	at it.auties.bytes.Bytes.readBytes(Bytes.java:326)
> 	at it.auties.bytes.Bytes.readBuffer(Bytes.java:313)
> 	at it.auties.whatsapp.binary.MessageWrapper.<init>(MessageWrapper.java:31)
> 	at it.auties.whatsapp.binary.MessageWrapper.<init>(MessageWrapper.java:37)
> 	at it.auties.whatsapp.socket.SocketHandler.onBinary(SocketHandler.java:207)
> 	at jdk.internal.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:105)
> 	at org.apache.tomcat.websocket.WsFrameBase.sendMessageBinary(WsFrameBase.java:602)
> 	at org.apache.tomcat.websocket.WsFrameBase.processDataBinary(WsFrameBase.java:561)
> 	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:307)
> 	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
> 	at org.apache.tomcat.websocket.WsFrameClient.processSocketRead(WsFrameClient.java:95)
> 	at org.apache.tomcat.websocket.WsFrameClient.resumeProcessing(WsFrameClient.java:212)
> 	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.doResumeProcessing(WsFrameClient.java:189)
> 	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.completed(WsFrameClient.java:163)
> 	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.completed(WsFrameClient.java:148)
> 	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$WrapperFuture.complete(AsyncChannelWrapperSecure.java:474)
> 	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$ReadTask.run(AsyncChannelWrapperSecure.java:338)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> ```

Can you try to delete all your current sessions? If it doesn't work I'll take a look

**Comment by NeilDuToit92** [comment]
Still not working, deleted all my sessions, scanned the QR code, it looks like it syncs the chats, but fails halfway.
Can't send messages either, it just hangs on the send call.
Full log with all error messages attached.
[app.log](https://github.com/Auties00/WhatsappWeb4j/files/10369342/app.log)

**Comment by Auties00** [comment]
> Still not working, deleted all my sessions, scanned the QR code, it looks like it syncs the chats, but fails halfway. Can't send messages either, it just hangs on the send call. Full log with all error messages attached. [app.log](https://github.com/Auties00/WhatsappWeb4j/files/10369342/app.log)

Can you try now?
