### ISSUE TITLE
Messages sent from main mobile device has null or weird Receipt object

### ISSUE THREAD

**Issue by NeilDuToit92** [Auties00/WhatsappWeb4j#195]
This is similar to #194, but slightly different, but this one involves messages being sent from the main mobile device which WhatsappWeb4j is linked to.

Code being executed:
```
for (Chat chat : WhatsappApp.whatsapp.store().chats()) {
  for (MessageInfo messageInfo : chat.messages()) {
    if (!Objects.isNull(messageInfo.receipt()) {
      //Omitted - Reads data from messageInfo.receipt() into DTO for front-end use
    }
  }
}
```

Scenario:
1. Scan QR code
2. Send message with phone
3. Open message on receiver device
4. Execute code above
5. Receipt is null - expecting a value here
6. Create new connection with WhatsappWeb4j
7. Receipt is no longer null, but has own number instead of recipient number and timestamps of `0`

![image](https://user-images.githubusercontent.com/2218598/208521609-5af6c3e1-a1c7-4e07-ba68-cca73c1ce3a4.png)

**Comment by Auties00** [comment]
See #194 to understand
