### ISSUE TITLE
master build failing at the moment

### ISSUE THREAD

**Issue by rsegerink** [Auties00/WhatsappWeb4j#196]
Hi, I would like to contribute to this project and I'm trying to build but the master build is failing at the moment, could you make it building again? Thanks.

**Comment by Auties00** [comment]
> Hi, I would like to contribute to this project and I'm trying to build but the master build is failing at the moment, could you make it building again? Thanks.

Can you check right now if it's building?

**Comment by NeilDuToit92** [comment]
The code is compiling for me, the tests are giving issues, so I just disabled them.

`RunCITest` hangs in `testButtonsMessage()` on `api.store().mediaConnection()`
`UpdateCITest` fails
`TokensCollectorTest` fails

**Comment by Auties00** [comment]
> The code is compiling for me, the tests are giving issues, so I just disabled them.
> 
> `RunCITest` hangs in `testButtonsMessage()` on `api.store().mediaConnection()` `UpdateCITest` fails `TokensCollectorTest` fails

Can you check again the CI and also can you send me the error that tokenscollectortest throws?

**Comment by NeilDuToit92** [comment]
Here are all the test errors I am getting currently

### RunCITest.testVideoMessage()
```
Caused by: java.io.FileNotFoundException: https://file-examples.com/storage/fedb96226c637d3059a2f86/2017/04/file_example_MP4_480_1_5MG.mp4
```

### RunCITest.testGifMessage()
```
Caused by: java.io.FileNotFoundException: https://file-examples.com/storage/fedb96226c637d3059a2f86/2017/04/file_example_MP4_480_1_5MG.mp4
```

### UpdateCITest
```
java.lang.ExceptionInInitializerError
	at it.auties.whatsappweb4j@3.0-Dev01/it.auties.whatsapp.test.UpdateCITest.updateCredentials(UpdateCITest.java:18)
```

### TokenCollectorTest
```
java.util.NoSuchElementException: No value present

	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at it.auties.whatsappweb4j@3.0-Dev01/it.auties.whatsapp.test.TokensCollectorTest.findResult(TokensCollectorTest.java:104)
	at it.auties.whatsappweb4j@3.0-Dev01/it.auties.whatsapp.test.TokensCollectorTest.getJavascriptSource(TokensCollectorTest.java:92)
	at it.auties.whatsappweb4j@3.0-Dev01/it.auties.whatsapp.test.TokensCollectorTest.createClass(TokensCollectorTest.java:54)
	...
```
`input `varaible on `findResult`:
```
<!DOCTYPE html><html class="no-js" dir="ltr" loc="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><title>WhatsApp Web</title><meta name="viewport" content="width=device-width"><meta name="google" content="notranslate"><meta name="format-detection" content="telephone=no"><meta name="description" content="Quickly send and receive WhatsApp messages right from your computer."><meta name="og:description" content="Quickly send and receive WhatsApp messages right from your computer."><meta name="og:url" content="https://web.whatsapp.com/"><meta name="og:title" content="WhatsApp Web"><meta name="og:image" content="https://static.facebook.com/images/whatsapp/www/whatsapp-promo.png"><link id="favicon" rel="shortcut icon" href="/img/favicon/1x/favicon.png" type="image/png"><link rel="apple-touch-icon" sizes="194x194" href="/apple-touch-icon.png" type="image/png"><style>#initial_startup{--startup-background:#f0f2f5;--startup-background-rgb:240,242,245;--startup-icon:#bbc5cb;--secondary-lighter:#8696a0;--primary-title:#41525d;--progress-primary:#00c298;--progress-background:#e9edef}.dark #initial_startup{--startup-background:#111b21;--startup-background-rgb:17,27,33;--startup-icon:#676f73;--primary-title:rgba(233, 237, 239, 0.88);--secondary-lighter:#667781;--progress-primary:#0b846d;--progress-background:#233138}#app,body,html{width:100%;height:100%;padding:0;margin:0;overflow:hidden}#app{position:absolute;top:0;left:0}#initial_startup{position:fixed;top:0;left:0;display:flex;flex-direction:column;align-items:center;justify-content:center;width:100%;height:100%;user-select:none;background-color:var(--startup-background)}#initial_startup .graphic{margin-top:-40px;color:var(--startup-icon)}#initial_startup .graphic .resume-logo{transform:translateX(calc(50% - 52px / 2))}#initial_startup .graphic::after{position:relative;top:-100%;left:calc(50% - 72px * 2 - 72px / 2);display:block;width:calc(72px * 3);height:100%;content:'';background:linear-gradient(to right,rgba(var(--startup-background-rgb),.5) 0,rgba(var(--startup-background-rgb),.5) 33.33%,rgba(var(--startup-background-rgb),0) 44.1%,rgba(var(--startup-background-rgb),0) 55.8%,rgba(var(--startup-background-rgb),.5) 66.66%,rgba(var(--startup-background-rgb),.5) 100%);opacity:1;animation:shimmer 1.5s linear .6s infinite}html[dir=rtl] #initial_startup .graphic::after{animation-direction:reverse}@keyframes shimmer{from{left:calc(50% - 72px * 2 - 72px / 2)}to{left:calc(50% - 72px / 2)}}#initial_startup .progress{position:relative;width:420px;height:3px;margin-top:40px}#initial_startup .progress progress{vertical-align:top}#initial_startup .main{margin-top:40px;font-size:17px;color:var(--primary-title)}#initial_startup .secondary{margin-top:12px;font-size:14px;color:var(--secondary-lighter)}#initial_startup .secondary span{display:inline-block;margin-bottom:2px;vertical-align:middle}progress{-webkit-appearance:none;appearance:none;width:100%;height:3px;margin:0;color:var(--progress-primary);background-color:var(--progress-background);border:none}progress[value]::-webkit-progress-bar{background-color:var(--progress-background)}progress[value]::-moz-progress-bar,progress[value]::-webkit-progress-value{background-color:var(--progress-primary);transition:width .45s ease}</style><link href="/stylex-336eae0f683f5db93e748c5918acbece.css" rel="stylesheet"><link href="/app-a44cd2aca5375579a269.css" rel="stylesheet"></head><body class="web"><script data-binary-transparency-hash-key="inline-js-4b79b6dc91a7ee33373b115991c3eb287ed710cfb6708421b4cab682eddbfcbd">try{var systemThemeDark,theme=window.localStorage.getItem(""),systemThemeMode=window.localStorage.getItem("system-theme-mode");if(("true"===systemThemeMode||!theme)&&window.matchMedia){var systemTheme=window.matchMedia("(prefers-color-scheme: dark)");systemThemeDark=systemTheme&&systemTheme.matches}var darkTheme='"dark"'===theme||Boolean(systemThemeDark);darkTheme&&document.body.classList.add("dark")}catch(e){}</script><div id="app"></div><div id="hard_expire_time" data-time="1686695103.649"></div><div id="initial_startup"><div class="graphic"><span><svg width="250" height="52" xmlns="http://www.w3.org/2000/svg"><path class="resume-logo" d="M37.7 31.2c-.6-.4-3.8-2-4.4-2.1-.6-.2-1-.4-1.4.3l-2 2.5c-.4.4-.8.5-1.5.2-.6-.3-2.7-1-5.1-3.2-2-1.7-3.2-3.8-3.6-4.5-.4-.6 0-1 .3-1.3l1-1.1.6-1.1c.2-.4 0-.8 0-1.1l-2-4.8c-.6-1.3-1.1-1-1.5-1.1h-1.2c-.5 0-1.2.1-1.8.8-.5.6-2.2 2.2-2.2 5.3 0 3.2 2.3 6.3 2.6 6.7.3.4 4.6 7 11 9.7l3.7 1.4c1.5.5 3 .4 4 .2 1.3-.1 3.9-1.5 4.4-3 .5-1.5.5-2.8.4-3-.2-.4-.6-.5-1.3-.8M26 47.2c-3.9 0-7.6-1-11-3l-.7-.4-8.1 2L8.4 38l-.6-.8A21.4 21.4 0 0126 4.4a21.3 21.3 0 0121.4 21.4c0 11.8-9.6 21.4-21.4 21.4M44.2 7.6a25.8 25.8 0 00-40.6 31L0 52l13.7-3.6A25.8 25.8 0 0044.3 7.5" fill="currentColor"></path></svg></span></div><div class="progress"><progress value="0" max="100" dir="ltr"></progress></div><div class="main">WhatsApp</div><div class="secondary"><span><svg width="10" height="12" xmlns="http://www.w3.org/2000/svg"><path d="M5 1.6c1.4 0 2.5 1 2.6 2.4v1.5h.2c.5 0 1 .4 1 1V10c0 .6-.5 1-1 1H2.3a1 1 0 01-1.1-1V6.5c0-.6.5-1 1-1h.2V4.2c0-1.4 1-2.5 2.4-2.6H5zm0 1.2c-.7 0-1.3.6-1.3 1.3v1.4h2.6V4.2c0-.7-.4-1.2-1-1.3H5z" fill="currentColor"></path></svg> </span>&nbsp;End-to-end encrypted</div></div><link rel="preload" crossorigin="anonymous" as="fetch" href="/binary-transparency-manifest-2.2247.6.json" id="binary-transparency-manifest-preload"><script src="/libsignal-protocol-ee5b8ba.min.js"></script><script defer="defer" src="/runtime.10e6221e827df05f572a.js"></script><script data-binary-transparency-hash-key="inline-js-ed41805786dd1117101bb9885837e2401d53223c1031134fccc67479cc3870c4">/*! Copyright (c) 2022 WhatsApp Inc. All Rights Reserved. */
(self.webpackChunkwhatsapp_web_client=self.webpackChunkwhatsapp_web_client||[]).push([[5617],{595318:e=>{e.exports=function(e){return e&&e.__esModule?e:{default:e}},e.exports.default=e.exports,e.exports.__esModule=!0},132375:(e,t)=>{"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=function(e){let t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:"?";if(null==e)throw new Error("Unexpected null or undefined: "+t);return e}},801506:(e,t)=>{"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.UPLOAD_TO_CLB=t.TICKET_URL=t.LOG_SIZE=t.CLB_URL=t.CLB_TOKEN=t.CLB_CHECK_URL=void 0,t.CLB_CHECK_URL="https://crashlogs.whatsapp.net/wa_fls_upload_check",t.CLB_TOKEN="1063127757113399|745146ffa34413f9dbb5469f5370b7af",t.CLB_URL="https://crashlogs.whatsapp.net/wa_clb_data",t.TICKET_URL="https://web.whatsapp.com/web-contact-us";let n=0;n=1,t.UPLOAD_TO_CLB=1,t.LOG_SIZE=4999},207024:(e,t)=>{"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getDistribution=function(){let e="unknown";return e="prod","web_prod"},t.getLogUserAgent=function(e){let t,{appVersion:n,browser:r,device:o}=e;return t="Web/"+r,`WhatsApp/${n} ${t} Device/${o}`}},794858:(e,t,n)=>{"use strict";var r=n(595318),o=r(n(132375)),a=n(801506),s=n(207024),c=r(n(174285)),l=n(425017);function i(e){!function(e,t){const n=window.navigator.userAgent;if(n===p&&e.includes("getElementsByTagName"))return;const r=new FormData,i=new Blob([e],{type:"text/plain"});r.append("from_jid",function(){if(f)return f;try{f=JSON.parse((0,o.default)(c.default,"localStorage").getItem(d)),f&&(f=f.replace("-",""))}catch(e){}if(!f){f="unknown"+Math.floor(1e10*Math.random());const e=f;try{(0,o.default)(c.default,"localStorage").setItem(d,JSON.stringify(e))}catch(e){}}return(0,o.default)(f,"id")}()),r.append("agent",(0,s.getLogUserAgent)((0,l.parseUASimple)(n,"2.2247.6"))),r.append("file",i,"logs.txt"),r.append("tags","load");const u=new XMLHttpRequest,_=a.CLB_URL+"?access_token="+encodeURIComponent(a.CLB_TOKEN);u.open("POST",_,!0),u.send(r)}(e)}function u(e){let{error:t,reason:n,stack:r}=e;const o=(new Date).toISOString();return`${o}: error: ${t}\n${o}: reason for logs: ${n}\n${o}: userAgent: ${window.navigator.userAgent}\n${r}`}null==window.onerror&&(window.onerror=function(e,t,n){const r=t.split("?")[0];return"Uncaught SyntaxError: Unexpected token '<'"===e?(function(e){i(u({error:"failed to load a js or css bundle",reason:`failed to load [${e.split("/")[3].replace(/^\//,"")}]`,stack:""}))}(r),!0):(i(u({error:e,reason:`Error at [${r}:${n}]`,stack:""})),!1)});const d="WAUnknownID",p="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36";let f},425017:(e,t)=>{"use strict";function n(e){return e.includes("windows")?"Windows":e.includes("mac")?"Mac OS":e.includes("linux")?"Linux":"Unparsed"}Object.defineProperty(t,"__esModule",{value:!0}),t.parseUASimple=function(e,t){const r=e.toLowerCase();return{browser:s(r),device:n(r),appVersion:t}};const r=/(chrome|firefox)\/([\w\.]+)/i,o=/(edge|opr)\/([\w\.]+)/i,a={chrome:"Chrome",edge:"Edge",opr:"Opera",firefox:"Firefox"};function s(e){const t=e.match(o)||e.match(r);return null==t?"Unparsed":`${a[t[1]]} ${t[2]}`}},174285:(e,t)=>{"use strict";let n;Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;try{n=window.localStorage}catch(e){}var r=n;t.default=r}},e=>{"use strict";e(e.s=794858)}])</script><script defer="defer" src="/vendor1~app.ae7c9071ac6bdfd06f8e.js"></script><script defer="defer" src="/app.370342c2934091134e27.js"></script><script data-binary-transparency-hash-key="inline-js-9c8cd3d0f4d5af8c7f5cd1c45208edd308bfe472e353a50e4cbacbf6cb58627c">(i => {const l = document.getElementById(i); l &&fetch(l.href).then(b => b.text()).then(code => {const script = document.createElement('script');script.id = 'binary-transparency-manifest';script.type = 'application/json';script.innerHTML = code;document.body.append(script);});})('binary-transparency-manifest-preload');</script></body></html>
```

**Comment by Auties00** [comment]
> Here are all the test errors I am getting currently
> 
> ### RunCITest.testVideoMessage()
> ```
> Caused by: java.io.FileNotFoundException: https://file-examples.com/storage/fedb96226c637d3059a2f86/2017/04/file_example_MP4_480_1_5MG.mp4
> ```
> 
> ### RunCITest.testGifMessage()
> ```
> Caused by: java.io.FileNotFoundException: https://file-examples.com/storage/fedb96226c637d3059a2f86/2017/04/file_example_MP4_480_1_5MG.mp4
> ```
> 
> ### UpdateCITest
> ```
> java.lang.ExceptionInInitializerError
> 	at it.auties.whatsappweb4j@3.0-Dev01/it.auties.whatsapp.test.UpdateCITest.updateCredentials(UpdateCITest.java:18)
> ```
> 
> ### TokenCollectorTest
> ```
> java.util.NoSuchElementException: No value present
> 
> 	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
> 	at it.auties.whatsappweb4j@3.0-Dev01/it.auties.whatsapp.test.TokensCollectorTest.findResult(TokensCollectorTest.java:104)
> 	at it.auties.whatsappweb4j@3.0-Dev01/it.auties.whatsapp.test.TokensCollectorTest.getJavascriptSource(TokensCollectorTest.java:92)
> 	at it.auties.whatsappweb4j@3.0-Dev01/it.auties.whatsapp.test.TokensCollectorTest.createClass(TokensCollectorTest.java:54)
> 	...
> ```
> 
> `input `varaible on `findResult`:
> 
> ```
> <!DOCTYPE html><html class="no-js" dir="ltr" loc="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><title>WhatsApp Web</title><meta name="viewport" content="width=device-width"><meta name="google" content="notranslate"><meta name="format-detection" content="telephone=no"><meta name="description" content="Quickly send and receive WhatsApp messages right from your computer."><meta name="og:description" content="Quickly send and receive WhatsApp messages right from your computer."><meta name="og:url" content="https://web.whatsapp.com/"><meta name="og:title" content="WhatsApp Web"><meta name="og:image" content="https://static.facebook.com/images/whatsapp/www/whatsapp-promo.png"><link id="favicon" rel="shortcut icon" href="/img/favicon/1x/favicon.png" type="image/png"><link rel="apple-touch-icon" sizes="194x194" href="/apple-touch-icon.png" type="image/png"><style>#initial_startup{--startup-background:#f0f2f5;--startup-background-rgb:240,242,245;--startup-icon:#bbc5cb;--secondary-lighter:#8696a0;--primary-title:#41525d;--progress-primary:#00c298;--progress-background:#e9edef}.dark #initial_startup{--startup-background:#111b21;--startup-background-rgb:17,27,33;--startup-icon:#676f73;--primary-title:rgba(233, 237, 239, 0.88);--secondary-lighter:#667781;--progress-primary:#0b846d;--progress-background:#233138}#app,body,html{width:100%;height:100%;padding:0;margin:0;overflow:hidden}#app{position:absolute;top:0;left:0}#initial_startup{position:fixed;top:0;left:0;display:flex;flex-direction:column;align-items:center;justify-content:center;width:100%;height:100%;user-select:none;background-color:var(--startup-background)}#initial_startup .graphic{margin-top:-40px;color:var(--startup-icon)}#initial_startup .graphic .resume-logo{transform:translateX(calc(50% - 52px / 2))}#initial_startup .graphic::after{position:relative;top:-100%;left:calc(50% - 72px * 2 - 72px / 2);display:block;width:calc(72px * 3);height:100%;content:'';background:linear-gradient(to right,rgba(var(--startup-background-rgb),.5) 0,rgba(var(--startup-background-rgb),.5) 33.33%,rgba(var(--startup-background-rgb),0) 44.1%,rgba(var(--startup-background-rgb),0) 55.8%,rgba(var(--startup-background-rgb),.5) 66.66%,rgba(var(--startup-background-rgb),.5) 100%);opacity:1;animation:shimmer 1.5s linear .6s infinite}html[dir=rtl] #initial_startup .graphic::after{animation-direction:reverse}@keyframes shimmer{from{left:calc(50% - 72px * 2 - 72px / 2)}to{left:calc(50% - 72px / 2)}}#initial_startup .progress{position:relative;width:420px;height:3px;margin-top:40px}#initial_startup .progress progress{vertical-align:top}#initial_startup .main{margin-top:40px;font-size:17px;color:var(--primary-title)}#initial_startup .secondary{margin-top:12px;font-size:14px;color:var(--secondary-lighter)}#initial_startup .secondary span{display:inline-block;margin-bottom:2px;vertical-align:middle}progress{-webkit-appearance:none;appearance:none;width:100%;height:3px;margin:0;color:var(--progress-primary);background-color:var(--progress-background);border:none}progress[value]::-webkit-progress-bar{background-color:var(--progress-background)}progress[value]::-moz-progress-bar,progress[value]::-webkit-progress-value{background-color:var(--progress-primary);transition:width .45s ease}</style><link href="/stylex-336eae0f683f5db93e748c5918acbece.css" rel="stylesheet"><link href="/app-a44cd2aca5375579a269.css" rel="stylesheet"></head><body class="web"><script data-binary-transparency-hash-key="inline-js-4b79b6dc91a7ee33373b115991c3eb287ed710cfb6708421b4cab682eddbfcbd">try{var systemThemeDark,theme=window.localStorage.getItem(""),systemThemeMode=window.localStorage.getItem("system-theme-mode");if(("true"===systemThemeMode||!theme)&&window.matchMedia){var systemTheme=window.matchMedia("(prefers-color-scheme: dark)");systemThemeDark=systemTheme&&systemTheme.matches}var darkTheme='"dark"'===theme||Boolean(systemThemeDark);darkTheme&&document.body.classList.add("dark")}catch(e){}</script><div id="app"></div><div id="hard_expire_time" data-time="1686695103.649"></div><div id="initial_startup"><div class="graphic"><span><svg width="250" height="52" xmlns="http://www.w3.org/2000/svg"><path class="resume-logo" d="M37.7 31.2c-.6-.4-3.8-2-4.4-2.1-.6-.2-1-.4-1.4.3l-2 2.5c-.4.4-.8.5-1.5.2-.6-.3-2.7-1-5.1-3.2-2-1.7-3.2-3.8-3.6-4.5-.4-.6 0-1 .3-1.3l1-1.1.6-1.1c.2-.4 0-.8 0-1.1l-2-4.8c-.6-1.3-1.1-1-1.5-1.1h-1.2c-.5 0-1.2.1-1.8.8-.5.6-2.2 2.2-2.2 5.3 0 3.2 2.3 6.3 2.6 6.7.3.4 4.6 7 11 9.7l3.7 1.4c1.5.5 3 .4 4 .2 1.3-.1 3.9-1.5 4.4-3 .5-1.5.5-2.8.4-3-.2-.4-.6-.5-1.3-.8M26 47.2c-3.9 0-7.6-1-11-3l-.7-.4-8.1 2L8.4 38l-.6-.8A21.4 21.4 0 0126 4.4a21.3 21.3 0 0121.4 21.4c0 11.8-9.6 21.4-21.4 21.4M44.2 7.6a25.8 25.8 0 00-40.6 31L0 52l13.7-3.6A25.8 25.8 0 0044.3 7.5" fill="currentColor"></path></svg></span></div><div class="progress"><progress value="0" max="100" dir="ltr"></progress></div><div class="main">WhatsApp</div><div class="secondary"><span><svg width="10" height="12" xmlns="http://www.w3.org/2000/svg"><path d="M5 1.6c1.4 0 2.5 1 2.6 2.4v1.5h.2c.5 0 1 .4 1 1V10c0 .6-.5 1-1 1H2.3a1 1 0 01-1.1-1V6.5c0-.6.5-1 1-1h.2V4.2c0-1.4 1-2.5 2.4-2.6H5zm0 1.2c-.7 0-1.3.6-1.3 1.3v1.4h2.6V4.2c0-.7-.4-1.2-1-1.3H5z" fill="currentColor"></path></svg> </span>&nbsp;End-to-end encrypted</div></div><link rel="preload" crossorigin="anonymous" as="fetch" href="/binary-transparency-manifest-2.2247.6.json" id="binary-transparency-manifest-preload"><script src="/libsignal-protocol-ee5b8ba.min.js"></script><script defer="defer" src="/runtime.10e6221e827df05f572a.js"></script><script data-binary-transparency-hash-key="inline-js-ed41805786dd1117101bb9885837e2401d53223c1031134fccc67479cc3870c4">/*! Copyright (c) 2022 WhatsApp Inc. All Rights Reserved. */
> (self.webpackChunkwhatsapp_web_client=self.webpackChunkwhatsapp_web_client||[]).push([[5617],{595318:e=>{e.exports=function(e){return e&&e.__esModule?e:{default:e}},e.exports.default=e.exports,e.exports.__esModule=!0},132375:(e,t)=>{"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=function(e){let t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:"?";if(null==e)throw new Error("Unexpected null or undefined: "+t);return e}},801506:(e,t)=>{"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.UPLOAD_TO_CLB=t.TICKET_URL=t.LOG_SIZE=t.CLB_URL=t.CLB_TOKEN=t.CLB_CHECK_URL=void 0,t.CLB_CHECK_URL="https://crashlogs.whatsapp.net/wa_fls_upload_check",t.CLB_TOKEN="1063127757113399|745146ffa34413f9dbb5469f5370b7af",t.CLB_URL="https://crashlogs.whatsapp.net/wa_clb_data",t.TICKET_URL="https://web.whatsapp.com/web-contact-us";let n=0;n=1,t.UPLOAD_TO_CLB=1,t.LOG_SIZE=4999},207024:(e,t)=>{"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getDistribution=function(){let e="unknown";return e="prod","web_prod"},t.getLogUserAgent=function(e){let t,{appVersion:n,browser:r,device:o}=e;return t="Web/"+r,`WhatsApp/${n} ${t} Device/${o}`}},794858:(e,t,n)=>{"use strict";var r=n(595318),o=r(n(132375)),a=n(801506),s=n(207024),c=r(n(174285)),l=n(425017);function i(e){!function(e,t){const n=window.navigator.userAgent;if(n===p&&e.includes("getElementsByTagName"))return;const r=new FormData,i=new Blob([e],{type:"text/plain"});r.append("from_jid",function(){if(f)return f;try{f=JSON.parse((0,o.default)(c.default,"localStorage").getItem(d)),f&&(f=f.replace("-",""))}catch(e){}if(!f){f="unknown"+Math.floor(1e10*Math.random());const e=f;try{(0,o.default)(c.default,"localStorage").setItem(d,JSON.stringify(e))}catch(e){}}return(0,o.default)(f,"id")}()),r.append("agent",(0,s.getLogUserAgent)((0,l.parseUASimple)(n,"2.2247.6"))),r.append("file",i,"logs.txt"),r.append("tags","load");const u=new XMLHttpRequest,_=a.CLB_URL+"?access_token="+encodeURIComponent(a.CLB_TOKEN);u.open("POST",_,!0),u.send(r)}(e)}function u(e){let{error:t,reason:n,stack:r}=e;const o=(new Date).toISOString();return`${o}: error: ${t}\n${o}: reason for logs: ${n}\n${o}: userAgent: ${window.navigator.userAgent}\n${r}`}null==window.onerror&&(window.onerror=function(e,t,n){const r=t.split("?")[0];return"Uncaught SyntaxError: Unexpected token '<'"===e?(function(e){i(u({error:"failed to load a js or css bundle",reason:`failed to load [${e.split("/")[3].replace(/^\//,"")}]`,stack:""}))}(r),!0):(i(u({error:e,reason:`Error at [${r}:${n}]`,stack:""})),!1)});const d="WAUnknownID",p="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36";let f},425017:(e,t)=>{"use strict";function n(e){return e.includes("windows")?"Windows":e.includes("mac")?"Mac OS":e.includes("linux")?"Linux":"Unparsed"}Object.defineProperty(t,"__esModule",{value:!0}),t.parseUASimple=function(e,t){const r=e.toLowerCase();return{browser:s(r),device:n(r),appVersion:t}};const r=/(chrome|firefox)\/([\w\.]+)/i,o=/(edge|opr)\/([\w\.]+)/i,a={chrome:"Chrome",edge:"Edge",opr:"Opera",firefox:"Firefox"};function s(e){const t=e.match(o)||e.match(r);return null==t?"Unparsed":`${a[t[1]]} ${t[2]}`}},174285:(e,t)=>{"use strict";let n;Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;try{n=window.localStorage}catch(e){}var r=n;t.default=r}},e=>{"use strict";e(e.s=794858)}])</script><script defer="defer" src="/vendor1~app.ae7c9071ac6bdfd06f8e.js"></script><script defer="defer" src="/app.370342c2934091134e27.js"></script><script data-binary-transparency-hash-key="inline-js-9c8cd3d0f4d5af8c7f5cd1c45208edd308bfe472e353a50e4cbacbf6cb58627c">(i => {const l = document.getElementById(i); l &&fetch(l.href).then(b => b.text()).then(code => {const script = document.createElement('script');script.id = 'binary-transparency-manifest';script.type = 'application/json';script.innerHTML = code;document.body.append(script);});})('binary-transparency-manifest-preload');</script></body></html>
> ```

try now

**Comment by NeilDuToit92** [comment]
Okay, so I started using the project on a new laptop.

I had to install the https://github.com/Auties00/ModernProtobuf library to my local maven repo first.

After that, tests were all successful except for `UpdateCITest`, which is looking for a github token:
```
Caused by: java.lang.NullPointerException: Missing github_token in configuration
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at it.auties.whatsappweb4j/it.auties.whatsapp.github.GithubSecrets.loadGithubToken(GithubSecrets.java:137)
```

**Comment by Auties00** [comment]
> Okay, so I started using the project on a new laptop.
> 
> I had to install the https://github.com/Auties00/ModernProtobuf library to my local maven repo first.
> 
> After that, tests were all successful except for `UpdateCITest`, which is looking for a github token:
> 
> ```
> Caused by: java.lang.NullPointerException: Missing github_token in configuration
> 	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
> 	at it.auties.whatsappweb4j/it.auties.whatsapp.github.GithubSecrets.loadGithubToken(GithubSecrets.java:137)
> ```

Yeah this is normal, it's for the ci.
Also I pushed ModernProtobuf to maven central
