### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by z1065485649** [Auties00/WhatsappWeb4j#2]
Jdk15 all kinds of incompatibility, download try this project, simply can't use, period forget jdk8 project

**Comment by Auties00** [comment]
Hello,
Java 8 is no longer mantained or supported by Oracle.  You should be using Java 11, the latest LTS, or Java 15, the latest Java version as of today. If you are stuck on Java 8, migrate or don't use the project

**Comment by z1065485649** [comment]
Hello, please ask what plug-ins this project needs to use, I use idea +
jdk15 development, running the project report can not find import
it.auties.whatsapp4j . model.WhatsappNodeBuilder This class, can you give
me some advice, thank you

Alessandro Autiero ***@***.***> 于2021年3月12日周五 上午1:56写道：

**Comment by Auties00** [comment]
You just have to run the maven build, WhatsappNodeBuilder is a generated class
