### ISSUE TITLE
Compiling library caused account to get locked

### ISSUE THREAD

**Issue by NeilDuToit92** [Auties00/WhatsappWeb4j#201]
I just compiled the project which failed halfway through, when opening WhatsApp on my phone, I see the error
`This account is not allowed to use WhatsApp due to spam`

I compiled multiple times in December and didn't get this issue, I am guessing it is due to the high volume of requests that the unit tests run on the configured account.

It might be a good idea to put up a big red warning on the readme page that this is a possibility, so that people don't use their primary account (Luckily I used a dedicated number).

Edit: I requested a review through the in-app button, but I suspect they might keep my account blocked because reverse-engineering is against their terms.
I'll update on this ticket when I get feedback.

**Comment by Auties00** [comment]
> I just compiled the project which failed halfway through, when opening WhatsApp on my phone, I see the error `This account is not allowed to use WhatsApp due to spam`
> 
> I compiled multiple times in December and didn't get this issue, I am guessing it is due to the high volume of requests that the unit tests run on the configured account.
> 
> It might be a good idea to put up a big red warning on the readme page that this is a possibility, so that people don't use their primary account (Luckily I used a dedicated number).
> 
> Edit: I requested a review through the in-app button, but I suspect they might keep my account blocked because reverse-engineering is against their terms. I'll update on this ticket when I get feedback.

If you use this library on a fresh number that you have never used before with a contact you have, it's going to get banned 100% and there is nothing I can do about it. It would happen even if you used the main Whatsapp client. So no warning is necessary because your main account has been used enough for it to not get banned

**Comment by NeilDuToit92** [comment]
Based on what are you saying it will 100% get banned?

I have been using it for 2 months to send updates to my main number from my Home Assistant server, no other contacts, no other messages except 1-2 an hour with status updates.

It got banned the moment I compiled the library, so it didn't get banned for normal use, only when the high volume of requests started going through.

**Comment by Auties00** [comment]
> Based on what are you saying it will 100% get banned?
> 
> I have been using it for 2 months to send updates to my main number from my Home Assistant server, no other contacts, no other messages except 1-2 an hour with status updates.
> 
> It got banned the moment I compiled the library, so it didn't get banned for normal use, only when the high volume of requests started going through.

When you compile the library, it runs the CI which does a bunch of stuff really fast(you know it has to check that the library actually works). If you instead created a new project and compiled that, then it's an actual issue probably caused by the fact that I automatically subscribe to user presences which sends a ton of requests. If that's the case I'll remove it asap which should fix the issue

**Comment by NeilDuToit92** [comment]
I don't think you should remove the unit tests, 99% of users will pull the compiled library from maven instead of compiling themselves. The majority of people compiling themselves will be people who would want to contribute.

Hence the comment about maybe just adding a warning in the readme for people who do want to compile it themselves, maybe just something in the `How to contribute` section stating that the unit tests do execute a large number of operations which could cause an account to get banned - run them at your own risk.

FYI, my number got unbanned pretty quickly (about an hour), I'm just going to keep the unit tests disabled on my build so it doesn't happen again.

**Comment by NeilDuToit92** [comment]
I think the issue came in when the tests executed that creates the group and adds the user/promotes etc, that's when I got banned.

A potential workaround might be to add an `@AfterEach` block with a sleep of 2 or 3 seconds. That way, the requests hits WhatsApp at a rate which an actual person could do it.

**Comment by Auties00** [comment]
> I think the issue came in when the tests executed that creates the group and adds the user/promotes etc, that's when I got banned.
> 
> A potential workaround might be to add an `@AfterEach` block with a sleep of 2 or 3 seconds. That way, the requests hits WhatsApp at a rate which an actual person could do it.

That makes sense, I'll add a warning in the CI to not run it unless you know what you are doing and I'll make it slower so new numbers don't get banned for spamming
