### ISSUE TITLE
Feature : Please add findChatByContacts(WhatsappContact...contacts)

### ISSUE THREAD

**Issue by GedMarc** [Auties00/WhatsappWeb4j#22]
Please can we add the above method to uniquely search for groups/chats :)

Will see if I can do a PR but my fork pom is a bit different now ;)

**Comment by Auties00** [comment]
> Please can we add the above method to uniquely search for groups/chats :)
> 
> Will see if I can do a PR but my fork pom is a bit different now ;)

Doing something like this requires a call to WhatsapAPI#queryGroupMetadata. This would require the singleton WhatsappManager to have an instance of WhatsapAPI, which is not a singleton. There is already a method for this moreover called WhatsappAPI#queryGroupsInCommon
