### ISSUE TITLE
Unsupported class file major version 60

### ISSUE THREAD

**Issue by alirezasbri** [Auties00/WhatsappWeb4j#26]
I added your dependency to my project and I have gotten "Unsupported class file major version 60" error after run project.
help me to solve this problem, thanks.

**Comment by Auties00** [comment]
> I added your dependency to my project and I have gotten "Unsupported class file major version 60" error after run project.
> help me to solve this problem, thanks.

Hello, you need to use Java 16 to run this project, you are probably on Java 8 or 11

**Comment by alirezasbri** [comment]
Java Version: 16
Gradle Plugin Version: 4.2.1
Gradle Version: 6.7.1

And this is my build.gradle :

```
plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.yarinweb.whatsapptools"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_16
        targetCompatibility JavaVersion.VERSION_16
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    implementation 'com.github.auties00:whatsappweb4j:1.2'
}
```

**Comment by Auties00** [comment]
> Java Version: 16
> Gradle Plugin Version: 4.2.1
> Gradle Version: 6.7.1
> 
> And this is my build.gradle :
> 
> ```
> plugins {
>     id 'com.android.application'
> }
> 
> android {
>     compileSdkVersion 30
>     buildToolsVersion "30.0.3"
> 
>     defaultConfig {
>         applicationId "com.xxx.xxxx"
>         minSdkVersion 16
>         targetSdkVersion 30
>         versionCode 1
>         versionName "1.0"
> 
>         testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
>     }
> 
>     buildTypes {
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
>         }
>     }
>     compileOptions {
>         sourceCompatibility JavaVersion.VERSION_16
>         targetCompatibility JavaVersion.VERSION_16
>     }
> }
> 
> dependencies {
> 
>     implementation 'androidx.appcompat:appcompat:1.2.0'
>     implementation 'com.google.android.material:material:1.3.0'
>     implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
>     testImplementation 'junit:junit:4.13.2'
>     androidTestImplementation 'androidx.test.ext:junit:1.1.2'
>     androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
> 
>     implementation 'com.github.auties00:whatsappweb4j:1.2'
> }
> ```

Try to set the release option to target java 16

**Comment by alirezasbri** [comment]
How can i do it?
When I run app in debug mode on a emulator, get this error!

**Comment by GedMarc** [comment]
This is you running the wrong version of java - 
The maven and gradle options have been supplied - 

If you still have difficulties setting the java version which you are using..... get the idea? 
This isn't a school, it's an issue and help forum

**Comment by Auties00** [comment]
> How can i do it?
> When I run app in debug mode on a emulator, get this error!

what version of android are you using?

**Comment by alirezasbri** [comment]
> 
> 
> This is you running the wrong version of java -
> The maven and gradle options have been supplied -
> 
> If you still have difficulties setting the java version which you are using..... get the idea?
> This isn't a school, it's an issue and help forum,
> 
> Try an online Java course

Thank You.
Can I Try an Offline Java course or must be an online course?

**Comment by alirezasbri** [comment]
> 
> 
> > How can i do it?
> > When I run app in debug mode on a emulator, get this error!
> 
> what version of android are you using?

Api Version 30

**Comment by Auties00** [comment]
> Api Version 30

I doubt they are running Java 16 on Android 11 as it was released in September 2020, while Java 16 was released in March of this year.
