### ISSUE TITLE
I have the SE JDK 16 but it still shows me an error...

### ISSUE THREAD

**Issue by SLAYER-CODE** [Auties00/WhatsappWeb4j#30]
C:\Users\ADMIN\IdeaProjects\RobotWatsapa\src\main\java\org\example\whatsapp\Mainbot.java:3: error: cannot access WhatsappAPI
import it.auties.whatsapp4j.api.WhatsappAPI;
                               ^
  bad class file: C:\Users\ADMIN\.gradle\caches\modules-2\files-2.1\com.github.auties00\whatsappweb4j\2.1\a7a78d54b90b833432bfe24644b484f029cef90\whatsappweb4j-2.1.jar(/it/auties/whatsapp4j/api/WhatsappAPI.class)
    class file has wrong version 60.65535, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by Auties00** [comment]
> C:\Users\ADMIN\IdeaProjects\RobotWatsapa\src\main\java\org\example\whatsapp\Mainbot.java:3: error: cannot access WhatsappAPI
> import it.auties.whatsapp4j.api.WhatsappAPI;
> ^
> bad class file: C:\Users\ADMIN.gradle\caches\modules-2\files-2.1\com.github.auties00\whatsappweb4j\2.1\a7a78d54b90b833432bfe24644b484f029cef90\whatsappweb4j-2.1.jar(/it/auties/whatsapp4j/api/WhatsappAPI.class)
> class file has wrong version 60.65535, should be 55.0
> Please remove or make sure it appears in the correct subdirectory of the classpath.

Hello, what version of gradle are you using?

**Comment by Auties00** [comment]
> I was using version 7.0 which is compatible with jdk 16 but another problem arose
> 
> ![image](https://user-images.githubusercontent.com/51754456/123105226-41429000-d3fd-11eb-8595-b94d1a058ec8.png)
> 
> ![image](https://user-images.githubusercontent.com/51754456/123105380-61724f00-d3fd-11eb-96ed-d12e7931e489.png)
> 
> '''
> Unable to find method ''java.lang.String org.codehaus.groovy.runtime.StringGroovyMethods.capitalize(java.lang.String)''.
> Possible causes for this unexpected error include:
> Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
> Re-download dependencies and sync project (requires network)
> 
> The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
> Stop Gradle build processes (requires restart)
> 
> Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.
> 
> In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
> '''
> 
> It cannot import the necessary packages to use it with grandle, it only does it with version 4.8 with jdk 11 but there I get another compatibility error:
> 
> ![image](https://user-images.githubusercontent.com/51754456/123106038-ea898600-d3fd-11eb-8d2e-eb70ee2c939a.png)
> 
> I am almost new using grandle I hope it did not indicate something easy to solve ..
> 
> Now I have another problem when I change the JVM version from grandle:
> 
> ![image](https://user-images.githubusercontent.com/51754456/123117639-8a97dd00-d407-11eb-91a8-a73d8e32c534.png)

in the last image you have the correct version of java and the correct version of gradle, but you should add the argument --enable-preview to enable preview features

**Comment by SLAYER-CODE** [comment]
Even putting that fails

```
tasks.withTyp(Test) {
    jvmArgs += "--enable-preview"
}


compileJava {
    options.compilerArgs += ["--enable-preview"]
}
test {
    jvmArgs '--enable-preview'
}
```

**Comment by Auties00** [comment]
Did you fix this?

**Comment by SLAYER-CODE** [comment]
> ¿Arreglaste esto?

Si
