### ISSUE TITLE
WhatsappListener can add genQr method?

### ISSUE THREAD

**Issue by hwck** [Auties00/WhatsappWeb4j#34]
hi, WhatsappListener can add Generate whatsapp qr to stream ?
and can add get whatsapp number api like 
https://pedroslopez.me/whatsapp-web.js/Client.html#getNumberId

**Comment by hwck** [comment]
and can add checkout phone number is whatsapp number api?

**Comment by Auties00** [comment]
> hi, WhatsappListener can add Generate whatsapp qr to stream ?
> and can add get whatsapp number api like
> https://pedroslopez.me/whatsapp-web.js/Client.html#getNumberId

You would like a feature that allows the developer to specify how the qr code should be consumed, if I understand correctly. If that's the case I can add that. 

The second feature is already planned for release 2.1.2

**Comment by Auties00** [comment]
> hi, WhatsappListener can add Generate whatsapp qr to stream ?
> and can add get whatsapp number api like
> https://pedroslopez.me/whatsapp-web.js/Client.html#getNumberId

Version 2.1.2 contains these changes, tell me if they work as expected.

**Comment by hwck** [comment]
> > hi, WhatsappListener can add Generate whatsapp qr to stream ?
> > and can add get whatsapp number api like
> > https://pedroslopez.me/whatsapp-web.js/Client.html#getNumberId
> 
> Version 2.1.2 contains these changes, tell me if they work as expected.

hi ,genqr is not work 
![image](https://user-images.githubusercontent.com/19302107/125716866-f1932de3-7153-4f16-bce5-32d82e19fb9d.png)

can you change generate qr to WhatsappListener like onLoggedIn?

**Comment by Auties00** [comment]
> > > hi, WhatsappListener can add Generate whatsapp qr to stream ?
> > > and can add get whatsapp number api like
> > > https://pedroslopez.me/whatsapp-web.js/Client.html#getNumberId
> > 
> > 
> > Version 2.1.2 contains these changes, tell me if they work as expected.
> 
> hi ,genqr is not work
> ![image](https://user-images.githubusercontent.com/19302107/125716866-f1932de3-7153-4f16-bce5-32d82e19fb9d.png)
> 
> can you change generate qr to WhatsappListener like onLoggedIn and add param config qr refresh time?
> thanks !

I can implement the first request, though I cannot do the same for the last as QR codes expire after a fixed amount of time and that time interval is determined by WhatsappWeb's servers. The changes will be live tomorrow

**Comment by Auties00** [comment]
> > > hi, WhatsappListener can add Generate whatsapp qr to stream ?
> > > and can add get whatsapp number api like
> > > https://pedroslopez.me/whatsapp-web.js/Client.html#getNumberId
> > 
> > 
> > Version 2.1.2 contains these changes, tell me if they work as expected.
> 
> hi ,genqr is not work
> ![image](https://user-images.githubusercontent.com/19302107/125716866-f1932de3-7153-4f16-bce5-32d82e19fb9d.png)
> 
> can you change generate qr to WhatsappListener like onLoggedIn and add param config qr refresh time?
> thanks !

I've added the method onQRCode in version 2.2.1. Tell me if everything's working

**Comment by hwck** [comment]
> > > > hi, WhatsappListener can add Generate whatsapp qr to stream ?
> > > > and can add get whatsapp number api like
> > > > https://pedroslopez.me/whatsapp-web.js/Client.html#getNumberId
> > > 
> > > 
> > > Version 2.1.2 contains these changes, tell me if they work as expected.
> > 
> > 
> > hi ,genqr is not work
> > ![image](https://user-images.githubusercontent.com/19302107/125716866-f1932de3-7153-4f16-bce5-32d82e19fb9d.png)
> > can you change generate qr to WhatsappListener like onLoggedIn and add param config qr refresh time?
> > thanks !
> 
> I've added the method onQRCode in version 2.2.1. Tell me if everything's working

can add test case? i use method onQRCode not work

**Comment by Auties00** [comment]
> > > > > hi, WhatsappListener can add Generate whatsapp qr to stream ?
> > > > > and can add get whatsapp number api like
> > > > > https://pedroslopez.me/whatsapp-web.js/Client.html#getNumberId
> > > > 
> > > > 
> > > > Version 2.1.2 contains these changes, tell me if they work as expected.
> > > 
> > > 
> > > hi ,genqr is not work
> > > ![image](https://user-images.githubusercontent.com/19302107/125716866-f1932de3-7153-4f16-bce5-32d82e19fb9d.png)
> > > can you change generate qr to WhatsappListener like onLoggedIn and add param config qr refresh time?
> > > thanks !
> > 
> > 
> > I've added the method onQRCode in version 2.2.1. Tell me if everything's working
> 
> can add test case? i use method onQRCode not work

It doesn't work because the method onQRCode isn't called or because the QR code cannot be scanned?

**Comment by hwck** [comment]
thanks, it's work
