### ISSUE TITLE
Satatus view count

### ISSUE THREAD

**Issue by hamedsharifi** [Auties00/WhatsappWeb4j#42]
Hello
Can you help me how can I get Status view count in Whatsapp Web? I know it's not implemented in this library but I hope you can give some headings.

**Comment by Auties00** [comment]
> Hello
> Can you help me how can I get Status view count in Whatsapp Web? I know it's not implemented in this library but I hope you can give some headings.

Hello,
if you want to implement this feature on your own you can fork the project, download https://github.com/Auties00/whatsappweb4j-request-analyzer, find the nodes that whatsapp uses for said feature (they are printed on the console) and implement it on your own in the WhatsappAPI class. Then open a pull request and I'll merge the feature
