### ISSUE TITLE
QR Code isn't working on cmd

### ISSUE THREAD

**Issue by TheGeyik** [Auties00/WhatsappWeb4j#43]
Hello, QRCode isn't working on CMD but it's working on intellij development console. Can you give me some information about why it's not working with cmd? Is because of bitmatrix?

https://imgur.com/FWqKoS5

**Comment by Auties00** [comment]
> Hello, QRCode isn't working on CMD but it's working on intellij development console. Can you give me some information about why it's not working with cmd? Is because of bitmatrix?
> 
> https://imgur.com/FWqKoS5

This looks weird, those should be ASCII characters. What version of windows are you using ?

**Comment by TheGeyik** [comment]
Windows 10 x64 and runned console with
`java -Xmx128M -jar --enable-preview -Dfile.encoding=UTF-8 AutoWPMsg-1.0-SNAPSHOT.jar`

**Comment by Auties00** [comment]
> Windows 10 x64 and runned console with
> `java -Xmx128M -jar --enable-preview -Dfile.encoding=UTF-8 AutoWPMsg-1.0-SNAPSHOT.jar`
> 
> ![image](https://user-images.githubusercontent.com/22749769/133443823-331f1386-fcbc-4c3f-abba-69fa1275654c.png)

kind of weird, i'll look into it

**Comment by TheGeyik** [comment]
I've researched a bit and find Windows Command Prompt isn't supporting ANSI.
So i've made JFrame for QRCode with image function.
![image](https://user-images.githubusercontent.com/22749769/133502018-8e615bd1-82b6-486a-a1fc-5bd3ec431355.png)
That's enough for me, but I thought I'd let you know.
