### ISSUE TITLE
How can I get WhatsappKeysManager parameter?

### ISSUE THREAD

**Issue by SjacoSun** [Auties00/WhatsappWeb4j#44]
Such as clientToken serverToken macKey

**Comment by Auties00** [comment]
> Such as clientToken serverToken macKey



> Such as clientToken serverToken macKey

Create a new instance of Whatsapp api and use the method keys()
https://www.javadoc.io/static/com.github.auties00/whatsappweb4j/2.2.1/whatsapp4j/it/auties/whatsapp4j/whatsapp/WhatsappAPI.html#keys()
