### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jayp84847** [Auties00/WhatsappWeb4j#48]
Need some help.

**Comment by Auties00** [comment]
> Need some help.

Tell me

**Comment by jayp84847** [comment]
Yet I am working on project with dlib but it's not stable and accurate so the result is very poor. I did my best to get solution but nope. Then I got hyprsense but its my bad luck that epic games acquired hyprsense so nope.

I saw your comment releted to hyprsense. That's why I reached to you. Like can you share me your hyprsense unity sdk please. And if you purchased it and not working with it can you please share it with me I will pay you for that too.

I am in college second year. And its very important for me. Its one of my very important project. 

Please help me if you can please.

**Comment by Auties00** [comment]
> Yet I am working on project with dlib but it's not stable and accurate so the result is very poor. I did my best to get solution but nope. Then I got hyprsense but its my bad luck that epic games acquired hyprsense so nope.
> 
> I saw your comment releted to hyprsense. That's why I reached to you. Like can you share me your hyprsense unity sdk please. And if you purchased it and not working with it can you please share it with me I will pay you for that too.
> 
> I am in college second year. And its very important for me. Its one of my very important project.
> 
> Please help me if you can please.

I just tried it sorry, i didn't purchase it

**Comment by Auties00** [comment]
> Yet I am working on project with dlib but it's not stable and accurate so the result is very poor. I did my best to get solution but nope. Then I got hyprsense but its my bad luck that epic games acquired hyprsense so nope.
> 
> I saw your comment releted to hyprsense. That's why I reached to you. Like can you share me your hyprsense unity sdk please. And if you purchased it and not working with it can you please share it with me I will pay you for that too.
> 
> I am in college second year. And its very important for me. Its one of my very important project.
> 
> Please help me if you can please.

I just tried it sorry, i didn't purchase it

**Comment by jayp84847** [comment]
Can you share trial sdk please

**Comment by Auties00** [comment]
> Can you share trial sdk please

It expired

**Comment by jayp84847** [comment]
If you still have it's file for unity can you please share it?
