### ISSUE TITLE
I got this problem and I don't know how to solve it.

### ISSUE THREAD

**Issue by OnFireMohamed** [Auties00/WhatsappWeb4j#50]
![screenshot_5](https://user-images.githubusercontent.com/67835053/139593456-eeb45f18-f498-44ce-98e0-5dcb61e57fd5.png)
Hello,
I got this problem when I want to run the code.
Any one knows the solution?

**Comment by Auties00** [comment]
> ![screenshot_5](https://user-images.githubusercontent.com/67835053/139593456-eeb45f18-f498-44ce-98e0-5dcb61e57fd5.png) Hello, I got this problem when I want to run the code. Any one knows the solution?

As the error says, you need to enable preview options by adding --enable-preview to your command line. You can do so in IntelliJ by click Run -> Edit Configurations ->Modify Options -> VM Options -> --enable-preview
