### ISSUE TITLE
NullPointerException - Cannot evaluate WhatsappWebSocket.toString()

### ISSUE THREAD

**Issue by stwe** [Auties00/WhatsappWeb4j#52]
This is the code

```java
    public static void main(String[] args) {
        var api = new WhatsappAPI();
        api.registerListener(new MyListener(api));
        api.connect();
    }
```

```java
public class MyListener implements WhatsappListener {
    private final WhatsappAPI api;
    public MyListener(WhatsappAPI api){
        this.api = api;
    }

    public void onLoggedIn(@NonNull UserInformationResponse info) {
        System.out.println("Connected :)");
    }

    public void onChats(){
        System.out.printf("Recived chats: %s%n", api.manager().chats());
    }
}
```

And this is the error message:

![issue](https://user-images.githubusercontent.com/2964748/140547602-da9dd01b-d6d5-48d1-923f-5a942abf9f40.png)

Any ideas what I'm doing wrong?

**Comment by Auties00** [comment]
> This is the code
> 
> ```java
>     public static void main(String[] args) {
>         var api = new WhatsappAPI();
>         api.registerListener(new MyListener(api));
>         api.connect();
>     }
> ```
> 
> ```java
> public class MyListener implements WhatsappListener {
>     private final WhatsappAPI api;
>     public MyListener(WhatsappAPI api){
>         this.api = api;
>     }
> 
>     public void onLoggedIn(@NonNull UserInformationResponse info) {
>         System.out.println("Connected :)");
>     }
> 
>     public void onChats(){
>         System.out.printf("Recived chats: %s%n", api.manager().chats());
>     }
> }
> ```
> 
> And this is the error message:
> 
> ![issue](https://user-images.githubusercontent.com/2964748/140547602-da9dd01b-d6d5-48d1-923f-5a942abf9f40.png)
> 
> Any ideas what I'm doing wrong?

You can't debug your code using IntelliJ, that's what you mean?

**Comment by stwe** [comment]
No, I mean the error message in red on the picture:

`socket = Method threw 'java.lang.NullPointerException' exception. Cannot evaluate it.auties.whatsapp4j.manager.WhatsappDataManager.toString()`

I can therefore not read out any chats / contacts or phone numbers.
WhatsApp Web is running in a browser. Is my code above the right one to connect to?

**Comment by Auties00** [comment]
> No, I mean the error message in red on the picture:
> 
> `socket = Method threw 'java.lang.NullPointerException' exception. Cannot evaluate it.auties.whatsapp4j.manager.WhatsappDataManager.toString()`
> 
> I can therefore not read out any chats / contacts or phone numbers. WhatsApp Web is running in a browser. Is my code above the right one to connect to?

I probably didn't exclude the nullable fields from the toString method, that's why the debugger in throwing that error. I'll fix it once I'm done with the multi device beta

**Comment by stwe** [comment]
OK thanks. Is that also the explanation why I am not getting a connection?

**Comment by Auties00** [comment]
> OK thanks. Is that also the explanation why I am not getting a connection?

What do you mean?

**Comment by stwe** [comment]
I have `https://web.whatsapp.com/` open in the browser and it is connected to my mobile phone. This is how I can write with my friends. Now the question is what I can do with your code here. 

```java
    public static void main(String[] args) {
        var api = new WhatsappAPI();
        api.registerListener(new MyListener(api));
        api.connect();
    }
```

Should it connect to the websocket and show me the chat? If I do it like that, nothing will happen. So the question is: how can I read out the chat / display messages?

**Comment by Auties00** [comment]
> I have `https://web.whatsapp.com/` open in the browser and it is connected to my mobile phone. This is how I can write with my friends. Now the question is what I can do with your code here.
> 
> ```java
>     public static void main(String[] args) {
>         var api = new WhatsappAPI();
>         api.registerListener(new MyListener(api));
>         api.connect();
>     }
> ```
> 
> Should it connect to the websocket and show me the chat? If I do it like that, nothing will happen. So the question is: how can I read out the chat / display messages?

Read the documentation, you need to register a listener

**Comment by stwe** [comment]
I had that. This is my listener (from your documentation):

```java
public class MyListener implements WhatsappListener {
    private final WhatsappAPI api;
    public MyListener(WhatsappAPI api){
        this.api = api;
    }

    public void onLoggedIn(@NonNull UserInformationResponse info) {
        System.out.println("Connected :)");
    }

    public void onChats(){
        System.out.printf("Recived chats: %s%n", api.manager().chats());
    }
}

```

**Comment by Auties00** [comment]
> I had that. This is my listener (from your documentation):
> 
> ```java
> public class MyListener implements WhatsappListener {
>     private final WhatsappAPI api;
>     public MyListener(WhatsappAPI api){
>         this.api = api;
>     }
> 
>     public void onLoggedIn(@NonNull UserInformationResponse info) {
>         System.out.println("Connected :)");
>     }
> 
>     public void onChats(){
>         System.out.printf("Recived chats: %s%n", api.manager().chats());
>     }
> }
> ```

This looks right. Is any error being thrown?

**Comment by Daligz** [comment]
> OK thanks. Is that also the explanation why I am not getting a connection?

I think I have the same error, it just never connects, it doesn't work @Auties00

**Comment by Auties00** [comment]
> > OK thanks. Is that also the explanation why I am not getting a connection?
> 
> I think I have the same error, it just never connects, it doesn't work @Auties00
> 
> I try to connect but I never receive a qr code, the code is similar to the example and no errors are displayed.



> I had that. This is my listener (from your documentation):
> 
> ```java
> public class MyListener implements WhatsappListener {
>     private final WhatsappAPI api;
>     public MyListener(WhatsappAPI api){
>         this.api = api;
>     }
> 
>     public void onLoggedIn(@NonNull UserInformationResponse info) {
>         System.out.println("Connected :)");
>     }
> 
>     public void onChats(){
>         System.out.printf("Recived chats: %s%n", api.manager().chats());
>     }
> }
> ```

Should be fixed in 2.2.2. Can you please double check?

**Comment by stwe** [comment]
looks good: now I see a large QR code all over the screen. Offtopic: Is it possible for the code to be displayed a little smaller?

**Comment by Auties00** [comment]
> looks good: now I see a large QR code all over the screen. Offtopic: Is it possible for the code to be displayed a little smaller?

There is a method you can implement called onQRCode. I honestly looked anywhere how to print it smaller but I didn't find anything.  There is most definitely a way though

**Comment by stwe** [comment]
It's a fine new day; it's the same code as yesterday. But what I don't see is a QR code. WTF.

**Comment by SheikhZayed** [comment]
i'm able to get the qr code, but while scanning the qr code from whatsapp it does not initiate the session, execution calls isLoggedIn with userinfo as null

**Comment by SheikhZayed** [comment]
> looks good: now I see a large QR code all over the screen. Offtopic: Is it possible for the code to be displayed a little smaller?

use this code to print the qr to ur path 

` BufferedImage image = MatrixToImageWriter.toBufferedImage(qr);
        File outputfile = new File("image.jpg");
        ImageIO.write(image, "jpg", outputfile);`
