### ISSUE TITLE
The connection is never made

### ISSUE THREAD

**Issue by Daligz** [Auties00/WhatsappWeb4j#53]
I already tried it with example codes but it never connects, I don't know if it's my problem but it never shows any error, this worked a few days ago, then it showed an error but some things kept working, now nothing worked. :(

**Comment by Auties00** [comment]
> I already tried it with example codes but it never connects, I don't know if it's my problem but it never shows any error, this worked a few days ago, then it showed an error but some things kept working, now nothing worked. :(



> I already tried it with example codes but it never connects, I don't know if it's my problem but it never shows any error, this worked a few days ago, then it showed an error but some things kept working, now nothing worked. :(

Related to https://github.com/Auties00/WhatsappWeb4j/issues/51

This afternoon I'll publish the updated version
