### ISSUE TITLE
QR code is not regenerated when I close the client and logout from WhatsApp on device

### ISSUE THREAD

**Issue by brunoaduarte** [Auties00/WhatsappWeb4j#56]
I've successfully connected and logged in (QR code scanned ok) in the first time, but if I close the client and try opening it again it will not show the QR code anymore.

I've tried restarting the computers and also deleted the "AppData\Local\Temp" folder.
Does the library saves the keys or some other temp file somewhere else in the computer?

```
package com.test.wsclientnew;

import org.springframework.boot.autoconfigure.SpringBootApplication;

import it.auties.whatsapp4j.whatsapp.WhatsappAPI;

@SpringBootApplication
public class WsclientNewApplication {

	public static void main(String[] args) {

		System.out.println("STARTING...");

		WhatsappAPI api = new WhatsappAPI();
		api.registerListener(new WsClientWhatsappListener());
		api.connect();

		api.hasWhatsapp("xxxxxxxxxxxxxx");

		try {
			Thread.sleep(5000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		api.disconnect();
	}
}

```

```
package com.test.wsclientnew;

import com.google.zxing.common.BitMatrix;

import it.auties.whatsapp4j.listener.RegisterListener;
import it.auties.whatsapp4j.listener.WhatsappListener;
import it.auties.whatsapp4j.response.impl.json.UserInformationResponse;
import lombok.NonNull;

@RegisterListener
public class WsClientWhatsappListener implements WhatsappListener {

	@Override
	public void onQRCode(@NonNull BitMatrix qr) {
		System.out.println("GENERATING QR CODE...)");
		WhatsappListener.super.onQRCode(qr);
	}

	@Override
	public void onLoggedIn(@NonNull UserInformationResponse info) {
		System.out.println("Connected :)");
	}

	@Override
	public void onDisconnected() {
		System.out.println("Disconnected :(");
	}

}
```

**Console output**

```
STARTING...
<AFTER 5 SECONDS>
Exception in thread "main" java.lang.IllegalStateException: WhatsappAPI: Cannot terminate the connection with whatsapp as it doesn't exist
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at it.auties.whatsapp4j.utils.internal.Validate.isTrue(Validate.java:49)
	at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.disconnect(WhatsappWebSocket.java:247)
	at it.auties.whatsapp4j.whatsapp.WhatsappAPI.disconnect(WhatsappAPI.java:120)
	at com.test.wsclientnew.WsclientNewApplication.main(WsclientNewApplication.java:26)

```

It should not even log in, as I've logged out this client on the device.

**Comment by Auties00** [comment]
> I've successfully connected and logged in (QR code scanned ok) in the first time, but if I close the client and try opening it again it will not show the QR code anymore.
> 
> I've tried restarting the computers and also deleted the "AppData\Local\Temp" folder. Does the library saves the keys or some other temp file somewhere else in the computer?
> 
> ```
> package com.test.wsclientnew;
> 
> import org.springframework.boot.autoconfigure.SpringBootApplication;
> 
> import it.auties.whatsapp4j.whatsapp.WhatsappAPI;
> 
> @SpringBootApplication
> public class WsclientNewApplication {
> 
> 	public static void main(String[] args) {
> 
> 		System.out.println("STARTING...");
> 
> 		WhatsappAPI api = new WhatsappAPI();
> 		api.registerListener(new WsClientWhatsappListener());
> 		api.connect();
> 
> 		api.hasWhatsapp("xxxxxxxxxxxxxx");
> 
> 		try {
> 			Thread.sleep(5000);
> 		} catch (InterruptedException e) {
> 			e.printStackTrace();
> 		}
> 		api.disconnect();
> 	}
> }
> ```
> 
> ```
> package com.test.wsclientnew;
> 
> import com.google.zxing.common.BitMatrix;
> 
> import it.auties.whatsapp4j.listener.RegisterListener;
> import it.auties.whatsapp4j.listener.WhatsappListener;
> import it.auties.whatsapp4j.response.impl.json.UserInformationResponse;
> import lombok.NonNull;
> 
> @RegisterListener
> public class WsClientWhatsappListener implements WhatsappListener {
> 
> 	@Override
> 	public void onQRCode(@NonNull BitMatrix qr) {
> 		System.out.println("GENERATING QR CODE...)");
> 		WhatsappListener.super.onQRCode(qr);
> 	}
> 
> 	@Override
> 	public void onLoggedIn(@NonNull UserInformationResponse info) {
> 		System.out.println("Connected :)");
> 	}
> 
> 	@Override
> 	public void onDisconnected() {
> 		System.out.println("Disconnected :(");
> 	}
> 
> }
> ```
> 
> **Console output**
> 
> ```
> STARTING...
> <AFTER 5 SECONDS>
> Exception in thread "main" java.lang.IllegalStateException: WhatsappAPI: Cannot terminate the connection with whatsapp as it doesn't exist
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
> 	at it.auties.whatsapp4j.utils.internal.Validate.isTrue(Validate.java:49)
> 	at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.disconnect(WhatsappWebSocket.java:247)
> 	at it.auties.whatsapp4j.whatsapp.WhatsappAPI.disconnect(WhatsappAPI.java:120)
> 	at com.test.wsclientnew.WsclientNewApplication.main(WsclientNewApplication.java:26)
> ```
> 
> It should not even log in, as I've logged out this client on the device.

This is how it's supposed to be, the session is cached by WhatsappKeysManager so you don't have to rescan the qr code every time. If you wish to do so, you can by creating a new WhatsappKeysManager from an empty json or by calling api.keys().deleteKeysFromMemory()

**Comment by brunoaduarte** [comment]
> This is how it's supposed to be, the session is cached by WhatsappKeysManager so you don't have to rescan the qr code every time. If you wish to do so, you can by creating a new WhatsappKeysManager from an empty json or by calling api.keys().deleteKeysFromMemory()

Even if I call this method, QR code is not shown anymore on my computer. It's somehow stuck before the qr code creation. Not even the "onQRCode" method is called from the listener. That's weird.
