### ISSUE TITLE
Unreliable Whatsapp Socket Connection

### ISSUE THREAD

**Issue by huyuanliang** [Auties00/WhatsappWeb4j#57]
2.2.1 unable to obtain QR code, that is, unable to log in. The problem is the same when updating to 2.2.2

**Comment by huyuanliang** [comment]
@Auties00

**Comment by Auties00** [comment]
> 2.2.1 unable to obtain QR code, that is, unable to log in. The problem is the same when updating to 2.2.2

Looks weird. I have a bot completely working an everyone else has no problem. Can you please share the error that is thrown ?

**Comment by stwe** [comment]
> working an everyone else has no problem

https://github.com/Auties00/WhatsappWeb4j/issues/52

See my last comment. Same problem.

**Comment by Auties00** [comment]
> > working an everyone else has no problem
> 
> #52
> 
> See my last comment. Same problem.

Are you by any chance using the MD beta?

**Comment by huyuanliang** [comment]
@Auties00 
Thank you. The program is normal today. There may be a problem with the network. I use VPN.

**Comment by stwe** [comment]
Absolutely crazy. Today it works again.

**Comment by Auties00** [comment]
> Absolutely crazy. Today it works again.

I'm actually confused. If you find any way to reproduce the issue, I'm more than available to fix it. The only thing that comes to my mind is that it's Whatsapp doing some testing for the multi device beta, so maybe you were using it by default yesterday and didn't even realize

**Comment by Auties00** [comment]
Any updates?

**Comment by Auties00** [comment]
Should be fixed in latest version
