### ISSUE TITLE
Scanning generated QR does not initiate a session

### ISSUE THREAD

**Issue by SheikhZayed** [Auties00/WhatsappWeb4j#58]
i'm able to get the qr code, but while scanning the qr code from whatsapp it does not initiate the session, execution calls isLoggedIn with userinfo as null

_Originally posted by @SheikhZayed in https://github.com/Auties00/WhatsappWeb4j/issues/52#issuecomment-967718394_

**Comment by Auties00** [comment]
> i'm able to get the qr code, but while scanning the qr code from whatsapp it does not initiate the session, execution calls isLoggedIn with userinfo as null
> 
> _Originally posted by @SheikhZayed in [#52 (comment)](https://github.com/Auties00/WhatsappWeb4j/issues/52#issuecomment-967718394)_

Are you using the multidevice beta?
(send a screenshot of your connection tab in WhatsApp, it might be enabled by default in your region)

**Comment by SheikhZayed** [comment]
No, I'm not using multi device..

I get the following error now
![image](https://user-images.githubusercontent.com/8774293/141688873-fcd91147-8db4-4113-8cbe-ce89e62e9d7c.png)

**Comment by Auties00** [comment]
> No, I'm not using multi device..
> 
> I get the following error now ![image](https://user-images.githubusercontent.com/8774293/141688873-fcd91147-8db4-4113-8cbe-ce89e62e9d7c.png)

I'm using Android. Any chance you can try to use one of them? Maybe it's a platform related issue
