### ISSUE TITLE
Using problems in JavaFX

### ISSUE THREAD

**Issue by huyuanliang** [Auties00/WhatsappWeb4j#61]
2.2.1 use OK ，but 2.2.2 Module not found。_requires whatsapp4j;_you can click to enter in idea

**Comment by huyuanliang** [comment]
D:\workCode\idea\bigDog\src\main\java\module-info.java:21:14
java: module not found: whatsapp4j

**Comment by Auties00** [comment]
> D:\workCode\idea\bigDog\src\main\java\module-info.java:21:14 java: module not found: whatsapp4j

Try with it.auties.whatsapp4j

**Comment by huyuanliang** [comment]
I use jdk16 and change it to jdk17 ，that's it

**Comment by Auties00** [comment]
> thank you ，unrecognized it.auties.whatsapp4j

I'm sure that it should be whatsapp4j. Can you try to clean compile your project?
