### ISSUE TITLE
this connection has been closed.

### ISSUE THREAD

**Issue by huyuanliang** [Auties00/WhatsappWeb4j#64]
If the mobile phone is not connected for a long time after login, an error "this connection has been closed." will be reported. How do I catch this error and reconnect the mobile phone? Lost connections are also not listened for in onDisconnected

**Comment by huyuanliang** [comment]
@Auties00

**Comment by hamedsharifi** [comment]
Your device should be online all then time. You can not login with the library and go offline with Whatsapp on the mobile.

**Comment by Auties00** [comment]
> @Auties00 can you help me

The API should reconnect automatically by default if the connection is lost and the device is still online

**Comment by huyuanliang** [comment]
the device is still online，but don't seng message. if want to send messge; I need to reconnect, but I don't know when it's closed

**Comment by dennialdi** [comment]
hi denni, thank you for making this very helpful library, I also experienced the same issue when for a long time there was no incoming chat (idle) but my smartphone was still alive and online. My application is getting an exception like the following snippet:

`Exception in thread "Thread-574" java.lang.IllegalStateException: The connection has been closed.`
 `at org.glassfish.tyrus.core.TyrusSession.checkConnectionState(TyrusSession.java:513)`
`at org.glassfish.tyrus.core.TyrusSession.getAsyncRemote(TyrusSession.java:183)`
`at it.auties.whatsapp4j.request.model.JsonRequest.send(JsonRequest.java:59)`
`at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.createMediaConnection(WhatsappWebSocket.java:401)`
` at java.base/java.lang.Thread.run(Thread.java:833)`

i tried to detect this exception with try catch in main class, hoping to use the reconnect function when this exception is detected but it doesn't work.

your help means a lot, thank you.

**Comment by Auties00** [comment]
> hi @Auties00 , thank you for making this very helpful library, I also experienced the same issue when for a long time there was no incoming chat (idle) but my smartphone was still alive and online. My application is getting an exception like the following snippet:
> 
> `Exception in thread "Thread-574" java.lang.IllegalStateException: The connection has been closed.` `at org.glassfish.tyrus.core.TyrusSession.checkConnectionState(TyrusSession.java:513)` `at org.glassfish.tyrus.core.TyrusSession.getAsyncRemote(TyrusSession.java:183)` `at it.auties.whatsapp4j.request.model.JsonRequest.send(JsonRequest.java:59)` `at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.createMediaConnection(WhatsappWebSocket.java:401)` ` at java.base/java.lang.Thread.run(Thread.java:833)`
> 
> i tried to detect this exception with try catch in main class, hoping to use the reconnect function when this exception is detected but it doesn't work.
> 
> your help means a lot, thank you.

Probably tyrus kills the socket after a certain idle period. This is weird though considering that a ping request should be sent every 30 seconds. Do you have precise timings for when this issue starts to arise?

**Comment by dennialdi** [comment]
> > hi @Auties00 , thank you for making this very helpful library, I also experienced the same issue when for a long time there was no incoming chat (idle) but my smartphone was still alive and online. My application is getting an exception like the following snippet:
> > `Exception in thread "Thread-574" java.lang.IllegalStateException: The connection has been closed.` `at org.glassfish.tyrus.core.TyrusSession.checkConnectionState(TyrusSession.java:513)` `at org.glassfish.tyrus.core.TyrusSession.getAsyncRemote(TyrusSession.java:183)` `at it.auties.whatsapp4j.request.model.JsonRequest.send(JsonRequest.java:59)` `at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.createMediaConnection(WhatsappWebSocket.java:401)` ` at java.base/java.lang.Thread.run(Thread.java:833)`
> > i tried to detect this exception with try catch in main class, hoping to use the reconnect function when this exception is detected but it doesn't work.
> > your help means a lot, thank you.
> 
> Probably tyrus kills the socket after a certain idle period. This is weird though considering that a ping request should be sent every 30 seconds. Do you have precise timings for when this issue starts to arise?

I deployed my application on vps twice, the first was idle for about 1 hour and I got the exception message, while the second was idle for about 5 hours and I got the exception message.

**Comment by Auties00** [comment]
> > > hi @Auties00 , thank you for making this very helpful library, I also experienced the same issue when for a long time there was no incoming chat (idle) but my smartphone was still alive and online. My application is getting an exception like the following snippet:
> > > `Exception in thread "Thread-574" java.lang.IllegalStateException: The connection has been closed.` `at org.glassfish.tyrus.core.TyrusSession.checkConnectionState(TyrusSession.java:513)` `at org.glassfish.tyrus.core.TyrusSession.getAsyncRemote(TyrusSession.java:183)` `at it.auties.whatsapp4j.request.model.JsonRequest.send(JsonRequest.java:59)` `at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.createMediaConnection(WhatsappWebSocket.java:401)` ` at java.base/java.lang.Thread.run(Thread.java:833)`
> > > i tried to detect this exception with try catch in main class, hoping to use the reconnect function when this exception is detected but it doesn't work.
> > > your help means a lot, thank you.
> > 
> > 
> > Probably tyrus kills the socket after a certain idle period. This is weird though considering that a ping request should be sent every 30 seconds. Do you have precise timings for when this issue starts to arise?
> 
> I deployed my application on vps twice, the first was idle for about 1 hour and I got the exception message, while the second was idle for about 5 hours and I got the exception message.

Can you try and run it locally to see how much time it takes. I have one bot running 24/7 and never run into this issue for some weird reason

**Comment by zhengshengjie666** [comment]
我用多设备版本的whatsapp扫描二维码报错了，请帮忙分析下原因？
exception in thread "ForkJoinPool.commonPool-worker-1" java.lang.IllegalStateException: The connection has been closed.
	at org.glassfish.tyrus.core.TyrusSession.checkConnectionState(TyrusSession.java:513)
	at org.glassfish.tyrus.core.TyrusSession.getAsyncRemote(TyrusSession.java:183)
	at whatsapp4j/it.auties.whatsapp4j.request.model.JsonRequest.send(JsonRequest.java:59)
	at whatsapp4j/it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.sendInitialRequest(WhatsappWebSocket.java:100)
	at whatsapp4j/it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.lambda$scheduleQrCodeUpdate$1(WhatsappWebSocket.java:134)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by Auties00** [comment]
> 我用多设备版本的whatsapp扫描二维码报错了，请帮忙分析下原因？ exception in thread "ForkJoinPool.commonPool-worker-1" java.lang.IllegalStateException: The connection has been closed. at org.glassfish.tyrus.core.TyrusSession.checkConnectionState(TyrusSession.java:513) at org.glassfish.tyrus.core.TyrusSession.getAsyncRemote(TyrusSession.java:183) at whatsapp4j/it.auties.whatsapp4j.request.model.JsonRequest.send(JsonRequest.java:59) at whatsapp4j/it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.sendInitialRequest(WhatsappWebSocket.java:100) at whatsapp4j/it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.lambda$scheduleQrCodeUpdate$1(WhatsappWebSocket.java:134) at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

Fixed in the latest release
