### ISSUE TITLE
QR code not regenerated on initial request

### ISSUE THREAD

**Issue by bartoszgadzala** [Auties00/WhatsappWeb4j#68]
In case QR code was not scanned within TTL (usually 15s) WhatsappWeb4j regenerated the same code, as `ref` is the same, as `InitialRequest`'s response is reused. The only way to fix that is currently restarting whole app. I've prepared PR with potential fix: #67

**Comment by Auties00** [comment]
Merged. Thanks for your contribution!

**Comment by bartoszgadzala** [comment]
@Auties00 do you plan to release it?

**Comment by Auties00** [comment]
> @Auties00 do you plan to release it?

Yep. There is another bug fix that I need to finish before. As soon as I do it, I'll release it
