### ISSUE TITLE
Discord support

### ISSUE THREAD

**Issue by Yuhtin** [Auties00/WhatsappWeb4j#69]
Why not create a discord for fast support and q&a?

**Comment by Auties00** [comment]
> Why not create a discord for fast support and q&a?

There is already the MD discord, perhaps I should add a link in the readme?

**Comment by Yuhtin** [comment]
> > Why not create a discord for fast support and q&a?
> 
> There is already the MD discord, perhaps I should add a link in the readme?

yeah, can you send here? i have some questions to do, i dont like use issues to make questions 😔

**Comment by Auties00** [comment]
> > > Why not create a discord for fast support and q&a?
> > 
> > 
> > There is already the MD discord, perhaps I should add a link in the readme?
> 
> great, for now, can you send here? i have some questions to do, i dont like use issues to make questions 😔

https://discord.gg/e7dxV8aA
