### ISSUE TITLE
whatsapp mutidevicebeta分支的代码依赖找不到了

### ISSUE THREAD

**Issue by zhengshengjie666** [Auties00/WhatsappWeb4j#70]
![image](https://user-images.githubusercontent.com/81298032/145373786-256ca06f-ddaf-401a-9abf-62432228ed34.png)
![image](https://user-images.githubusercontent.com/81298032/145383443-228ccd95-da16-4377-9bee-469e2c0953eb.png)

**Comment by Auties00** [comment]
> ![image](https://user-images.githubusercontent.com/81298032/145373786-256ca06f-ddaf-401a-9abf-62432228ed34.png) ![image](https://user-images.githubusercontent.com/81298032/145383443-228ccd95-da16-4377-9bee-469e2c0953eb.png)

You have to use the prior version of protobuf as the one isn't released yet

**Comment by zhengshengjie666** [comment]
https://github.com/Auties00/WhatsappWeb4j/issues/75

**Comment by zhengshengjie666** [comment]
您好，multidevicebeta分支的代码什么时候发布呢？
