### ISSUE TITLE
the group's jid doesn't contain string'-' now

### ISSUE THREAD

**Issue by hmbyl** [Auties00/WhatsappWeb4j#78]
public static boolean isGroup(@NonNull String jid) {
        if (jid == null) {
            throw new NullPointerException("jid is marked non-null but is null");
        } else {
            return jid.contains("-");//this should change to  "return jid.contains("@g")",because the jid of a group looks like 'XXXXX@g.us' now
        }
    }

**Comment by Auties00** [comment]
> public static boolean isGroup(@nonnull String jid) { if (jid == null) { throw new NullPointerException("jid is marked non-null but is null"); } else { return jid.contains("-");//this should change to "return jid.contains("@g")",because the jid of a group looks like '[XXXXX@g.us](mailto:XXXXX@g.us)' now } }

You are indeed right, I patched this on the multi device branch but not here. What approach do you suggest?

**Comment by hmbyl** [comment]
Thanks for the great work on this project, I just want to know when will multi device branch be ready?

**Comment by Auties00** [comment]
> Thanks for the great work on this project, I just want to know when will multi device branch be ready?

Uhm I don't know, probably a few weeks from now?

**Comment by Auties00** [comment]
Fixed in 2.2.5
