### ISSUE TITLE
Does WhatsappDataManager support multi WhatsappAPI?

### ISSUE THREAD

**Issue by hmbyl** [Auties00/WhatsappWeb4j#80]
public class WhatsappDataManager {
    private static final WhatsappDataManager singletonInstance = new WhatsappDataManager(Executors.newSingleThreadExecutor(), new ArrayList(), new ArrayList(), new ArrayList(), new ArrayList(), Instant.now().getEpochSecond());
   }

I found that WhatsappDataManager use signle instance, so how about if I have multi WhatsappAPI?

**Comment by Auties00** [comment]
> 

It is currently not supported in the master branch, the multi branch though supports this
