### ISSUE TITLE
the web socket always diss connect after scan the QR code

### ISSUE THREAD

**Issue by hmbyl** [Auties00/WhatsappWeb4j#82]

**Comment by Auties00** [comment]
> _No description provided._

Can you send a log and specify the version you are using?

**Comment by fisher926** [comment]
Same problem.
jdk
![Java WA](https://user-images.githubusercontent.com/63165551/146659240-ed57d2c1-76c7-4889-9052-f32a4a8b6d2a.png)
-17

**Comment by Auties00** [comment]
> Same problem. jdk-17 ![Java WA](https://user-images.githubusercontent.com/63165551/146659240-ed57d2c1-76c7-4889-9052-f32a4a8b6d2a.png)

Can you show me the code you are using and what version of the library you are using(not Java)

**Comment by fisher926** [comment]
Using - com.github.auties00:whatsappweb4j:2.2.5

`import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import it.auties.whatsapp4j.listener.WhatsappListener;
import it.auties.whatsapp4j.response.impl.json.UserInformationResponse;
import it.auties.whatsapp4j.whatsapp.WhatsappAPI;
import it.auties.whatsapp4j.whatsapp.WhatsappConfiguration;
import lombok.NonNull;

import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Path;

public class Main {

    public static void main(String[] args) {
        Main main = new Main();
        main.whatsapp();
    }

    private void whatsapp() {
        WhatsappConfiguration configuration = WhatsappConfiguration.builder()
                .whatsappUrl("wss://web.whatsapp.com/ws")
                .requestTag("requestTag")
                .description("Whatsapp4j")
                .shortDescription("W4J")
                .reconnectWhenDisconnected((reason) -> true)
                .async(true)
                .build();

        WhatsappAPI api = new WhatsappAPI(configuration);
        api.registerListener(new WaStatusListener());
        api.connect();
    }

    private class WaStatusListener implements WhatsappListener {
        @Override
        public void onQRCode(@NonNull BitMatrix qr) {
            Path path = FileSystems.getDefault().getPath("qr.png");

            try {
                MatrixToImageWriter.writeToPath(qr, "PNG", path);
            } catch (IOException e) {
                e.printStackTrace();
            }

            WhatsappListener.super.onQRCode(qr);
        }

        public void onLoggedIn(@NonNull UserInformationResponse info) {
            System.out.println("Connected :)");
        }

        public void onDisconnected() {
            System.out.println("Disconnected :(");
        }
    }
}
`

**Comment by SheikhZayed** [comment]
Same issue with the following exception 

`Exception in thread "ForkJoinPool.commonPool-worker-7" java.lang.NullPointerException: WhatsappAPI: The session linked to the WebSocket is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.session(WhatsappWebSocket.java:486)
	at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.lambda$scheduleQrCodeUpdate$1(WhatsappWebSocket.java:134)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)`

**Comment by Auties00** [comment]
> import com.google.zxing.client.j2se.MatrixToImageWriter; import com.google.zxing.common.BitMatrix; import it.auties.whatsapp4j.listener.WhatsappListener; import it.auties.whatsapp4j.response.impl.json.UserInformationResponse; import it.auties.whatsapp4j.whatsapp.WhatsappAPI; import it.auties.whatsapp4j.whatsapp.WhatsappConfiguration; import lombok.NonNull;
> 
> import java.io.IOException; import java.nio.file.FileSystems; import java.nio.file.Path;
> 
> public class Main {
> 
> ```
> public static void main(String[] args) {
>     Main main = new Main();
>     main.whatsapp();
> }
> 
> private void whatsapp() {
>     WhatsappConfiguration configuration = WhatsappConfiguration.builder()
>             .whatsappUrl("wss://web.whatsapp.com/ws")
>             .requestTag("requestTag")
>             .description("Whatsapp4j")
>             .shortDescription("W4J")
>             .reconnectWhenDisconnected((reason) -> true)
>             .async(true)
>             .build();
> 
>     WhatsappAPI api = new WhatsappAPI(configuration);
>     api.registerListener(new WaStatusListener());
>     api.connect();
> }
> 
> private class WaStatusListener implements WhatsappListener {
>     @Override
>     public void onQRCode(@NonNull BitMatrix qr) {
>         Path path = FileSystems.getDefault().getPath("qr.png");
> 
>         try {
>             MatrixToImageWriter.writeToPath(qr, "PNG", path);
>         } catch (IOException e) {
>             e.printStackTrace();
>         }
> 
>         WhatsappListener.super.onQRCode(qr);
>     }
> 
>     public void onLoggedIn(@NonNull UserInformationResponse info) {
>         System.out.println("Connected :)");
>     }
> 
>     public void onDisconnected() {
>         System.out.println("Disconnected :(");
>     }
> }
> ```
> 
> }

Thanks very much. I can confirm that I can reproduce the bug, I'm working on a fix

**Comment by Auties00** [comment]
> Using - com.github.auties00:whatsappweb4j:2.2.5
> 
> `import com.google.zxing.client.j2se.MatrixToImageWriter; import com.google.zxing.common.BitMatrix; import it.auties.whatsapp4j.listener.WhatsappListener; import it.auties.whatsapp4j.response.impl.json.UserInformationResponse; import it.auties.whatsapp4j.whatsapp.WhatsappAPI; import it.auties.whatsapp4j.whatsapp.WhatsappConfiguration; import lombok.NonNull;
> 
> import java.io.IOException; import java.nio.file.FileSystems; import java.nio.file.Path;
> 
> public class Main {
> 
> ```
> public static void main(String[] args) {
>     Main main = new Main();
>     main.whatsapp();
> }
> 
> private void whatsapp() {
>     WhatsappConfiguration configuration = WhatsappConfiguration.builder()
>             .whatsappUrl("wss://web.whatsapp.com/ws")
>             .requestTag("requestTag")
>             .description("Whatsapp4j")
>             .shortDescription("W4J")
>             .reconnectWhenDisconnected((reason) -> true)
>             .async(true)
>             .build();
> 
>     WhatsappAPI api = new WhatsappAPI(configuration);
>     api.registerListener(new WaStatusListener());
>     api.connect();
> }
> 
> private class WaStatusListener implements WhatsappListener {
>     @Override
>     public void onQRCode(@NonNull BitMatrix qr) {
>         Path path = FileSystems.getDefault().getPath("qr.png");
> 
>         try {
>             MatrixToImageWriter.writeToPath(qr, "PNG", path);
>         } catch (IOException e) {
>             e.printStackTrace();
>         }
> 
>         WhatsappListener.super.onQRCode(qr);
>     }
> 
>     public void onLoggedIn(@NonNull UserInformationResponse info) {
>         System.out.println("Connected :)");
>     }
> 
>     public void onDisconnected() {
>         System.out.println("Disconnected :(");
>     }
> }
> ```
> 
> } `

Should be fixed, try version 2.2.6

**Comment by fisher926** [comment]
> > Using - com.github.auties00:whatsappweb4j:2.2.5
> > `import com.google.zxing.client.j2se.MatrixToImageWriter; import com.google.zxing.common.BitMatrix; import it.auties.whatsapp4j.listener.WhatsappListener; import it.auties.whatsapp4j.response.impl.json.UserInformationResponse; import it.auties.whatsapp4j.whatsapp.WhatsappAPI; import it.auties.whatsapp4j.whatsapp.WhatsappConfiguration; import lombok.NonNull;
> > import java.io.IOException; import java.nio.file.FileSystems; import java.nio.file.Path;
> > public class Main {
> > ```
> > public static void main(String[] args) {
> >     Main main = new Main();
> >     main.whatsapp();
> > }
> > 
> > private void whatsapp() {
> >     WhatsappConfiguration configuration = WhatsappConfiguration.builder()
> >             .whatsappUrl("wss://web.whatsapp.com/ws")
> >             .requestTag("requestTag")
> >             .description("Whatsapp4j")
> >             .shortDescription("W4J")
> >             .reconnectWhenDisconnected((reason) -> true)
> >             .async(true)
> >             .build();
> > 
> >     WhatsappAPI api = new WhatsappAPI(configuration);
> >     api.registerListener(new WaStatusListener());
> >     api.connect();
> > }
> > 
> > private class WaStatusListener implements WhatsappListener {
> >     @Override
> >     public void onQRCode(@NonNull BitMatrix qr) {
> >         Path path = FileSystems.getDefault().getPath("qr.png");
> > 
> >         try {
> >             MatrixToImageWriter.writeToPath(qr, "PNG", path);
> >         } catch (IOException e) {
> >             e.printStackTrace();
> >         }
> > 
> >         WhatsappListener.super.onQRCode(qr);
> >     }
> > 
> >     public void onLoggedIn(@NonNull UserInformationResponse info) {
> >         System.out.println("Connected :)");
> >     }
> > 
> >     public void onDisconnected() {
> >         System.out.println("Disconnected :(");
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > } `
> 
> Should be fixed, try version 2.2.6

Working!
Thanks!

**Comment by Auties00** [comment]
> > > Using - com.github.auties00:whatsappweb4j:2.2.5
> > > `import com.google.zxing.client.j2se.MatrixToImageWriter; import com.google.zxing.common.BitMatrix; import it.auties.whatsapp4j.listener.WhatsappListener; import it.auties.whatsapp4j.response.impl.json.UserInformationResponse; import it.auties.whatsapp4j.whatsapp.WhatsappAPI; import it.auties.whatsapp4j.whatsapp.WhatsappConfiguration; import lombok.NonNull;
> > > import java.io.IOException; import java.nio.file.FileSystems; import java.nio.file.Path;
> > > public class Main {
> > > ```
> > > public static void main(String[] args) {
> > >     Main main = new Main();
> > >     main.whatsapp();
> > > }
> > > 
> > > private void whatsapp() {
> > >     WhatsappConfiguration configuration = WhatsappConfiguration.builder()
> > >             .whatsappUrl("wss://web.whatsapp.com/ws")
> > >             .requestTag("requestTag")
> > >             .description("Whatsapp4j")
> > >             .shortDescription("W4J")
> > >             .reconnectWhenDisconnected((reason) -> true)
> > >             .async(true)
> > >             .build();
> > > 
> > >     WhatsappAPI api = new WhatsappAPI(configuration);
> > >     api.registerListener(new WaStatusListener());
> > >     api.connect();
> > > }
> > > 
> > > private class WaStatusListener implements WhatsappListener {
> > >     @Override
> > >     public void onQRCode(@NonNull BitMatrix qr) {
> > >         Path path = FileSystems.getDefault().getPath("qr.png");
> > > 
> > >         try {
> > >             MatrixToImageWriter.writeToPath(qr, "PNG", path);
> > >         } catch (IOException e) {
> > >             e.printStackTrace();
> > >         }
> > > 
> > >         WhatsappListener.super.onQRCode(qr);
> > >     }
> > > 
> > >     public void onLoggedIn(@NonNull UserInformationResponse info) {
> > >         System.out.println("Connected :)");
> > >     }
> > > 
> > >     public void onDisconnected() {
> > >         System.out.println("Disconnected :(");
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > } `
> > 
> > 
> > Should be fixed, try version 2.2.6
> 
> Working! Thanks!

Perfect

**Comment by Auties00** [comment]
> Same issue with the following exception
> 
> `Exception in thread "ForkJoinPool.commonPool-worker-7" java.lang.NullPointerException: WhatsappAPI: The session linked to the WebSocket is null at java.base/java.util.Objects.requireNonNull(Objects.java:233) at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.session(WhatsappWebSocket.java:486) at it.auties.whatsapp4j.whatsapp.internal.WhatsappWebSocket.lambda$scheduleQrCodeUpdate$1(WhatsappWebSocket.java:134) at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)`

Is it fixed also for you (version 2.2.6)

**Comment by SheikhZayed** [comment]
Fixed, Thanks
