### ISSUE TITLE
 Message receiving problem

### ISSUE THREAD

**Issue by hanjiuri** [Auties00/WhatsappWeb4j#84]
Hello, auties00, I have encountered a strange problem. There are no contacts in the address book. Sending a message to me for the first time will result in receiving the same message indefinitely

![image](https://user-images.githubusercontent.com/29794210/146885077-da575dfc-afaa-411d-854b-6a4a609ff888.png)

**Comment by Auties00** [comment]
> Hello, auties00, I have encountered a strange problem. There are no contacts in the address book. Sending a message to me for the first time will result in receiving the same message indefinitely
> 
> ![image](https://user-images.githubusercontent.com/29794210/146885077-da575dfc-afaa-411d-854b-6a4a609ff888.png)

Can you show me your code.

**Comment by hanjiuri** [comment]
`public static void main(String[] args) {
        WhatsappAPI whatsappAPI = new WhatsappAPI();
        whatsappAPI.registerListener(new YourAwesomeListener());
        whatsappAPI.connect();
}`
`public class YourAwesomeListener implements WhatsappListener {

    @Override
    public void onLoggedIn(@NonNull UserInformationResponse info) {
        System.out.println(info);
    }


    @Override
    public void onNewMessage(@NonNull Chat chat, @NonNull MessageInfo message) {
        TextMessage textMessage = message.container().textMessage();
        if(textMessage!=null){
            System.out.println("chatJid:"+chat.jid()+",msg:"+textMessage.text());
        }
    }

    public void onDisconnected() {
        System.out.println("Disconnected :(");
    }
}`

`<dependencies>
        <dependency>
            <groupId>com.github.auties00</groupId>
            <artifactId>whatsappweb4j</artifactId>
            <version>2.2.6</version>
        </dependency>
    </dependencies>`

**Comment by hanjiuri** [comment]
`public class Test {
    public static void main(String[] args) {
        WhatsappAPI whatsappAPI = new WhatsappAPI();
        whatsappAPI.registerListener(new YourAwesomeListener());
        whatsappAPI.connect();
    }
}`

`public class YourAwesomeListener implements WhatsappListener {

    @Override
    public void onLoggedIn(@NonNull UserInformationResponse info) {
        System.out.println(info);
    }


    @Override
    public void onNewMessage(@NonNull Chat chat, @NonNull MessageInfo message) {
        TextMessage textMessage = message.container().textMessage();
        if(textMessage!=null){
            System.out.println("chatJid:"+chat.jid()+",msg:"+textMessage.text());
        }
    }

    public void onDisconnected() {
        System.out.println("Disconnected :(");
    }
}`

`<dependencies>
        <dependency>
            <groupId>com.github.auties00</groupId>
            <artifactId>whatsappweb4j</artifactId>
            <version>2.2.6</version>
        </dependency>
    </dependencies>`

**Comment by hanjiuri** [comment]
chatJid:85362157566@s.whatsapp.net,msg:Hello
chatJid:85362157566@s.whatsapp.net,msg:Hello
chatJid:85362157566@s.whatsapp.net,msg:Hello
chatJid:85362157566@s.whatsapp.net,msg:Hello
chatJid:85362157566@s.whatsapp.net,msg:Hello
chatJid:85362157566@s.whatsapp.net,msg:Hello
chatJid:85362157566@s.whatsapp.net,msg:Hello
chatJid:85362157566@s.whatsapp.net,msg:Hello
chatJid:85362157566@s.whatsapp.net,msg:Hello
chatJid:85362157566@s.whatsapp.net,msg:Hello
chatJid:85362157566@s.whatsapp.net,msg:Hello
chatJid:85362157566@s.whatsapp.net,msg:Hello
chatJid:85362157566@s.whatsapp.net,msg:Hello
chatJid:85362157566@s.whatsapp.net,msg:Hello
chatJid:85362157566@s.whatsapp.net,msg:Hello


Only the first dialogue will get such a result

**Comment by hanjiuri** [comment]
![WechatIMG260](https://user-images.githubusercontent.com/29794210/147033131-11f54ef4-b1ea-466f-9dd0-e3bbefe09cbc.jpeg)

**Comment by hanjiuri** [comment]
![WechatIMG260](https://user-images.githubusercontent.com/29794210/147033416-83e5a86e-b187-43b5-a48b-d1edc92b3cf0.jpeg)

**Comment by hanjiuri** [comment]
Can this bug be solved? Where is the problem

**Comment by Auties00** [comment]
> 

I will fix it in a few days. I think I know the problem. Are you still experiencing it just to be sure?

**Comment by Auties00** [comment]
> Can this bug be solved? Where is the problem

I will fix it in a few days.
Just to be sure, are you still experiencing this on the latest version?

**Comment by hanjiuri** [comment]
是的，2.2.6版本有这个问题

**Comment by hanjiuri** [comment]
Yes, version 2.2.6 has this problem

**Comment by Auties00** [comment]
> Yes, version 2.2.6 has this problem

Can you try 2.2.7?
