### ISSUE TITLE
When will the session expire?

### ISSUE THREAD

**Issue by hmbyl** [Auties00/WhatsappWeb4j#85]
I saved the session, which includes client token, server token in a file, then I   restore  the session , sometimes I found I can not connect server with the session I saved. So when the session will be expired?

**Comment by Auties00** [comment]
> I saved the session, which includes client token, server token in a file, then I restore the session , sometimes I found I can not connect server with the session I saved. So when the session will be expired?

The session should never expire, a challenge might be presented to the client to confirm ownership of the credentials, but it should be solved automatically

**Comment by hmbyl** [comment]
but I did not find the server send the challenge request to the client

**Comment by Auties00** [comment]
> but I did not find the server send the challenge request to the client

Do you have a log of that?
