### ISSUE TITLE
the connection always disconnect after scanning the QR code

### ISSUE THREAD

**Issue by hmbyl** [Auties00/WhatsappWeb4j#89]
When I scanned the QR code and login the server, my own listener onDisconnected function will always be called.  But the connection will be reconnected after a few seconds.

 @Override
    public void onDisconnected() {

        System.out.println("disconnect");// always be called after scanning the QR code
    }

**Comment by hanjiuri** [comment]
```
private void sendInitialRequest(Session session) {
        if(loggedIn){
            return;
        }
        new InitialRequest<InitialResponse>(options, whatsappKeys){}
                .send(session)
                .thenAccept(this::handleInitialMessage);
    }
```
I also encountered this problem. Try this code

**Comment by hmbyl** [comment]
> ```
> private void sendInitialRequest(Session session) {
>         if(loggedIn){
>             return;
>         }
>         new InitialRequest<InitialResponse>(options, whatsappKeys){}
>                 .send(session)
>                 .thenAccept(this::handleInitialMessage);
>     }
> ```
> 
> I also encountered this problem. Try this code

Thanks so much ,it works

**Comment by hmbyl** [comment]
there is another question, when the network is broken down, such as I close the network manually, so how can I check whether the connection is connected?

**Comment by Auties00** [comment]
> When I scanned the QR code and login the server, my own listener onDisconnected function will always be called. But the connection will be reconnected after a few seconds.
> 
> @OverRide public void onDisconnected() {
> 
> ```
>     System.out.println("disconnect");// always be called after scanning the QR code
> }
> ```

What version are you using?
