### ISSUE TITLE
Delete credentials manually

### ISSUE THREAD

**Issue by hamedsharifi** [Auties00/WhatsappWeb4j#93]
Hello

My account has been blocked by Whatsapp and when I run my app it can't detect that situation and run Qrcode again. how can I manually delete this account ceredentials.

**Comment by Auties00** [comment]
> Hello
> 
> My account has been blocked by Whatsapp and when I run my app it can't detect that situation and run Qrcode again. how can I manually delete this account ceredentials.

api.keys().

> Hello
> 
> My account has been blocked by Whatsapp and when I run my app it can't detect that situation and run Qrcode again. how can I manually delete this account ceredentials.

https://www.javadoc.io/static/com.github.auties00/whatsappweb4j/2.2.6/whatsapp4j/it/auties/whatsapp4j/manager/WhatsappKeysManager.html#deleteKeysFromMemory()
